- README.md
I could also add the line back but with a deprecated note:
```
* [zshuery](https://github.com/myfreeweb/zshuery) - [DEPRECATED] A simpler zsh configuration framework. jQuery did this for JS, we're doing it for zsh. 
```
> Remove zshuery as it's deprecated

- README.md
Previous one 404'd to https://github.com/unixorn/awesome-zsh-plugins/blob/master/sharat87/zsh-vim-mode
> Fix the link to zsh-vim-mode

- README.md
It was merged into the main zaw repository, so zaw-extras is now just a readme file saying that it was merged.
> Remove zaw-extras

- README.md
* Clean up frameworks section
* Add generic zsh heading to tutorials section
* Mention that zgen, antigen and antigen-hs all handle cloning plugins automatically
> Readme tuneups

- README.md
A zsh plugin for generating a GitHub short URL using [git.io](https://git.io). Inspired by [tiny](https://github.com/fishery/tiny) utility by [Jorge Bucaran](https://github.com/bucaran).
**Usage:**
```zsh
gitio <[https://github.com/]username/repo> [cool-url]
```
> Add gitio-zsh.

- README.md
sorin-ionescu/prezto is an abandoned project, the new living community
fork is on zsh-users organisation now.
Refs: https://github.com/sorin-ionescu/prezto/issues/1239
> prezto: Update links to the new community home of prezto

- README.md
The aim of this plugin is to set a random but consistent tab color on iTerm tabs based on the directory you are in. If you have more than one tab in the same working directory they will have the same color and will remain the same every terminal session.
> Added iterm-tab-colors to Plugin section

- README.md
`zsh-interactive-cd` is a fish like interactive tab completion plugin for `cd`.
> Add zsh-interactive-cd

- README.md
Today's released plugin `zdharma/fast-syntax-highlighting`, optimized and improved version of `zsh-users/zsh-syntax-highlighting`
> Add fast-syntax-highlighting plugin

- README.md
Zsh steeef theme as a standalone repository. The purpose behind this repo is avoid having a dependency on oh-my-zsh when using the steeef theme. Zsh plugin managers such as Antibody can use the theme without having to use oh-my-zsh.
> Add steef theme as a standalone

- README.md
Removed carcassoid theme since it has gone 404.
> carcassoid has gone 404

- README.md
`zsh-docker-run` allows users to go back to the simpler times of runnning `php -r 'echo "Hello";'` and `npm install`, even while running said commands in containers.
This plugin will also detect if your command should be run in a `docker-compose` environment, by inspecting the local directory.
> Adding `zsh-docker-run` to plugins

- .codeclimate.yml
Disable markdownlint's ordered list item prefix style check
> Disable markdownlint's ordered list item prefix style check

- README.md
A lot of things are named oh-my-zsh-this and oh-my-zsh-that. Trim off the oh-my-zsh to make it clear these don't require oh-my-zsh specifically, just an omz-compatible plugin manager.
> Remove omz from names

- README.md
Adds tab completions for [pass](https://www.passwordstore.org/)
> Add tab completions for pass

- README.md
Remove `zsh-` from names of plugins so the plugins don't cluster in the **z** section of the list
> Remove zsh- from names of plugins

- README.md
Add [zsh-colored-man-pages](https://github.com/ael-code/zsh-colored-man-pages)
> Add zsh-colored-man-pages plugin

- README.md
* Fix typo in sugar-free theme name
* Remove 404 bureau-colorized theme
> Fix typo in theme name

- README.md
Would you merge this?
Add [sys-diver-zsh](https://github.com/ToruIwashita/sys-diver-zsh) plugin.
> Add sys-diver-zsh plugin

- README.md
Added one important link, to description of Turbo Mode, on Zplugin's github page.
> Update Zplugin description (add Turbo Mode link)

- README.md
Adding the new plugin i've created for fast case changing between upper and lower case in your command line.
Adding the new plugin i've created for fast case changing between upper and lower case in your command line.
> Adding Change Case Plugin

- README.md
Move hacker-quotes to plugin section. Closes #378
> Move hacker-quotes to plugin section

- README.md
A script that lets you add the current Kubernetes context and namespace configured on kubectl to your Zsh prompt strings 
- [x ] Add/remove a plugin
- [x ] I have confirmed that the link(s) in my PR are valid.
- [x ] My entries are single lines and are in the appropriate (plugins, themes, completions) section.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I have stripped leading and trailing **zsh-** or **oh-my-zsh-** substrings from the link name. This makes it easier to find plugins/themes/completions by name since there aren't big clusters in the o and z sections of the list.
> ZSH kube-ps1 prompt helper for kubectl

- README.md
Thanks to @dikiaap for the heads up
Update tmux links to use https://tmux.github.io instead of http://tmux.sourceforge.net and https://github.com/tmux/tmux/wiki
> Update tmux links to https://tmux.github.io

- README.md
* Clean up themes section by stripping `zsh-` prefixes and resorting theme section
* Add [comxtohr](https://github.com/comxtohr/comxtohr-zsh-iterm-theme) theme
* Add [zqt](https://github.com/ladychili/zqt-zsh-theme) theme
* Remove docker_fun completions that have gone 404.
> Strip zsh prefix from themes

- README.md
This commit adds my two recent plugins:
- careful_rm: a python rm wrapper that integrates into ZSH and provides
useful warnings, a recycle/trash mode, and a shred mode, while being a
drop in replacement for rm
- tmux-zsh-vim-titles: a set of plugins for ZSH, tmux, and Vim/NVIM that
creates a unified terminal title with information from all three. Fully
modular so adds value for tmux, ZSH, and Vim/NVIM independently,
although it works best when all three are used together.
> Add careful_rm and tmux-zsh-vim-titles plugins

- README.md
* Add completion for SSH
* Clean up completions section
* Make references to ssh command consistently `ssh`
> Tweak ssh references

- README.md
Add [tmux-vim-integration](https://github.com/jsahlen/tmux-vim-integration.plugin.zsh)
> Add link to tmux-vim-integration plugin

- README.md
Made zed entry consistent with other entries that include zsh in their name
> Make zed entry consistent with other entries with zsh in their name

- README.md
Remove trailing .plugin.zsh from a bunch of the link text
> Clean up link names

- README.md
I have renamed agkozak/agkozak-zsh-theme to agkozak/agkozak-zsh-prompt.
> Updated agkozak-zsh-prompt repo name

- README.md
Update the plugin source from "jgrowl/depot_tools" to "kuoe0/zsh-depot-tools". The old one cannot get the latest depot_tools from chromium so that I updated the plugin to do that.
> replace depot_tools plugin to get latest depot_tools

- README.md
Add author to disambiguate the other q plugin entry
> Add author to disambiguate the other q plugin entry

- README.md
Update autopair desc to show ZSH > 5.0.2 requirement
> Update autopair desc to show ZSH > 5.0.2 requirement

- README.md
* Add [aftermath](https://github.com/schanur/aftermath) and [rougarou](https://github.com/RougarouTheme/rougarou-zsh)
* Fix [staples](https://github.com/dersam/staples) description
> Add aftermath and rougarou themes

- README.md
* Add [zsh-command-note.plugin](https://github.com/KKRainbow/zsh-command-note.plugin)
> Add link to command-note plugin

- README.md
* Fix names of completions and ipfs entries
> Trim leading zsh in link names in completions section

- README.md
Trim a bunch of trailing `-zsh` from link names for consistency with the contribution guidelines
> Trim a bunch of trailing `-zsh` from link names

- zsh-plugin-assessor/zsh-plugin-assessor
I've updated `zsh-plugin-assessor`. It now almost-fully can work incrementally, for newly added plugins only (i.e. no emoji yet), with option -n/--only-new. The problem: stalled inactive plugins also have no-emoji assigned, so ZPA will recognize them as "new" and will search for an emoji for them. This is easily fixable: a non-rendered markdown character is needed, to mark processed no-emoji plugins. That said, ZPA now processes the README in 9 minutes, instead of 31 minutes.
Added `zparseopts` sophisticated option handler, -q/--quiet option, fixed bug with displaying # of themes found.
> ZPA: Work faster/incrementally, bugfixes

- README.md
Added plugin ZSH-z (native ZSH drop-in replacement for `z.sh`).
Don't you think I should leave it as *zsh-z*, rather than stripping the *zsh-* from the beginning? I don't want people to think that it's the famous `z`; it's closely related, but a little different.
> Added plugin ZSH-z

- README.md
* Fix link name of rake-completion plugin
* Disambiguate link titles for the two `ssh-agent` tab completion plugins by adding the GitHub usernames of their authors
* Fix link title for vert.x plugin
* Add bash-quote and hab plugins
> 2019-03-03 Updates

- README.md
Re-run doctoc to fix TOC link 'Completions' in README
> Re-run doctoc to fix TOC link 'Completions' in README

- .circleci/config.yml
- README.md
* Add [aws-cli-mfa](https://github.com/joepjoosten/aws-cli-mfa-oh-my-zsh) plugin
* Add [vi-mode (Nyquase)](https://github.com/Nyquase/vi-mode) plugin
> Add aws-cli-mfa and vi-mode plugins

- README.md
https://github.com/perlpunk/App-AppSpec-p5
It can autogenerate Bash and ZSH completions from a specification
file in App::Spec YAML format.
Followup to our discussion in https://github.com/perlpunk/MooseX-App-Plugin-ZshCompletion/issues/3
Installation and Usage instructions were added, and I added a standalone version that can be used without installing perl modules.
> Add appspec tool

- README.md
The purien zsh plugin/theme has been discontinued and the public repository is no longer exists. Just delete the reference to that repository.
> Delete purien zsh prompt theme: deprecated

- README.md
* sobolevn and wbingli both have plugins named wakatime, disambiguate their names as part of making them both conform to the preferred list entry style.
> Disambiguate wakatime plugins

- README.md
Similar to system-clipboard, but also allows access to vim and nvim registers.
Yes, it's mine. I waited until now because I don't think I'm changing its API anymore.
[Evil-registers](https://github.com/zsh-vi-more/evil-registers) is similar to a plugin already on the list, system-clipboard. However, this plugin brings in a few features:
- **Extensible**: by setting an element of an array to a snippet, the snippet will be run with the text that was yanked.
- **Supports remote access to editors**: Currently only vim with `+clientserver` support and nvim with [nvr](https://github.com/mhinz/neovim-remote) is supported. `"ap` will read from the `a` register from the respective editor, if it is running.
This is my plugin, so I understand skepticism. However, I have been using it comfortably for …
> Add evil-registers

- README.md
* gime was renamed [gimme](https://github.com/nralbrecht/gimmezsh) upstream, rename in list.
> Rename gime to gimme in list

- README.md
* Fix sort in plugins section
* Add [pentest](https://github.com/jhwohlgemuth/oh-my-zsh-pentest-plugin) plugin
* Add [pyenv](https://github.com/mattberther/zsh-pyenv) plugin
* Add [tfenv](https://github.com/CDA0/zsh-tfenv) plugin
* Add [docker (greymd)](https://github.com/greymd/docker-zsh-completion) completions
* Update several link descriptions
> November 17th, 2019 updates

- README.md
* Add link to [cheatsheet](https://github.com/0b10/cheatsheet) plugin
> Add link to cheatsheet plugin

- Writing_Plugins.md
All files in the fpath directories should be able to be compiled. See http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Recompiling-Functions
This allows ZSH to take advantage of compiled function digest files. See http://zsh.sourceforge.net/Doc/Release/Functions.html#Autoloading-Functions
> Add advise about fpath to Writing_Plugins.md

- README.md
* Replace zplugin with Zinit in plugin descriptions
* Update urls of zplugin/z-a-* to use zinit-zsh/z-a-*
* Remove anki-code/bar theme that has gone 404
* Minor wording tweaks throughout
> More zplugin -> zinit naming changes

- README.md
I've built a zsh plugin for heavy users of [jq](https://stedolan.github.io/jq/). The plugin provides a line editor feature with `alt +j`.
> Add jq-zsh-plugin

- README.md
The domain doesn't exist anymore (NXDOMAIN). This breaks CI test in this repo.
Context: https://github.com/test-kitchen/test-kitchen/issues/1616
> Add valid link for test kitchen

- README.md
* Add p9k-theme-pastel now that https://github.com/iboyperson/p9k-theme-pastel/issues/1 is closed.
* Removing nonotes - it is 404.
> Add p9k-theme-pastel, remove nonotes

- README.md
The Plugins tab describes the functions ``tolower`` and ``touper``, but the latter is ``toupper`` in the actual repo's description.
Request to fix that typo. :)
- [ x ] This document is covered by the [BSD License](https://github.com/unixorn/awesome-zsh-plugins/blob/master/LICENSE), and I agree to contribute this PR under the terms of the license.
- [ x ] I have confirmed that the link(s) in my PR are valid.
- [ x  ] My entries are single lines and are in the appropriate (plugins, themes or completions) section, and in alphabetical order in their section.
- [ x ] I have read the **CONTRIBUTING** document.
> Update README.md to fix typo in "case" plugin description.

- README.md
Now that https://github.com/sirhc/op.plugin.zsh/issues/1 and https://github.com/sirhc/okta.plugin.zsh/issues/1 are closed, add the op and Okta tab completion plugins.
> Add op and Okta tab completion plugins

- README.md
* Add  abbr plugin
* Add ubuntu-with-vitamins theme now that https://github.com/ureesoriano/zsh-ubuntu-with-vitamins-zim-theme/issues/1 is closed
> Add abbr plugin and ubuntu-with-vitamins theme

- README.md
* Update URL for zsh-ipfs tab completions
> Update URL for zsh-ipfs tab completions

- README.md
- Add [`zoxide`](https://github.com/ajeetdsouza/zoxide) under Plugins
`zoxide` is a ZSH plugin that tracks your directory usage, allowing you to quickly `cd` to anywhere on your filesystem using just part of the directory name as a query.
> Add zoxide under Plugins

- README.md
> Remove ruby-switch that has gone 404

- README.md
* Add ptavares/zsh-kubectx plugin
- [x ] This document is covered by the [BSD License](https://github.com/unixorn/awesome-zsh-plugins/blob/master/LICENSE), and I agree to contribute this PR under the terms of the license.
> Add ptavares/zsh-kubectx plugin

- README.md
Add link to [buidler](https://github.com/gonzalobellino/buidler-zsh) now that https://github.com/gonzalobellino/buidler-zsh/issues/1 is closed.
> Add buidler completions plugin

- .github/PULL_REQUEST_TEMPLATE.md
Update the PR template to add an option for frameworks
> Add framework option to PR template

- README.md
Add mvn-contexts now that https://github.com/artemy/zsh-mvn-contexts/issues/1 is closed.
> Add zsh-mvn-contexts plugin

- README.md
Add https://github.com/pinelibg/dircolors-solarized-zsh, disambiguate joel-porquet's.
> Adds pinelibg's solarized dircolors plugin

- .circleci/config.yml
1password.com has occasional 20X errors, whitelist it in the ci tests.
> Whitelist 1password.com

- README.md
Add the Michiel Mulders tutorial on how installing Oh-My-Zsh! on Ubuntu. Since this is one of the most viewed tutorials, I think will be useful to new users.
> Add Oh-My-Zsh! A Work of CLI Magic to the list os tutorials

- README.md
* Add dzhi theme now that https://github.com/pentago/dzhi-zsh-theme/issues/1 is closed.
* Add nctu theme now that https://github.com/leovincentseles/nctu.zsh-theme/issues/2 is closed.
> Add dzhi and nctu themes

- .github/workflows/awesomebot.yml
- README.md
* Switch from circleCI badge to a Github actions status badge
* Remove 404ing saltgen theme
> Update badges, remove 404 saltgen

- README.md
Add link to [ZSH for Humans](https://github.com/romkatv/zsh4humans)
> Add link to ZSH for humans tutorial

- README.md
* Add fzf-zsh-completions tab completion plugin
* Add hematite now that https://github.com/bigdave/hematite/issues/1 is closed
> Add fzf-zsh-completions tab completion plugin and hematite theme

- README.md
Move s3cmd to completions section, update description
> Move s3cmd to completions section, update description

- README.md
Add nodenv now that https://github.com/C-uo/zsh-env/issues/2 is closed.
* Add c-uo's nodenv plugin
> Add c-uo's nodenv plugin

- README.md
Adds the recently created [zsh-emacs](https://github.com/cowboyd/zsh-emacs) plugin to the list.
> Add zsh-emacs

- README.md
This adds the `zsh-volta` plugin to the list which automatically configures the [Volta](https://volta.sh) toochain manager, downloading it beforehand if it is not installed already.
> Add zsh-volta to the plugins list

- README.md
Add pentesters theme now that https://github.com/sdcampbell/lpha3cho-Oh-My-Zsh-theme-for-pentesters/issues/1 is closed.
> Add pentesters theme

- README.md
Add SukkaW's gitcd plugn, disambiguate viko16's
> Add SukkaW's gitcd plugin

- README.md
Remove deprecated fzf-git plugin. Closes #1125
> Remove deprecated fzf-git plugin

- README.md
- Add 4den now that there's a screen shot. Closes https://github.com/RunThem/zsh-theme-4den/issues/1
- Remove 404 link to https://linhmtran168.github.io/blog/2013/12/15/ditching-oh-my-zsh-for-prezto/
> Add 4den theme

- README.md
Updates a link to point to GitHub instead of GitLab. The GitLab link 404s, but the repo seems to be on GitHub.
> Fix link to hermitmaster/zsh-exa-plugin

- README.md
> Add quickjump completion

- README.md
> Add ptavares' exa plugin

- README.md
Fix sort of the vi-mode plugins
> Fix sort of vi-mode plugins

- README.md
Hello, I would like to add a simple plugin that I created to the plugins list. It prints out an ASCII picture of a cow saying a random epigram on every zsh start. 🐄
> Adds "babasbot/auto-fortune-cowsay" to the plugin list

- README.md
Remove unreachable zdharma.org links that are causing awesomebot checks to fail. Will restore them after https://github.com/zdharma/zinit/issues/489 is closed.
> Remove unreachable zdharma.org links

- README.md
- Add [cod](https://github.com/dim-an/cod), a completion demon for bash/fish/ZSH which creates completion functions on the fly when it sees you run something with `--help`.
- x] This document is covered by the [BSD License](https://github.com/unixorn/awesome-zsh-plugins/blob/master/LICENSE), and I agree to contribute this PR under the terms of the license.
> St. Patrick's Day - Add cod completion daemon

- README.md
> Fix typo in markdown

- README.md
Add heuristic command suggestion system for ZSH.
Add plugin called [hbt](https://github.com/lzambarda/hbt), which provides heuristic command suggestion based on past usage.
> Add hbt plugin

- README.md
- Now that https://github.com/r3nic1e/r3nic1e-zsh-theme/issues/1 is closed, add r3nic1e theme
- Clean up some agnoster references that weren't links
- Add inspr tab completion
> 2021-05-11 Updates

- README.md
- Add link to [bw](https://github.com/CupricReki/zsh-bw-completion) tab completion
- Add link to [comonicon](https://github.com/Roger-luo/ComoniconZSHCompletion.jl) tab completion
> Add comonicon and bw tab completions

- .github/PULL_REQUEST_TEMPLATE.md
- Contributing.md
- Call out need for readmes in PR template
- Update contributing guidelins
> Require readmes in new entries

- README.md
This PR adds a link to [`fzf-gcloud`](https://github.com/mbhynes/fzf-gcloud), which is a plugin that provides `fzf` autocompletion for the google cloud SDK's `gcloud` CLI.
The plugin provides the following autocompletion widget:
- (tested on the file [here](https://github.com/unixorn/awesome-zsh-plugins/blob/89a15bf62e53498b91e2e026511fd2c356d8ad8e/README.md))
> Add `fzf-gcloud` repo to awesome zsh plugins list

- README.md
- Add kubectl-fzf  tab-completion for `kubectl`, powered by `fzf`.
- Add git-fuzzy plugin
> Add kubectl-fzf tab completion and git-fuzzy plugin

- README.md
- Add xlk-simple now that https://github.com/xuelingkang/xlk-simple-zsh-theme/issues/1 is closed.
- Add eleastic theme
> Add xlk-simple and eleastic themes

- README.md
Miniplug's canonical source code repository is on sourcehut: https://sr.ht/~yerinalexey/miniplug. The Github repository right now works as a mirror and may be deleted in the future.
> Relocate miniplug to sr.ht

- README.md
Add tab completions for the github CLI
> Add tab completions for the github CLI

- README.md
Add emojirussell theme. Closes https://github.com/Bergiu/emojirussell/issues/1
> Add emojirussell theme

- README.md
Fix ZSH reference in magicmace entry
> Fix ZSH reference in magicmace entry

- README.md
> Fix link for "nodenv (mattberther)"

- README.md
- Add `shelby` theme
- Update `zinit` link to point to a mirror
- It looks like psprint  deleted all of their ZSH plugins from github. Pity, there was some very good stuff there.
Deleted:
* [declare-zsh](https://github.com/zdharma/declare-zsh) - A command-line parser for Zinit commands in `zshrc`.
* [diff-so-fancy](https://github.com/zdharma/zsh-diff-so-fancy) - Simplify installing the `diff-so-fancy` project into your user account.
* [editing-workbench](https://github.com/psprint/zsh-editing-workbench) - Adds sane, complex command line editing (e.g. incremental history _word_ completion).
* [github-issues](https://github.com/zdharma/zsh-github-issues) - Subscribe to projects on Github and receive within shell (under prompt) notifications about new issues.
* …
> Delete dead psprint links, add shelby theme

- README.md
> Add ztouch plugin

- README.md
Add missing trailing `.` to entries in ZSH tools section.
> Add missing trailing `.` in ZSH tools section

- README.md
add [media-sync](https://github.com/redxtech/zsh-media-sync).
> add media-sync plugin

- README.md
- Add link to github-issues mirror. Closes #1337
- nvm-auto is 404, removing
> Add link to github-issues mirror

- README.md
It's just a fork, but doesn't provide anything different from the upstream (the reegnz one).
> Remove jq-zsh-plugin fork

- README.md
> Add git-is-clean plugin

- README.md
- Add a link to the ZSH unplugged un-framework
- Add rhoas tab completion
> Add ZSH Unplugged and rhoas completion

- README.md
- https://github.com/DevinLeamy/just-around-the-corner/issues/1 is closed, add `just-around-the-corner` theme.
- Remove code climate badge
- Update TOC
> Add just-around-the-corner theme

- README.md
Add scythe now that https://github.com/kostoskistefan/scythe/issues/1 is closed.
> Add scythe theme

- README.md
https://github.com/milespossing/Azure-Keyvault-Zsh/issues/1 is closed, add azure-keyvault plugin
> Add azure-keyvault

- README.md
Clean up zsh-quicstart-kit, ZPWR, and Black-Void entries
> Clean up zsh-quicstart-kit, ZPWR, and Black-Void entries

- README.md
- Add `spyrhoo` theme
- Add `zstyle-completions`
> Add spyrhoo theme and zstyle completions

- README.md
- Add ssfprompt theme
- Add expressvpn tab completion
> Add ssfprompt theme and expressvpn tab completion

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- Add instructions for signing off on commits to the PR template and a link to the DCO action help.
- Add `git-worktree` plugin now that https://github.com/alexiszamanidis/zsh-git-worktree/issues/1 is closed
> Add signoff instructions to PR template and git-worktree plugin

- README.md
- ivyhjk/ohmyzsh-theme-ivy#1 is closed, add ivy theme
- hgaiser/gruvbox-zsh#2 is closed, add gruvbox theme
> Add ivy and gruvbox themes

- README.md
- Add tab completions for Jenkins-X cli
- Razor is 404 now, so removing its tab completion
> Add jx tab completion

- .github/PULL_REQUEST_TEMPLATE.md
Clarify that the BSD license is just for the list, not necessarily for the plugins added.
> Update PR template to clarify license

- README.md
Add linuxero now that https://github.com/andreshincapier/linuxero/issues/1 is closed.
> Add linuxero theme

- README.md
- https://github.com/ianthehenry/zsh-expander/issues/1 is closed, add `expander` ZLE widget plugin.
- Add `autoquoter` plugin
- Add `drupal` plugin. Closes https://github.com/yhaefliger/zsh-drupal/issues/1
> Add autoquoter, drupal and expander plugins

- README.md
https://github.com/spikespaz/autoupdate-antibody-zsh
> Add autoupdate-antibody to Plugins

- README.md
https://github.com/jelek21/omz-git-smart-commands/issues/1 is closed, add `git-smart-commands` wrapper plugin
> Add git-smart-commands wrapper plugin

- README.md
- Add `asdf-prompt` plugin
- Brokenhammer72 account is 404, delete their `fizzy` theme
> Add asdf-prompt

- README.md
> Update fzf-finder entry

- README.md
- Writing_Plugins_and_Themes.md
- Minor reformatting
- Warn authors not to override ZSH default settings without a really good reason.
> Update plugin/theme guide

- .codeclimate.yml
- Writing_Plugins_and_Themes.md
- `exclude_paths` has been deprecated,
- `engines` has been deprecated,
- `exclude_paths` has been deprecated,
- `ratings` have been deprecated.
Notes: linted with new configuration (1 file): Writing_Plugins_and_Themes.md
```shell
➜  awesome-zsh-plugins git:(codeclimate) ✗ codeclimate validate-config
No errors or warnings found in .codeclimate.yml.
```
```shell
➜  awesome-zsh-plugins git:(codeclimate) ✗ codeclimate analyze        
Starting analysis
Running structure: Done!
Running duplication: Done!
Running pep8: Done!
Running fixme: Done!
Running markdownlint: Done!
Running shellcheck: Done!
```
```shell
== README.md (4 issues) ==
105: Lists should be surrounded by blank lines [markdownlint]
2116: Multiple headers with the same content [markdownlint]
2144: Multiple headers with the same …
```
> style: ✅ Update codeclimate.yml

- README.md
Add ddev plugin for https://github.com/drud/ddev
> Add ddev plugin

- README.md
Add bio completions - closes https://github.com/yamaton/zsh-completions-bio/issues/1
> Add bio completions

- README.md
> Add github-folders plugin

- README.md
- Add tab completion for `speedtest`
- Move `pipenv` plugin from completions section to plugins section
> Add speedtest tab completion

- README.md
Add [1password-op](https://github.com/unixorn/1password-op.plugin.zsh) completions for 1Password's [op](https://developer.1password.com/docs/cli/get-started/) command line tool.
> Add 1password-op tab completions plugin

- README.md
- Add `bw` plugin for bitwarden
- Remove 404 `bougenville` plugin
> Add `bw` plugin for bitwarden

- README.md
- https://github.com/chammanganti/a-zsh-theme/issues/1 is closed, add `a` theme.
- https://github.com/daniilty/rounded-zsh-theme/issues/1 is closed, add `rounded` theme
- Add `terragrunt` tab completion
> Add `a`, `rounded` and `terragrunt` plugins

- README.md
> Add backcountry plugin

- README.md
`nodo` keeps `node_modules` directories from filling up your iCloud storage.
> Add nodo plugin

- README.md
Add `nhl-schedule`, closes https://github.com/Matt561/zsh-nhl-schedule/issues/1
> Add nhl-schedule plugin

- README.md
- Fix typo in nhl plugin entry introduced in https://github.com/unixorn/awesome-zsh-plugins/commit/d44cbd76130418f0f6e399e6cc187e43cadd7f88
- Add `gstreamer` tab completion
- Add `al-magic` theme, closes https://github.com/Alustrat/al-magic/issues/1
Thanks @matt561 for the catch
> Typo fix in `nhl` entry, add `gstreamer-tab` and `al-magic`

- README.md
> Add todie's exa plugin

- README.md
Update url for @MartinSimango's kubectl completion plugin
> Update url for @MartinSimango's kubectl completion plugin

- README.md
Update entry for  `autoupdate-oh-my-zsh-plugins`. Closes https://github.com/TamCore/autoupdate-oh-my-zsh-plugins/issues/15
> Update entry for  `autoupdate-oh-my-zsh-plugins`

- README.md
af-magic-mod went 404, remove entry
> Remove 404 af-magic-mod theme

- README.md
Add dyzsh, closes https://github.com/daotoyi/dyzsh-zsh-theme/issues/1
> Add dyzsh theme

- README.md
- Add `zi-rbenv` plugin
- Add baliestri's `pnpm`, disambiguate ntnyq's.
- Add `021011` theme
- Add `brew-completions` tab-completion plugin
- Add `click-completion` tab-completion plugin
- Add `ssh` completion plugin
> 2022-05-10 updates

- README.md
- Add `promptor` theme now that https://github.com/MickaelBlet/Promptor/issues/1 is closed
- baliestri's `pnpm` plugin is 404, remove
- Update ntnyq's `pnpm` plugin since it no longer needs to be disambiguated.
> Add promptor theme, remove 404 pnpm plugin

- README.md
Add `goenv` now that https://github.com/heyvito/goenv.zsh/issues/1 is closed.
> Add goenv plugin

- README.md
Add mainnika theme - closes https://github.com/mainnika/zsh-theme-mainnika/issues/1
> Add mainnika theme

- README.md
> Add gimbo's `fzf` plugin

- README.md
Adds baliestri's `pnpm` plugin and disambiguates `ntnyq`'s.
> Add `pnpm` plugin

- README.md
closes https://github.com/gusrylmubarok/gusrylmubarok-zsh-theme/issues/1
> Add `gusyrylmybarok` theme

- README.md
> Add `paxton` theme

- README.md
Add tarcadia theme. Closes https://github.com/Tarcadia/tarcadia-zsh-theme/issues/1
> Add tarcadia theme

- README.md
Add `github` theme now that https://github.com/Debdut/github.zsh-theme/issues/1 is closed.
> Add `github` theme

- README.md
> Add `shinkansen` theme

- README.md
Add `Vicfs/smelly-theme`. Closes https://github.com/Vicfs/smelly-theme/issues/1
> Add Vicfs/smelly-theme

- README.md
- Add McFly replaces your default ctrl-r shell history search with an intelligent search engine that takes into account your working directory and the context of recently executed commands. McFly's suggestions are prioritized in real time with a small neural network.
- Add LeonidPilyugin/kawaii-oh-my-zsh theme
> Add cantino/mcfly

- README.md
- Add `Freed-Wu/zsh-cmmand-not-found` plugin
- Disambiguate `Tarrasch/zsh-command-not-found` plugin
> Add `Freed-Wu/zsh-command-not-found` plugin

- README.md
- Add `jedelson-pagerduty/pagerduty-omz-plugin` tab completions
- Add `florentinl/openstack-zsh-plugin` now that https://github.com/florentinl/openstack-zsh-plugin/issues/1 is closed
> 2022-09-10 updates

- README.md
Add `zkuzmic/which-jspm` now that https://github.com/zkuzmic/which-jspm/issues/2 is closed
Closes https://github.com/zkuzmic/which-jspm/issues/2
> Add `zkuzmic/which-jspm`

- README.md
- Add `zrut747/alp` now that https://github.com/zrut747/alp/issues/1 is closed
> Add `zrut747/alp`

- README.md
- Add `masonc15/wsl-notify-zsh` plugin, closes https://github.com/masonc15/wsl-notify-zsh/issues/1
- Add `dk949/searocket` theme now that https://github.com/dk949/searocket/issues/1 is closed
- Remove 404 `jvzaniolo/zsh-backcountry`
> Add `masonc15/wsl-notify-zsh` plugin

- README.md
Add `z-shell/zsh-fancy-completions`
> Add `z-shell/zsh-fancy-completions`

- README.md
https://github.com/TrooperT/Troopert-theme/issues/1 is closed, add `TrooperT/Troopert-theme`
> Add `TrooperT/Troopert-theme`

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- Add `keyaedisa/Valuca` (ducula variant) theme
- [x Add/remove/update a link to a theme
> Add `keyaedisa/Valuca` theme

- README.md
- Add `gsalami00/softblobby` theme, closes https://github.com/gsalami00/softblobby/issues/1 
- Add `gnsfujiwara/gnsprompt` theme
> Add `gsalami00/softblobby` theme

- README.md
Add `tom-power/fzf-tab-widgets`, closes https://github.com/tom-power/fzf-tab-widgets/issues/1
> Add `tom-power/fzf-tab-widgets`

- README.md
- Add `wintermi/zsh-lsd` plugin that overrides `tree` and `ls` with `lsd`.
- `zshmux` is 404, remove
> Add `wintermi/zsh-lsd` plugin

- README.md
https://github.com/fe80/fe80.zsh-theme/issues/1 is closed, add `fe80/fe80.zsh-theme`
> Add `fe80/fe80.zsh-theme`

- README.md
- Add `Daivasmara/daivasmara.zsh-theme`
> Add `Daivasmara/daivasmara.zsh-theme`

- README.md
Add `paxcoder/zsh-toolbox/`. Closes https://github.com/paxcoder/zsh-toolbox/issues/2
> Add `paxcoder/zsh-toolbox/`

- README.md
> Add `bwpge/zcmder` theme

- LICENSE
- README.md
- Add `chrishrb/zsh-kubectl` tab completion plugin.
- `gabrielecanepa/zsh-custom` is 404, remove its `squanchy` theme
> 2023-01-29

- README.md
- Add `baliestri/git-multiuser.plugin.zsh` plugin
> Add `baliestri/git-multiuser.plugin.zsh`

- README.md
- Add `f1redr4g0n/river_dreams` theme
- Add `alpaca-honke/prowpt` theme
- Update `robobenklein/zinc` theme entry
- Add `olrtg/zsh-fvm` tab completions
> 2023-02-07 updates

- README.md
- `f1redr4g0n` no longer has a GitHub account, so `f1redr4g0n/river_dreams` is 404, remove.
> Remove `f1redr4g0n/river_dreams`

- README.md
Add `cmuench/zsh-magento-cloud` completions
> Add `cmuench/zsh-magento-cloud`

- README.md
Add `mbergo/oh-plugin` utility for adding custom plugins to an oh-my-zsh instance.
> Add `mbergo/oh-plugin`

- README.md
- Add `2KAbhishek/starship2k` prompt. Based on starship
> Add `2KAbhishek/starship2k` theme

- README.md
- https://github.com/skippyr/river_dreams/issues/1 is closed, add `skippyr/river_dreams` theme
- https://github.com/NonLogicalDev/shell.async-goprompt/issues/1 is closed, add `goprompt` theme
> 2023-02-21 updates

- .github/PULL_REQUEST_TEMPLATE.md
- .github/dependabot.yml
- README.md
- Add dependabot configuration to keep our GH actions up to date
- Add `Mboukhal/hoMyZsh_theme`. Closes https://github.com/Mboukhal/hoMyZsh_theme/issues/1
- Add `SleepyBag/zsh-confer` plugin now that https://github.com/SleepyBag/zsh-confer/issues/1 is closed
- Add `trabdlkarim/parrot-zsh-theme`
> 2023-03-01 updates

- README.md
- Add `clamy54/kali-like-zsh-theme` theme
- Add `Madasish/madas-zsh-theme` theme now that https://github.com/Madasish/madas-zsh-theme/issues/1 is closed.
> 2023-03-15 updates

- README.md
[fzf-dir-navigator](https://github.com/KulkarniKaustubh/fzf-dir-navigator) - This is a cool and user-friendly directory navigation plugin for `zsh` using `fzf`.
> Add `KulkarniKaustubh/fzf-dir-navigator` plugin

- README.md
- Fix broken entry for `chrishrb/zsh-kubectl`.
> Update `chrishrb/zsh-kubectl` entry

- README.md
https://github.com/luislve17/calma/issues/1 is closed, add `luislve17/calma` theme
> Add `luislve17/calma` theme

- README.md
`zsh-ssh-quickconnect` is simple utility function that makes it fast and easy to SSH into a target host by selecting from a list of all hosts from `.ssh/config` file & `known_hosts`.
> Add `breda/zsh-ssh-quickconnect`

- README.md
- Update links that were showing `302` in the awesomebot GitHub action summary to point to their updated location directly
- Buidler.dev has a bad SSL cert, remove direct link
- Update jquery link
- Remove ZSH gems link, server is 500 for everything
- Remove explicit `/README.md` portions of links - GitHub automatically uses the repository's readme if you use a bare repository link
> Link cleanups

- README.md
- Add `l-umaca/omz-fluxcd-plugin` tab completion now that https://github.com/l-umaca/omz-fluxcd-plugin/issues/1 is closed.
- Add `Idan1993/zsh-htb-theme` theme now that https://github.com/Idan1993/zsh-htb-theme/issues/1 is closed
- Add `casonadams/bitwarden-cli` plugin. Closes https://github.com/unixorn/awesome-zsh-plugins/issues/1727
- Remove `zshzoo/copier` plugin, it's gone 404
> 2023-05-26 updates

- README.md
The original [fast-alias-tips](https://github.com/sei40kr/zsh-fast-alias-tips) is not active since 2020. I've forked it and implemented some features requests, and merged opened PRs.
> Replace zsh-fast-alias-tips with its fork

- README.md
Some time ago I created a Zsh plugin to install iterm2 utilities. Now the author of iTerm2 moved those utilities and shell integration to a dedicated repository, naturally making my plugin not needed anymore.
> Add iterm2-shell-integration

- README.md
[zsh-watch](https://github.com/Thearas/zsh-watch) is a simple `watch` wrapper for zsh that supports alias and completion.
Just `watch <command> <args>` (press `<Tab>` to complete):
```bash
watch kubectl get pod -n kube-system
watch kgpn kube-system
watch -c -n1 -d -t kgp
```
> Add `zsh-watch` plugin

- README.md
- Add `https://github.com/ablil/less-noise` - closes https://github.com/ablil/less-noise/issues/1
> Add `ablil/less-noise` theme

- README.md
- Add `d-exclaimation/vscode-dark-modern.zsh-theme` now that https://github.com/d-exclaimation/vscode-dark-modern.zsh-theme/issues/1 is closed.
- https://github.com/thegodheehee/hijack-zsh/issues/2 is closed, add `thegodheehee/hijack-zsh` theme
> 2023-06-29 updates

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/awesomebot.yml
- README.md
- Update `awesomebot` configuration
- Add `cmuench/zsh-miniconda` tab completion
- Update PR template
- Add `joknarf/nerdps1` theme. Closes https://github.com/joknarf/nerdps1/issues/1
> 2023 -07-23 updates

- README.md
> Add `Saka7/laconic` theme

- .github/workflows/pre-commit.yml
- README.md
- Add `skippyr/lildragon` theme
- Add `heapbytes/heapbytes-zsh` theme. Closes https://github.com/heapbytes/heapbytes-zsh/issues/2
- The ecortinas user is 404, remove `ecortinas/zsh-rbenv` plugin
- Update `kusamaxi/chaos-zsh` entry now that https://github.com/kusamaxi/chaos-zsh/issues/1 is closed
- `doctormemes/p10k-promptconfig` is 404, remove
> 2023-08-10 updates

- README.md
Add `A-delta/zsh-airpods-battery` plugin, now that https://github.com/A-delta/zsh-airpods-battery/issues/1 is closed
> Add `A-delta/zsh-airpods-battery` plugin

- README.md
Add `jotasixto/purge-history-secrets` plugin
> Add `jotasixto/purge-history-secrets`

- README.md
- Add `ethan605/fzfsh` plugin with fzf plugins for `chezmoi`, `docker`, `git`, `kubectl` and `pass`.
- Add `aoyama-val/zsh-incsearch` plugin
> 2023-10-05 updates

- README.md
- Add `GeoLMg/apt-zsh-plugin` plugin
- Update description for `jayree/sfdx-autocomplete-plugin` to include link to Salesforce's sfdx
- Add `fielding/zsh-brew-switcher` plugin
> 2023-10-06 updates

- README.md
- Add `bostonaholic/ngrok.plugin.zsh` completion.
- https://github.com/xiaoshihou514/skiff/issues/1 is closed, add `xiaoshihou514/skiff` theme
- https://github.com/easytocloud/oh-my-easytocloud/issues/1 is closed, update `easytocloud/oh-my-easytocloud` entry.
- Add `tapyu/zsh-alias-snippet-toolkit` plugin.
- Add `Doc0x1/zautoload` plugin.
> 2023-10-11 updates

- README.md
- Update `baliestri/git-profiles` entry to be more consistent with the rest of the list.
- https://github.com/Zacharyjlo/git-recent-branches/issues/1 is closed, add `Zacharyjlo/git-recent-branches`.
> 2023-10-13 updates

- README.md
- Update `aoyama-val/zsh-incsearch` entry. Closes https://github.com/unixorn/awesome-zsh-plugins/issues/1788.
- Adds `admons/hebzsh` plugin - If a command is not found as typed in Hebrew, translates the command as if it was typed on a keyboard with a US English layout and tries again.
- `xVanjaZ/xVanjaZ-ZSH-Theme` is 404, remove.
> 2023-10-14 updates

- README.md
- Add `vitobotta/zsh-history-sync`. Closes https://github.com/vitobotta/zsh-history-sync/issues/1
- Re-sort entries
> Add `vitobotta/zsh-history-sync`

- README.md
https://github.com/chmouel/zsh-select-with-lf/issues/1 is closed, add `chmouel/zsh-select-with-lf` plugin
> Add `chmouel/zsh-select-with-lf` plugin

- README.md
- https://github.com/wdjcodes/magpie/issues/1 is closed, add `wdjcodes/magpie`
- https://github.com/tariqdomi/ohmyzsh-domixgit/issues/1 and https://github.com/tariqdomi/ohmyzsh-domixgit/issues/2 are closed, add `alexgervais/telepresence-ps1` plugin.
> 2023-11-01 updates

- README.md
- Update `wdjcodes/magpie` theme entry
- Add `mellypop/princess` theme
> 2023-11-03 updates

- README.md
- Add `espeon/paramour/` theme now that https://github.com/espeon/paramour/issues/1 is closed
- Update url in `devopstales/kubecolor-zsh` plugin to `devopstales/kubecolor-zsh`
> 2023-12-07 updates

- README.md
- Add `Sam-programs/zsh-calc` plugin
- Add `yhlooo/zsh-kubeconfig-mgr` plugin
- Add `harvey103565/git-multi-sshacc-asst` plugin
- Add `Doc0x1/Aircrack-Zsh-Completions` tab completions.
> 2023-12-10 updates

- README.md
- Update `Pilaton/OhMyZsh-full-autoupdate` plugin entry to include a link to omz.
- Add `gabriel2m/gabriel2m-oh-my-zsh-theme` theme
- Add `Petrushevsky-A/Lacerate-zsh-theme`, closes https://github.com/Petrushevsky-A/Lacerate-zsh-theme/issues/1
- Add `Bigyls/Bigyls-zsh-theme` theme
> 2023-12-15 updates

- README.md
I"m not sure when the original autoenv links were added, but the [main autoenv project](https://github.com/hyperupcall/autoenv) now supports ZSH. This replaces the older repository link, which hasn't been updated in years.
> Replace outdated autoenv link

- README.md
- Add `Taimoor-Tariq/zsh-supabase` tab completions
- Add `wintermi/zsh-gcloud` plugin
- Add `umlx5h/zsh-manpage-completion-generator` utility
- Add `antznin/zsh-bitbake` tab completion
> 2024-01-13 updates

- README.md
- Add `nbitmage/clarity.zsh` theme
- Add `ronitkrshah/frontcube` theme. Closes https://github.com/ronitkrshah/frontcube/issues/1
- Remove stackexchange.com link, it 403s when awesomebot tries to check the link. Works in browsers, just not from automation.
- `pentago/dzhi-zsh-theme` theme is 404, remove
> 2024-02-16 updates

- README.md
`Gary-Ash/SnazzyPrompt` theme is 404, remove
> Leap Day! Remove `Gary-Ash/SnazzyPrompt`

- README.md
added braundo theme to list of themes
[braundo](https://github.com/Braundo/braundo-zsh-theme) - Straightforward theme with username, current directory, `git` status, and timestamp.
> added braundo theme

- README.md
- Add `bahmanworld/bahman-zsh-theme` theme
- Add `codingtho/tho-zsh-theme` theme
- Add `okhiroyuki/zsh-git-switch-branch-skim` plugin, closes https://github.com/okhiroyuki/zsh-git-switch-branch-skim/issues/1
- Add `okhiroyuki/zsh-select-history-skim` plugin, closes https://github.com/okhiroyuki/zsh-select-history-skim/issues/1
- Add zsh-mgr framework now that https://github.com/amt911/zsh-mgr/issues/21 is closed
- `tinted-theming/base16-shell` is now `tinted-theming/tinted-shell`, update plugin entry.
> 2024-03-20 update

- README.md
- Add `NimaNikfar/ninik-zsh-theme` now that https://github.com/NimaNikfar/ninik-zsh-theme/issues/1 is closed.
- Add `raisedadead/zsh-awsssh` plugin
- Add `bateman/fbi-zsh-theme` theme
> 2024-03-24 updates

- README.md
This PR addresses two plugins:
- [jaeheonji/zsh-zellij-plugin](https://github.com/jaeheonji/zsh-zellij-plugin)
- This has been archived by the original author
- Added a notice of deprecation in the same format as that added in #1720 ([ref](https://github.com/unixorn/awesome-zsh-plugins/pull/1720/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R1088))
- Also added notice of native zellij replacement, which is included in the original project's archive notice
- [tranzystorekk/zellij-zsh](https://github.com/tranzystorekk/zellij-zsh)
- The plugin author has archived the repository and moved it to Codeberg (see readme)
- Updated plugin link to reference [new Codeberg repository](https://codeberg.org/tranzystorekk/zellij.zsh)
> Fix `jaeheonji/zsh-zellijplugin`, `tranzystorek-io/zellij-zsh`

- README.md
- `skippyr/river_dreams` has moved to `skippyr/river-dreams`, update link accordingly
- Update `sinetoami/antibody-completion` entry
- Add `giovannilupi/dirbrowse` plugin. Closes https://github.com/giovannilupi/dirbrowse/issues/1
- Add link to `i-love-coffee-i-love-tea/audogombleed.sh` tool for generating tab completion scripts now that https://github.com/i-love-coffee-i-love-tea/audogombleed.sh/issues/1 is closed.
- Add `raisedadead/zsh-touchplus` plugin
> 2024-04-06 updates

- README.md
Remove `zi` framework. See https://recurse.social/@dylnuge/112224580867240812 thread for why.
> Remove zi framework

- README.md
- Add `jashezan/lagnoda` theme
> Add `jashezan/lagnoda`

- README.md
- Remove `tybritten/pks-zsh-autocomplete-plugin`, it is 404.
- Add link to `kyletimmermans/shell-color-prompt-tool` prompt creator tool.
> 2024-04-11 updates

- README.md
- `zsh-tmux-multisession` is 404, remove
- https://github.com/tulioribeiro/zsh-tcr-theme/issues/1 is closed, add `tulioribeiro/zsh-tcr-theme`
- Add `anasouardini/portal` plugin. Closes https://github.com/anasouardini/portal/issues/2
> 2024-04-13 updates

- README.md
- Add `Skylor-Tang/auto-venv` plugin
- Add `NiziL/ranger.plugin.zsh` plugin
- Add `lucasheartcliff/venv` plugin
- Add `utox39/oh-my-update` plugin
- Update `anasouardini/portal` plugin entry
> 2024-04-27 updates

- README.md
- https://github.com/jnooree/zoxide-zsh-completion/issues/1 is closed, add `jnooree/zoxide-zsh-completion`
- https://github.com/fruitydog/kiwi.zsh-theme/issues/1 is closed, add `fruitydog/kiwi.zsh-theme`
- https://github.com/GNUWood/firmine/issues/1 is closed, add `GNUWood/firmine` theme.
> 2024-05-05 updates

- README.md
- Add `troykelly/oh-my-zsh-brave` plugin
- Add `Butakus/ros2-env` plugin
- Add `plutowang/zsh-ollama-command` plugin
- Add `fffelix-huang/candy-fantasy` theme
- Add `marknefedov/oh-my-zsh-tofu` tab completion loader
- Add `brokentoaster/zsh-explainshell` plugin
> Mothers' Day 2024 updates

- README.md
- https://github.com/AyoubMounim/zsh-git-status/issues/1 is closed, add `AyoubMounim/zsh-git-status`
- Add `meshkinyar/berghain.zsh-theme`. Closes https://github.com/meshkinyar/berghain.zsh-theme/issues/1
> 2024-05-18 updates

- README.md
This is no longer maintained, and this functionality exists directly in zoxide now.
Removes fzf-z plugin link.
> Remove fzf-z

- README.md
- Add `p1r473/tab-title` plugin. Closes https://github.com/unixorn/awesome-zsh-plugins/issues/1863
- Typo fix
- Add `jrocha-dev/ohmyzsh-plugin-jrgit` plugin
> 2024-05-25 updates

- README.md
- Add `hsrzq/PluginForTailscale` tab completion
- Add `wardhanisukoco/zsh-plugin-conda` now that https://github.com/wardhanisukoco/zsh-plugin-conda/issues/1 is closed
> 2024-06-01 updates

- README.md
- Add `JannoTjarks/catppuccin-zsh`. Closes https://github.com/JannoTjarks/catppuccin-zsh/issues/1
- Add `idaMakelaWork/refined-flower` now that https://github.com/idaMakelaWork/refined-flower/issues/1 is closed
- Add `FalconLee1011/mint-zsh-theme/`, closes https://github.com/FalconLee1011/mint-zsh-theme/issues/1
> 2024-06-15 updates

- README.md
`zenv` is a shell utility designed to create isolated working environments. It allows you to run arbitrary commands and set environment variables to configure your workspace. 
Similar to the purpose of direnv, `zenv` uses a new shell instance providing cleaner workspace isolation.
> Add `janitha/zenv` to the Plugin list.

- README.md
Per https://github.com/unixorn/awesome-zsh-plugins/actions/runs/9944246907 `babasbot/auto-fortune-cowsay-zsh` is 404, remove
> `babasbot/auto-fortune-cowsay-zsh` is 404

- README.md
Update mill-build link to cope with site layout change
> Update mill-build link

- README.md
- Add `hrmeetsingh/sorin-modified-dark` theme
- `git-girl/pseudo-projectile-plugin` is 404, remove
- `aifrim/aifrim.zsh-theme` is 404, remove
> Add `hrmeetsingh/sorin-modified-dark`

- README.md
- Add `mass8326/zsh-chezmoi` completion. Closes [1898](https://github.com/unixorn/awesome-zsh-plugins/issues/1898)
- Add `swomf/netmask-zsh-theme` theme
> 2024-08-17 updates

- README.md
- Add `gh-source` framework
- Add `ZitherPeng/oh-my-zsh-luckycoding-theme`
- Add `ZelongGuo/steeef theme
- Add `donbuehl/zsh-unraid` plugin
- Add `toku-sa-n/zsh-dot-up` plugin
> 2024-09-13 updates

- README.md
- https://github.com/Readf0x/integral-prompt/issues/5 is closed, add `Readf0x/integral-prompt`
- `mountaineerbr/shellChatGPT` is 404, remove
- Re https://github.com/unixorn/awesome-zsh-plugins/discussions/1908, add https://github.com/stentibbing/abzt-zsh-theme
> 2024-09-14 updates

- README.md
- https://github.com/jlduran/git-arc-oh-my-zsh-plugin/issues/1 is closed, add `jlduran/git-arc-oh-my-zsh-plugin/`
> Add `jlduran/git-arc-oh-my-zsh-plugin/`

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- Add `bilelmoussaoui/flatpak-zsh-completion` tab completion.
- Add `kislyuk/argcomplete` completion generator
- Add `crazy-complete/crazy-complete` completion generator
- Add `ocadaruma/zsh-gcloud-prompt` plugin
> 2024-10-12 updates

- README.md
- `pbar1/zsh-terraform` is 404, remove
- https://github.com/iloveitaly/zsh-ai-completions/issues/1 is closed, add
`iloveitaly/zsh-ai-completions`. Closes https://github.com/unixorn/awesome-zsh-plugins/issues/1920
- Add `chougousui/complete-lastf` tab completion
> 2024-10-24 updates

- README.md
When zpy was added to this list, pip-tools was the sole backend. These days there's an additional, preferred backend: uv.
This change includes the new uv backend in zpy's description, instead of only the non-preferred pip-tools backend.
> Update zpy description to reflect new backend (uv)

- README.md
- Add `Robinx0/catpuccin-kali-theme.zsh-theme` now that https://github.com/Robinx0/catpuccin-kali-theme.zsh-theme/issues/1 is closed
- `claymorwan/Flatpak-zsh-plugin` is 404, remove
> 2024-11-09 updates

- README.md
Add `felipec/zsh-prompt-felipec` now that https://github.com/felipec/zsh-prompt-felipec/issues/1 is closed
> Add `felipec/zsh-prompt-felipec`

- README.md
- Add `snovra-dev/zsh-autovenv` plugin
- Disambiguate `linnnus/autovenv` plugin entry
> Add `snovra-dev/zsh-autovenv`

- README.md
- Add `lipov3cz3k/zsh-uv` tab completion
> Add `lipov3cz3k/zsh-uv`

- README.md
- Add `miche1e/do-you-even-nix` theme
- Add `zchee/deoplete-zsh` completion
> 2024-11-30 updates

- README.md
- `xxninjabunnyxx`'s github account is 404, remove `xxninjabunnyxx/hug-zsh`
- `codingtho/tho-zsh-theme` is 404, remove
- Add `dimgatz98/Baddcafe_zsh_theme` theme
- Add `moonbloom-theme/zsh` theme
> 2024-12-03 updates

- README.md
- Remove duplicate `crazy-complete` entry
- Add `suonto/awsp-zsh-plugin` plugin
- the.exa.website is offline, replace with link to https://github.com/ogham/exa
> 2024-12-04 updates

- README.md
- Add missing badges to `joknarf/thefly` framework entry
- Remove redundant theme install instructions
> Add missing badges to `joknarf/thefly`

- README.md
- Update `zchee/deoplete-zsh` ZSH completion entry
> 2024-12-08 updates

- README.md
The zsh-ai github account is 404, remove zsh.ai framework
> Remove zsh.ai

- README.md
- Add `cabovianco/cabovianco-zsh-theme` theme
> Add `cabovianco/cabovianco-zsh-theme`

- README.md
- Add `BadRat-in/zsh-modern-theme` theme
- Add `ruslan-korneev/pgconnect-zsh` now that https://github.com/ruslan-korneev/pgconnect-zsh/issues/1 is closed
> 2024-12-27 updates

- README.md
Add `alberti42/tmux-ssh-syncing` plugin
> Add `alberti42/tmux-ssh-syncing`

- README.md
- Add `Xatra1/burn` now that https://github.com/Xatra1/burn/issues/1 is closed
- https://github.com/targendaz2/taskfile/issues/1 is closed, add `targendaz2/taskfile`
> 2024 NYE updates

- README.md
`mobiuscog/zsh-auto-cenv` is 404, remove.
> Remove `mobiuscog/zsh-auto-cenv`

- README.md
- https://github.com/mikkurogue/archmocha/issues/1 is closed, add `mikkurogue/archmocha`
- Add `do-i-need-a-username/ensure-kube-context` plugin
> 2025-01-05 updates

- README.md
- Formatting cleanup in `Freed-Wu/zsh-command-not-found` entry
- https://github.com/rufevean/vivi/issues/1 is closed, add `rufevean/vivi` plugin
- https://github.com/bGZo/life-progress/issues/1 is closed, add `bGZo/life-progress` plugin
- Add `danieldietrich/gitprompt.sh` theme
- Add `chr15m/aish` plugin
> 2025-01-10 updates

- README.md
- `valek/zsh-hadoop-plugin` is 404, remove
- Add `marceloclp/zsh-brew-install` plugin
- Update `Goldeneye128/goldenprompt` link - it has moved to `Goldeneye128/golden-prompt`
> 2025-01-12 updates

- README.md
- Update `shihyuho/zsh-jenv-lazy` plugin entry - jenv.be doesn't resolve
- Add `matthiasha/zsh-uv-env` plugin
> 2025-01-15 updates

- README.md
- `ronitkrshah/frontcube` is 404, remove
- https://github.com/Teajey/teajey-zsh-theme/issues/1 is closed, add `Teajey/teajey-zsh-theme`
- https://github.com/Aggrathon/torim/issues/1 is closed, add `Aggrathon/torim` theme
- https://github.com/avano/vanan.zsh-theme/issues/1 is closed, add `avano/vanan.zsh-theme`
- Add `delorenj/nerd-font-check` plugin
- Add `andrii-rieznik/rie-zsh-theme` theme
> 2025-01-31 updates

- README.md
- https://github.com/thestuckster/jumper/issues/1 is closed, add `thestuckster/jumper` plugin
- https://github.com/xooooooooox/zsh-proxy/issues/1 is closed, add `xooooooooox/zsh-proxy` plugin
- Add `Ohh-Raven/ohh_IP` theme. Closes https://github.com/Ohh-Raven/ohh_IP/issues/1
- Add `devopsguy/ohelm-zsh-theme`. Closes https://github.com/devopsguy/ohelm-zsh-theme/issues/1
- Add `Xeferis/cleanzip` plugin. Closes https://github.com/Xeferis/cleanzip/issues/1
- Add `hmgle/aider-zsh-complete` tab completion
> 2025-02-08 updates

- README.md
- Add `r3-fresh/r3-fresh-zsh-theme` theme
- Add `olets/zsh-transient-prompt` theme
- Add `tomorrowbye/yellow-peach-theme` now that https://github.com/tomorrowbye/yellow-peach-theme/issues/2 is closed
- Add `mikhaben/pickaxe-zsh-theme` theme
- Add `cfunkz/zsh-raspberry-temp-plugin` plugin for rPi
- Sort cleanups
> 2025 Valentine's Day updates

- README.md
- Update `Spectere/spectere-omz-theme` entry
- `xylous/hydrogen` is 404, remove
- `Insert-Creative-Name-Here` deleted their Github account, remove `Insert-Creative-Name-Here/gitstatus.zsh`
> 2025-02-16

- README.md
- Add `alimranahmed/zsh-imranic-themes` now that https://github.com/alimranahmed/zsh-imranic-themes/issues/2 is closed
- Add `michaelsousajr/zshcp` plugin
- Add `jaacob/whisp` plugin
> 2025-03-01 updates

- README.md
- `manuelcattelan/promptly` is 404, remove
- Add `murku/omz_poetry_plugin` plugin
- Update link to @anki-code's bar theme
> 2025-03-20 updates

- README.md
- Add `ppcamp/zsh-pet` plugin
- Clean up wording in `shosca/zsh-pew` plugin entry
- Add `KernelDiego/kerneldiego-zsh-theme` theme
- https://github.com/alex-crouch/zsh-diskfree/issues/1 is closed, add `alex-crouch/zsh-diskfree` plugin
- https://github.com/pickle-slime/kittyback/issues/1 is closed, add `pickle-slime/kittyback`
> 2025-04-11 updates

- README.md
- Add `logout-user` now that https://github.com/pressdarling/logout-user/issues/1 is closed
- https://github.com/afaq1337/afaq.zsh-theme/issues/1 is closed, add `afaq.zsh-theme`
- Replace update nerd font references with hyperlinks
> 2025-06-02 updates

- README.md
- `ArmandPhilippot/coldark-zsh-theme` is 404, remove
- Reformat `chaosimpact/sops-crypt` entry for consistency
> 2025-06-27 updates

- README.md
- Add `aranel616/rtm-reminder-zsh`
- Add `ars2062/serenity-zsh-theme` theme
- Add `tourcoder/larn.zsh-theme`.  Closes https://github.com/tourcoder/larn.zsh-theme/issues/1
- Add `cnlee1702/zsh-system-update` plugin
> 2025-07-07 updates

- README.md
- `pskfyi/zsh-theme` is 404, remove
- `git-girl/git-check` is 404, remove
> Remove 404s

- README.md
- Add `saeed0xf/mocha-fusion` theme
> Add `saeed0xf/mocha-fusion`

- README.md
The plugin no longer works, as the data source it uses is no longer on github
> Remove git-ignore plugin

- README.md
- Add `ivomac/zsh-fzf-nav` plugin now that https://github.com/ivomac/zsh-fzf-nav/issues/1 is closed.
- Add `scaryrawr/fzf.zsh` now that https://github.com/scaryrawr/fzf.zsh/issues/1 is closed
> Add more `fzf` plugins
