unixorn/awesome-zsh-plugins

README.md
You already have one of my plugins on your list, surprisingly.  Have a couple more.
=> add snippets and hooks plugins

README.md
Add my prompt to the themes.  It's a great prompt with a lot of info that shows up when you want it (eg. number of jobs, but only when you have some).
=> add megaprompt

README.md
=> Very little typo

README.md
.. They were missing in the readme ;)
=> Added "Awesome Terminal Fonts"

README.md
https://github.com/caarlos0/antibody
=> added antibody

README.md
Plugin for supporting `npm run` autocompletions.
=> Add npm-run.plugin.zsh

README.md
I made this plugin to add a default configuration of cdr in one line instead of several.
=> add cdr plugin

README.md
In the spirit of vim-sensible, I made this plugin of sensible default options.
=> add saneopt

README.md
Thanks for putting it *almost* in the right place.
And thanks for making this great list.  My zsh is much better for it.
=> fix alphabetical order

README.md
Just added a missing parenthesis.
=> Fix molokai-powerline-zsh stars icon

README.md
=> Add b4b4r07/emoji-cli

README.md
Fixes #56 
Signed-off-by: Wilhelm Erasmus <iam@wilhelm.co.za>
=> Some plugins were listed as themes.

README.md
=> Add b4b4r07/zplug

README.md
=> Add Eriner/zim

README.md
Doing this as a PR to check the travis configuration.
=> Add gprune plugin

README.md
https://github.com/psprint/zsh-cmd-architect – a plugin, supports Zgen, Antigen, etc.
=> New plugin: Zsh Command Architect (zsh-cmd-architect)

README.md
Also TOC is updated by `doctoc README.md`.
=> Add zplug instructions

README.md
Hello
A new plugin: organized shortcuts for various command line editing operations, plus new operations (e.g. incremental history word completion)
=> New plugin: Zsh Editing Workbench (zsh-editing-workbench)

README.md
New framework with tracking what plugin does, ability to unload it, and selective administration of plugin's completions, and all this with clean, basically ununsed $FPATH. I've tested 38 plugins with it and will test more:
https://github.com/psprint/zplugin/blob/master/doc/tested.txt
=> New framework: Zplugin

README.md
=> Zplugin: update of description (parts about variables and compilation)

README.md
Plugin that provides zsnapshot command which dumps current ZSH state into a file, for restoration by sourcing the file
=> New plugin - zsnapshot

README.md
=> purge star badges from readme

README.md
https://github.com/voronkovich/phpunit.plugin.zsh
=> Add plugin for phpunit

README.md
Hello
Two new plugins, Ztrace and history-search-multi-word
Best regards,
Sebastian Gniazdowski
=> 2 new plugins: Ztrace and history-search-multi-word

README.md
Hello,
a selection list that uses pure Zsh capabilities to achieve what e.g. selecta or fzf do.
=> New plugin: zsh-select

README.md
Hello,
terminal screen saver framework, plus some screen savers equipped, video: https://asciinema.org/a/47242
Best regards,
Sebastian Gniazdowski
=> New plugin: zsh-morpho

README.md
`npm run` completion is now included with `npm` https://github.com/npm/npm/issues/8030
=> Remove npm-run.plugin.zsh

README.md
=> Add lukechilds/zsh-better-npm-completion

README.md
=> Add zsh-nvm

README.md
The trailing / suddenly broke the article link, fix.
=> Fix link error discovered by travis

README.md
I wrote a very simple zsh plugin that populates numerous ascii art emojis as variables in your environment. 
I initially used to store these myself in my `.zshrc` file, but some friends expressed interest in having something like this available to them. So I decided to make it into a simple plugin ᕙ(⇀‸↼‶)ᕗ
=> Add zsh-emojis to plugin list

README.md
=> Add autojump for ZSH info

README.md
Owner changed from b4b4r07 to the zplug organization.
=> Update zplug links

README.md
* Add **ssh-agent** plugin
* Add **zsh-abbrev-alias** plugin
=> Add plugins

README.md
Hi there! I just want to add my theme. Thanks
=> [ADD] zsh-theme: ozono

README.md
* Add dragon theme
* Add ykmam theme
=> Add dragon and ykmam themes

README.md
=> add listbox, project and ssh-connect

README.md
Fix sort errors that have crept in.
=> Fix sorting

README.md
Reverts unixorn/awesome-zsh-plugins#184
=> Revert "Add thirsty plugin"

README.md
> A curated list of Terminal frameworks, plugins & resources for CLI lovers.
GitHub Repo: [here](https://github.com/k4m4/terminals-are-sexy/)
**Project Site: [here](http://terminalsare.sexy/)**
=> Add Terminals Are Sexy

README.md
* Add bilibili theme
* spelljammer theme went 404, removing
=> Add bilibili theme

README.md
Changed user `psprint` to `zdharma` in 2 places. Extended HSMW description. Added 2 plugins Zconvey, ZUI
=> Update on psprint's plugins; new plugins: Zconvey, ZUI

README.md
It not exactly framework, but I use it for manage 4 different operating systems with different zsh versions and plugins.
=> Add ansible-role-zsh

README.md
Display feedback of terminal in the 🍏 Touchbar
=> add `zsh-iterm-touchbar`

README.md
Also fix entry for bracketed paste
=> Replace http with https in links where possible

README.md
https://github.com/voronkovich/phpcs.plugin.zsh
=> Add plugin for phpcs

README.md
=> Add kubectl-zsh-plugin

README.md
Add link to the **zsh-google-lucky** plugin
=> Add zsh-google-lucky

README.md
=> Add zgdbm plugin

README.md
* Added ruby-switch plugin.
* Cleaned up section sorting
* Made newman entry consistent with other entries.
=> Add ruby-switch plugin

README.md
=> Add fishy theme

README.md
=> Add bumblebee plugin

README.md
=> Add keloran theme

README.md
Redis server can be tied with all Zsh datatypes. Updating Zsh variable automatically updates redis server.
Add single plugin, zdharma/zredis
=> Add zredis database plugin

README.md
=> Add asciigit theme, clean up themes section

README.md
=> Add termuxer theme

README.md
=> Add tq-zsh-theme

README.md
=> Add sobole theme

README.md
Add [zsh-dircycle](https://github.com/michaelxmcbride/zsh-dircycle) plugin
=> Add zsh-dircycle

README.md
Add a link to a zsh plugin that reminds you to use aliases you have defined.
=> Add zsh-you-should-use

README.md
Add link to [powerline-shell](https://github.com/banga/powerline-shell) theme.
=> Add powerline-shell

README.md
=> Add ubuntu16 aliases plugin

README.md
Added [zit](https://github.com/m45t3r/zit) plugin manager.
=> Add zit plugin manager

README.md
Add [gimme](https://github.com/folixg/gimme-ohmyzsh-plugin) plugin
=> Add gimme go manager plugin

README.md
=> Add clean-project to plugins list

README.md
=> Add git-annex-completion

README.md
=> Add absolute theme

README.md
Add [kinda-fishy-theme](https://github.com/folixg/kinda-fishy-theme)
=> Add kinda-fishy-theme

README.md
Update the entry for sepshell.
=> Update sepshell entry

README.md
Add [proxy-plugin](https://github.com/escalate/oh-my-zsh-proxy-plugin)
=> Add proxy-plugin

README.md
Add [starboy](https://github.com/zuck007/Starboy) zsh theme
=> Add starboy theme

README.md
Add [astro](https://github.com/iplaces/astro-zsh-theme/blob/master/README.md) theme
=> Add astro theme

README.md
Add link to [docker-machine](https://github.com/asuran/zsh-docker-machine)
=> Add docker-machine plugin

README.md
update entry for [ripz](https://github.com/jedahan/ripz)
=> Update ripz entry

README.md
* Add [bronze](https://github.com/reujab/bronze) prompt
* Remove dead buccaneer link
=> Add bronze prompt.

README.md
Add [operator](https://github.com/nivv/operator-theme) theme.
=> Add operator theme

README.md
Add [plain](https://github.com/jimeh/plain.zsh-theme) theme
=> Add plain theme

README.md
=> Add jtool completion

README.md
Add [lambdav](https://github.com/vkaracic/lambdav-zsh-theme) theme
=> Add lambdav theme

README.md
Update [sobole](https://github.com/sobolevn/sobole-zsh-theme) theme's description
=> Update description for sobole theme

README.md
Add link to [refined](https://github.com/octarect/refined.zsh)
=> Add refined theme

README.md
Add [clarity](https://github.com/octarect/clarity.zsh) theme.
=> Add clarity theme

README.md
Update description for powerlevel9k
=> Update powerlevel9k description

README.md
Clean up a bunch of entries with missing periods or inconsistent ZSH capitalization.
=> Clean up inconsistent line endings and ZSH captitalization

README.md
Standardize on ZSH in descriptions.
=> Standardize on ZSH instead of zsh or Zsh.

Contributing.md, PULL_REQUEST_TEMPLATE.md
Update the PR Template and Contributing guidelines for clarity.
=> Update PR Template and Contributing guidelines

README.md
Added [zedzsh](https://github.com/eendroroy/zed-zsh)
=> Add zed-zsh plugin

README.md
A simple zsh plugin for managing projects: https://github.com/voronkovich/project.plugin.zsh
=> Add project.plugin.zsh

README.md
Updated description of [powerzeesh](https://github.com/sevaho/Powerzeesh) theme
=> Update powerzeesh description

README.md
Add [materialshell](https://github.com/carloscuesta/materialshell) theme
=> Add materialshell

README.md
I added information about hanami zsh plugin to list
=> Add information about hanami zsh plugin

README.md
Add [rafiki](https://github.com/akabiru/rafiki-zsh) theme
=> Add rafiki theme

README.md
* Add [powerline-go](https://github.com/justjanne/powerline-go) theme
* Fix sorting in theme section
=> Add powerline-go theme

README.md
Add [himself](https://github.com/mwamodojnr/himself) theme
=> Add himself theme

.codeclimate.yml, PULL_REQUEST_TEMPLATE.md, README.md
Disable some of the markdown checks in code climate.
=> Configure code climate

README.md
Add [eggshausted](https://github.com/inutano/eggshausted) theme
=> Add eggshausted theme

README.md
Add [aphrodite](https://github.com/win0err/aphrodite-terminal-theme) theme.
=> Add aphrodite theme

README.md
Add [zpacker](https://github.com/happyslowly/zpacker) framework
=> Add zpacker framework

README.md
Add [diractions](https://github.com/AdrieanKhisbe/diractions) plugin
=> Add diraction plugin

README.md
Add [zsh-tmux-rename](https://github.com/sei40kr/zsh-tmux-rename) plugin
=> Add zsh-tmux-rename plugin

README.md
Add [vanan](https://github.com/avano/vanan-zsh-theme) theme
=> Add vanan theme

README.md
Add [kill-node](https://github.com/vmattos/kill-node) plugin
=> Add kill-node

README.md
Add [sublime](https://github.com/valentinocossar/sublime) plugin
=> Add sublime plugin

README.md
Add [bluehigh](https://github.com/abouthiroppy/bluehigh.zsh-theme) theme
=> Add bluehigh theme

README.md
Add [theraveler](https://github.com/azah/the-raveler) theme
=> Add theraveler theme

README.md
Add [vim-plugin](https://github.com/nviennot/zsh-vim-plugin) plugin
=> Add vim-plugin plugin

README.md
Add [zsh-plugin-cd-ssh](https://github.com/jeffwalter/zsh-plugin-cd-ssh) plugin
=> Add cd-ssh plugin

README.md
Add [randeme](https://github.com/ex-surreal/randeme) plugin
=> Add randeme theme switcher plugin

README.md
Add [zsh-vimto](https://github.com/laurenkt/zsh-vimto) plugin
=> Add zsh-vimto plugin

README.md
Add [zsh-dp-theme](https://github.com/davidparsson/zsh-dp-theme)
=> Add dp theme

README.md
Add [poor-programmer](https://github.com/vishaltelangre/poor-programmer.zsh-theme) theme
=> Add poor-programmer theme

README.md
Add link to [zsh-hadoop-plugin](https://github.com/valek/zsh-hadoop-plugin)
=> Add hadoop plugin

README.md
=> Add cd-reporoot

README.md
Add [aterminal](https://github.com/guiferpa/aterminal) theme
=> Add aterminal theme

README.md
Apple renamed OS X to macOS a while ago. Update references accordingly.
=> Update osx to mac os

README.md
Add [fzf-mpd](https://github.com/piotryordanov/fzf-mpd/) plugin.
=> Add fzf-mpd plugin

README.md
Add [atom-plugin](https://github.com/CorradoRossi/oh-my-zsh-atom-plugin)
=> Add atom-plugin

README.md
Add [zsh-pyenv-lazy](https://github.com/davidparsson/zsh-pyenv-lazy) plugin
=> Add pyenv-lazy plugin

README.md
Add [firebase-zsh](https://github.com/rmrs/firebase-zsh) plugin
=> Add firebase plugin

README.md
Add [paci](https://github.com/iloginow/zsh-paci) plugin
=> Add paci plugin

.travis.yml, PULL_REQUEST_TEMPLATE.md, README.md
* Add [zsh-escape-backtick](https://github.com/bezhermoso/zsh-escape-backtick) plugin
* Update PR template with naming guidelines
=> Add escape-backtick plugin

README.md
Add [lesaint-git](https://github.com/lesaint/lesaint-git) plugin
=> Add lesaint-git plugin

README.md
Add [youtube-dl](https://github.com/joow/youtube-dl) plugin
=> Add youtube-dl plugin

README.md
Added the msf and simpelserver-plugin
i added 2 plugins. msf(which helps in launching the metasploit handler's easily
=> add-msf&simpleserver-plugin

README.md
=> sort plugin section

README.md
Add [remolueoend](https://github.com/remolueoend/remolueoend.zsh-theme) theme
=> Add remoluoend

README.md
Add [zsh-abbr-path](https://github.com/felixgravila/zsh-abbr-path) plugin
=> Add zsh-abbr-path plugin

README.md
Add [seltzer](https://github.com/GrantSeltzer/seltzer.zsh-theme) theme
=> Add seltzer theme

README.md
Add [guri](https://github.com/victorfsf/guri) theme
=> Add guri theme

README.md
Add [birame](https://github.com/maniat1k/birame) theme
=> Add birame theme

README.md
Add [nmaxcom](https://github.com/nmaxcom/nmaxcom-zsh-theme) theme
=> Add nmaxcom

README.md
Add [nuqlezsh.zsh-theme](https://github.com/Nuqlear/nuqlezsh.zsh-theme) theme
=> Add nuqlzsh theme

README.md
'rummik' should be all lowercase (not really something that's known, so here's a PR :wink:)
=> Update README.md - replace 'Rummik' with 'rummik'

README.md
Add [simple-agnoster.zsh-theme](https://github.com/iwat/simple-agnoster.zsh-theme) theme
=> Add simple-agnoster theme

README.md
Add [llama.zsh-theme](https://github.com/PsychoLlama/llama.zsh-theme)
=> Add llama theme

README.md
Add [Parrot-OS-mod-zsh-theme](https://github.com/Sameera-Madushan-Perera/Parrot-OS-mod-zsh-theme)
=> Add parrot-os theme

README.md
Add [karu](https://github.com/zaari/karu) theme
=> Add karu theme

README.md
Add [pieni](https://github.com/zaari/pieni) theme
=> Add pleni theme

README.md
Add [dustmod](https://github.com/bmihaila/dustmod) theme
=> Add dustmod

README.md
* Clean up some plugin descriptions
* Add tmux hotlinks
=> text cleanups

README.md
Update yairshefi theme description
=> update yairshefi description

README.md
Add [fattyarrow](https://github.com/sohnryang/fattyarrow) theme
=> Add fattyarrow theme

README.md
Zplugin has been extended with many functionalities, 1000 commits passed, time to update the description.
=> Update Zplugin description

README.md
Add [dune-quotes](https://github.com/brokendisk/dune-quotes) plugin
=> Add dune-quotes plugin

README.md
Add [zsh-ing](https://github.com/rummik/zsh-ing) plugin
=> Add zsh-ing plugin

README.md
Add [lambda-gitster](https://github.com/ergenekonyigit/lambda-gitster) theme
=> Add lambda-gitster theme

README.md
Update link and description for geometry theme
=> Update link to geometry theme

README.md
Add [zsh-change-case](https://github.com/mtxr/zsh-change-case)
=> Add zsh-change-case plugin

README.md
Add [zsh-aws-vault](https://github.com/blimmer/zsh-aws-vault) plugin
=> Add aws-vault plugin

README.md
=> Add blokkzh theme

README.md
Add [milight-zsh](https://github.com/frodoslaw/milight-zsh) theme
=> Add milight theme

PULL_REQUEST_TEMPLATE.md
=> Update PR template checklist

README.md
Add [agnoster-plus](https://github.com/jiahut/agnoster-plus.zsh-theme) theme
=> Add agnoster-plus theme

README.md
Add [senpai-zsh](https://github.com/hiroru/senpai-zsh) theme
This makes it easier to find plugins/themes/completions by name since there aren't big clusters in the o and z sections of the list.
=> Add senpai

README.md
* Add razer-status-code
* Update zsh article link to https
=> Add razer-status-code, update zsh article link to https

README.md
Add link to [topan-theme-oh-my-zsh](https://github.com/fudyartanto/topan-theme-oh-my-zsh)
=> Add topan theme

README.md
=> Add bender theme

README.md
Add [gpg-crypt](https://github.com/Czocher/gpg-crypt) plugin
=> Add gpg-crypt plugin

README.md
=> Add powerline-pills Theme

README.md
Zplugin has a new distinct feature so I have listed it in description. Also changed beginning of description.
=> Update Zplugin description (add information on services support)

README.md
Add [avit-mod](https://github.com/zlsun/avit-mod) theme
=> Add avit-mod theme

README.md
* Renamed node-theme link to remove oh-my-zsh prefix
* Added ysm theme
* Added webicons theme
=> Add ysm theme

README.md
Add darksoku, hanpen and nox themes
=> Add darksoku, hanpen and nox themes

README.md
I updated the description of my [agkozak](https://github.com/agkozak/agkozak-zsh-theme) theme to reflect that it is now asynchronous. Many thanks for putting me on your list.
=> agkozak-zsh-theme is now asynchronous

README.md
Add [zgen-compinit-tweak](https://github.com/seletskiy/zsh-zgen-compinit-tweak)
=> Add zgen-compinit-tweak plugin

README.md
Add [geometry-datetime](https://github.com/desyncr/geometry-datetime) plugin
=> Add geometry-datetime plugin

README.md
Add [heart-theme](https://github.com/gko/heart-theme), [minimal2](https://github.com/PatTheMav/minimal2), [sleeplessmind](https://github.com/godbout/sleeplessmind-zsh-theme) and [tabaf](https://github.com/bvc3at/tabaf-zsh-theme) themes.
=> Add more themes

README.md
Add [leafia](https://github.com/Ghostrick/leafia-prompt) and [noon](https://github.com/silky/noon.zsh-theme) themes
=> 2018 01 14

README.md
Add @kwpolska's [kw](https://github.com/Kwpolska/kw.zsh-theme)
=> Add kw theme

README.md
Add [fortuity](https://github.com/VGamezz19/oh-my-zsh-fortuity-theme) theme
=> Add fortuity theme

README.md
Add [redis](https://github.com/zservices/redis) plugin.
=> Add redis plugin

README.md
Add [ansible-server](https://github.com/viasite-ansible/zsh-ansible-server) completions
=> Add ansible-server completions

README.md
Merge a branch that has been dangling for a while.
=> Add pastel theme

README.md
=> move razer plugin to plugins section

README.md
Add [imp](https://github.com/igormp/Imp) theme
=> Add imp theme

README.md
Add [enormous](https://github.com/leighmcculloch/zsh-theme-enormous) theme
=> Add enormous theme

README.md
* Add link to [helb](https://github.com/helb/helb.zshtheme) theme
=> Add helb theme

README.md
* Format cleanups
* Added link to [A Beautifully Productive Terminal Experience](http://mikebuss.com/2014/02/02/a-beautiful-productive-terminal-experience/)
=> 2018-01-25 Changes

README.md
* Add [aflah-bhari](https://github.com/AflahB/aflah-bhari-zsh-theme)
* Update fzf-mpd entry
* Text cleanups
=> Add aflah-bhari theme

README.md
Add [Toasty](https://github.com/5paceToast/toasty-zsh) framework
=> Add toasty

README.md
* Add [virtuozzo-plugin](https://github.com/TamCore/virtuozzo-zsh-plugin)
=> Add virtuozzo plugin

README.md
=> Adds wakatime-zsh-plugin

README.md
Make ZSH capitalization consistent
=> Make ZSH capitalization consistent

README.md
* Add a new colors plugin
* Disambiguate names since there are now two different colors plugins in the list
=> Add colors plugin

.travis.yml, README.md
Add [ec2ssh](https://github.com/h3poteto/zsh-ec2ssh) plugin
=> Add ec2ssh

README.md
Add [percol](https://github.com/robturtle/percol.plugin.zsh)
=> Add percol plugin

README.md
Add [zsh-nix-shell](https://github.com/chisui/zsh-nix-shell)
=> Add plugin to use zsh as nix shell

README.md
Add [rbenv](https://github.com/ELLIOTTCABLE/rbenv.plugin.zsh) plugin
=> Add rbenv, fix sorting

README.md
Add [beer](beer-theme) and [jose](https://github.com/tmjoseantonio/jose-zsh-theme) themes
=> Add beer and jose themes

README.md
Add [czsh](https://github.com/Cellophan/czsh) theme
=> Add czsh container/theme

README.md
=> Add oxide theme

README.md
Add [quoter](https://github.com/pxgamer/quoter-zsh)
=> Add quoter plugin

README.md
Add [laradock-workspace](https://github.com/rluders/laradock-workspace-zsh) plugin
=> Add link to laradock-workspace plugin

README.md
Adds [fishy-lite](https://github.com/pseudorook/fishy-lite) - Fork of the original [fishy](https://github.com/robbyrussell/oh-my-zsh/wiki/themes#fishy) theme in oh-my-zsh
=> Add fishy-lite theme

README.md
=> Add tmux-fork plugin

README.md
Add [delta](https://github.com/dongri/delta-zsh-theme) and [simplezsh](https://github.com/fr0zn/simplezsh) themes
=> Add bag of themes

README.md
Add [cinnabar](https://github.com/nvillapiano/zsh-theme---cinnabar) theme
=> Add cinnabar theme

README.md
Add [nuko](https://github.com/tzing/nuko.zsh-theme) them
=> Add nuko theme

README.md
=> Add battery plugin

README.md
Add link to [autoupdate-oh-my-zsh-plugins](https://github.com/TamCore/autoupdate-oh-my-zsh-plugins)
=> Add autoupdate-oh-my-zsh-plugins

README.md
=> Add pipenv completions

README.md
Add [workon](https://github.com/bryanculver/workon.plugin.zsh) plugin
=> Add workon

README.md
Adding the q plugin to the list! :)
=> Add q plugin.

README.md
=> Add yarn autocompletion

README.md
=> Update q plugin entry wording

README.md
* Add [iterm2-tabs](https://github.com/gimbo/iterm2-tabs.zsh) plugin
* Add [venv-lite](https://github.com/gimbo/venv-lite.zsh) plugin
=> Add gimbo plugins

README.md
=> Minor text cleanups

README.md
Add [hipstersmoothie-p9x](https://github.com/hipstersmoothie/PowerlevelHipstersmoothie) theme
=> Add hipstersmoothie-p9k

README.md
Added Iosevka font to Font section.
Iosevka is a highly customizable coder's font generated completly from code.
=> Added Iosevka font.

README.md
=> Add profile-secrets

README.md
Add [gmatheu](https://github.com/gmatheu)'s [dirrc](https://github.com/gmatheu/shell-plugins) and [explain-shell](https://github.com/gmatheu/shell-plugins) plugins.
=> Add explainshell and dirrc plugins

README.md
=> Add forgit plugin.

README.md
enkel and orobbl have gone 404, removed
=> enkel and orobbl have gone 404, removed

README.md
Add [lila](https://github.com/raphaelivan/lila-zsh-theme)
=> Add lila theme

README.md
Add link to [timewarrior](https://github.com/svenXY/timewarrior)
=> Add timewarrior plugin

README.md
Add [multiline](https://github.com/jan-auer/zsh-multiline) theme
=> Add multiline

README.md
* Add link to [zsh-fzy](https://github.com/aperezdc/zsh-fzy)
=> Add zsh-fzy plugin

README.md
=> Update fishy-lite link

README.md
Add link to [git-scripts](https://github.com/packruler/zsh-git-scripts)
=> Add git-scripts plugin

README.md
Add link to [xml-starlet](https://github.com/hejack0207/zsh-xmlstarlet-plugin/blob/master/xmlstarlet.plugin.zsh)
=> Add xmlstarlet completions

README.md
Adds a link to the [robbyrussell-WIP](https://github.com/ecbrodie/robbyrussell-WIP-theme) theme.
=> Advertises the robbyrussell-WIP theme

README.md
Add link to [jovial](https://github.com/zthxxx/jovial) theme
=> Add jovial theme

README.md
Add [hhktony](https://github.com/hhktony/hhktony.zsh-theme) and [saraiva](https://github.com/ruisaraiva19/saraiva-theme) themes
=> Mothers day 2018

README.md
Update to use correct link to beer theme.
=> Use working link to beer theme

README.md
* Move carthage and yarn completions to completions section
* Add [mx-honey](https://github.com/mukel/mx-honey) completion
=> Add mx honey

README.md
=> Add zjump plugin

README.md
Add link to [asq-theme](https://github.com/AugustoQueiroz/asq-theme)
=> Add asq theme

README.md
Add [bunnyruni.min](https://github.com/mikeumus/bunnyruni.min) theme
=> Add bunnyruni.min variant

README.md
Add [infernus](https://github.com/jshiell/infernus-zsh-theme) theme
=> Add infernus theme

README.md
Add [zgem](https://github.com/qoomon/zgem) framework
=> Add zgem framework

README.md
Add [gradle-completion (ninrod)](https://github.com/ninrod/gradle-zsh-completion)
=> Add @ninrod's gradle completion

README.md
`zhooks` is a tool for displaying the contents of all ZSH hook arrays (such as `$precmd_functions`) as well as any hook functions (such as `precmd`) that have been defined. It is intended to be used in debugging conflicts between scripts.
=> Added agkozak/zhooks

README.md
Add link to [markedit](https://github.com/zakariaGatter/MarkEdit) plugin
=> Add markedit plugin

README.md
* Adds [stashy](https://github.com/MisterRios/stashy) plugin.
=> Add stashy plugin

README.md
This fork has incorporated many new features and fixes. The old repository is not active.
Change link to point at an updated fork.
=> Update link for zsh-vim-mode plugin

README.md
=> Add zgem to TOC

README.md
@mdumitru has forked the [fancy-ctrl-z](https://github.com/mdumitru/fancy-ctrl-z), [git-aliases (mdumitru)](https://github.com/mdumitru/git-aliases) and [last-working-directory (mdumitru)](https://github.com/mdumitru/last-working-dir) out of the original [oh-my-zsh](http://ohmyz.sh/) so users of other frameworks don't have to import all of OMZ.
=> Add broken out omz plugins

README.md
Added Antibody installation example to the Antigen section – they both use the same approach.
- [?] All new and existing tests passed.
=> Added Antibody installation example

README.md
* Added link to [geometry-hydrate](https://github.com/jedahan/geometry-hydrate)
* Updated ZR description.
=> Add geometry-hydrate plugin

README.md
Add [wack](https://github.com/leoxlin/wack) plugini
=> Add wack plugin

README.md
Add link to [emojeer](https://github.com/lxynox/emojeer-ohmyzsh)
=> Add emojeer theme

README.md
Add link to [prompt-newt](https://github.com/softmoth/zsh-prompt-newt) theme
=> Add prompt-newt

README.md
Add [zsh-git-complete-urls](https://github.com/rapgenic/zsh-git-complete-urls) plugin
=> Add zsh-git-complete-urls plugin

README.md
=> Tweak newt theme blurb to sell it a little more

README.md
=> Add purify theme

README.md
Update elixir plugin description.
=> Update elixir-oh-my-zsh description

README.md
Add link to [fzf-finder](https://github.com/leophys/zsh-plugin-fzf-finder)
=> Add fzf-finder plugin

README.md
Add [lewis](https://github.com/lewisflude/oh-my-lewis) theme
=> Add lewis theme

README.md
=> Add extract plugin

README.md
Add link to [hashlink](https://github.com/tong/zsh.plugin.hashlink)
=> Add completion for hashlink

README.md
Add link to @AlexGascon's [pipenv](https://github.com/AlexGascon/pipenv-oh-my-zsh) plugin
=> Add AlexGascon's pipenv plugin

README.md
* Add link to [zsh-notes](https://github.com/chipsenkbeil/zsh-notes)
* Update atom plugin link name
=> Add zsh notes

PULL_REQUEST_TEMPLATE.md, README.md
=> Pull out BSD assignment into separate section

README.md
Add link to [zsh-crypto-prices](https://github.com/vincentdnl/zsh-crypto-prices)
=> Add crypto-prices plugin

README.md
Add link to [gitgo](https://github.com/ltj/gitgo)
=> Add link to gitgo

README.md
Add [zys-zsh-theme](https://github.com/ZYSzys/zys-zsh-theme)
=> Add zys theme

README.md
* Add [astral](https://github.com/alphabetum/astral)
=> Add astral theme

README.md
* Add [powerline-shell (b-ryan)](https://github.com/b-ryan/powerline-shell)
=> Add b-ryan's powerline shell

README.md
* Add [clean (BrandonRoehl)](https://github.com/BrandonRoehl/zsh-clean)
* Rename old clean entry to [clean (akz92)](https://github.com/akz92/clean)
=> Add BrandonRoehl's clean theme

README.md
Add [tmuxrepl](https://github.com/csurfer/tmuxrepl) plugin
=> Add tmuxrepl plugin

README.md
* Update references to solarized to link to https://github.com/altercation/solarized
=> Update solarized references to links

README.md
Add [craminzsh](https://github.com/FelipeCRamos/craminzsh)
=> Addd craminzsh

README.md
Add [oh-my-zsh-ys-cluster-theme](https://github.com/AndiH/oh-my-zsh-ys-cluster-theme) as **ys-cluster**
=> Add ys-cluster theme

README.md
* Add link to [wynwyn](https://github.com/thaffenden/wynwyn.zsh-theme) theme
* Update link to Ranger
=> Add wynwyn

README.md
Update wording in crypto-prices entry
=> Update wording in crypto-prices entry

README.md
Add link to [oh-my-matrix](https://github.com/amstrad/oh-my-matrix)
=> Add oh-my-matrix plugin

README.md
* Add [page](https://github.com/SLIB53/page-zsh-theme) theme
=> Add page theme

README.md
Add [ls](https://github.com/zpm-zsh/ls) plugin
=> Add ls plugin

README.md
* Add tmux plugin
* Fix sorting in plugins section
=> Add tmux plugin

README.md
* Add [zshrc](https://github.com/freak2geek/zshrc) plugin
=> Add zshrc plugin

README.md
Add the [auto-color-ls](https://github.com/gretzky/auto-color-ls) plugin
=> Add auto-color-ls

README.md
* Add link to [traffic-zsh-theme](https://github.com/fcce/traffic-zsh-theme)
=> Add traffic-zsh-theme

README.md
* Add link to [kraken-zsh](https://github.com/KrakenTheme/kraken-zsh)
=> Add kraken theme

README.md
* [Zplugin]((https://github.com/zdharma/zplugin) has added new features, update description
=> Zplugin has added new features, update description

README.md
Add link to [taskbook-zsh-plugin](https://github.com/mastern2k3/taskbook-zsh-plugin)
=> Add taskbook plugin

README.md
=> Update zplug description

README.md
Add [joe-completion](https://github.com/corvofeng/joe-completion)
=> Add joe-completion

README.md
Add [uvenv.plugin.zsh](https://github.com/vincentto13/uvenv.plugin.zsh)
=> Add uvenv plugin

README.md
[Q](https://github.com/y0ssar1an/q) is a debug tool which create a temporary file with debug info.
This plugin adds two functions for tailing and removing the $TMPDIR/q file.
=> Add q plugin

README.md
* Tweak wording in some descriptions
=> Tweak wording

README.md
Add hcompact, hfulldate and hornix themes
=> Add hcompact, hfulldate and hornix themes

README.md
=> Add nops theme

README.md
* Add ctop completion
* Add Kompose completion
* Add kubeadm completion
=> Add gantsign's zsh completions

README.md
=> Add kafka completions

README.md
=> Add base16 plugin

README.md
Update powerlevel9k description to match upstream
=> Update powerlevel9k desc to match upstream

README.md
Add [zsh-zsnapac](https://github.com/johnramsden/zsh-zsnapac) plugin for ZFS snapshotting
=> Add zsnapac plugin for ZFS snapshotting

README.md
Add gvm (Go version manager) plugin for ZSH
=> Add gvm plugin

README.md
=> Add qoomon theme

README.md
* Add link to [intellij](https://github.com/mgryszko/intellij)
* Make iTerm 2 references consistent
=> Add intellij

README.md
Add link to [robbyolivier](https://github.com/YuyeQingshan/robbyolivier)
Add link to [limpide](https://github.com/shooteram/limpide)
=> Add robbyolivier and limpide themes

README.md
* Add [iamskok](https://github.com/iamskok/iamskok.zsh-theme) theme
* Add [codemonkey-on-fire](https://github.com/babette-landmesser/codemonkey-on-fire.zsh-theme)
=> Add iamskok and codemonkey-on-fire themes

README.md
Add link to [vi-mode](https://github.com/hschne/vi-mode) plugin
=> Add vi-mode plugin

README.md
Add [colorbira](https://github.com/CristianCantoro/colorbira-zsh-theme) theme
=> Add colorbira theme

README.md
Add [shayan](https://github.com/shayanh/shayan-zsh-theme) theme.
=> add shayan-zsh-theme

README.md
* Update zulu framework description
=> Update zulu framework description

README.md
Update description of powerline-pills theme
=> Update description of powerline-pills theme

README.md
* Add link to [supertassu/another-theme](https://github.com/supertassu/another-theme)
=> Add just another theme

README.md
* Add link to [river-zsh-config](https://github.com/revir/river-zsh-config) theme
=> Add river theme

README.md
=> Add rufus theme

README.md
=> Rename nops to diy-ys

README.md
* Update zgen description
* Fix awkward phrasing in ZR description
* Fix oh-my-zsh link in ZPM description
* Make oh-my-zsh link in Zeesh description a link
* Add detail to zshing description
=> Update some framework descriptions

README.md
=> Added Terraform plugin

README.md
=> Update async description

README.md
* Add geometry plugins to display npm and rust versions in your geometry prompt
=> Add geometry plugins

README.md
Add link to [fz](https://github.com/changyuheng/fz)
=> Add fz plugin

README.md
Add [mode-switch.CLI](https://github.com/Gyumeijie/mode-switch.CLI)
=> Add mode-switch.CLI

README.md
* Make the case consistently all caps for ZSH
=> We were using zsh in some places and ZSH elsewhere

README.md
* Add [kenton](https://github.com/notnek/zsh-theme) theme
* Clean up themes section
* Add missing **.** characters
* Make references to `git` consistent
* Tweak wording in some entries
=> Add kenton theme

README.md
Add [purs](https://github.com/xcambar/purs)
=> Add purs theme

README.md
* Add PowerlevelHipstersmoothie
* Fix sorting in themes section
=> Add PowerlevelHipstersmoothie

README.md
Add shrug](https://github.com/tmjoseantonio/shrug-zsh-theme) theme
=> Add shrug theme

README.md
- Removed some 404 links
- Changes 301 redirections, mostly repositories with a different username
- Changed and re-ordered some themes with new name
=> Fix redirections and some 404s

README.md
* Update description of rummik theme
=> Update description of rummik theme

README.md
Add [app-up](https://github.com/Cloudstek/zsh-plugin-appup) plugin
=> Add app-up plugin

README.md
* Add [javaVersions](https://github.com/miguefl/javaVersions) plugin
=> Add javaVersions plugin

README.md
* Add link to [jc](https://github.com/jclementex/jc-zsh-theme)
=> Add jc theme

README.md
* Add link to [zeit](https://github.com/zeit/zeit.zsh-theme)
=> Add zeit theme

README.md
* Add link to [kevin](https://github.com/KevinParnell/Kevin-zsh)
=> Add kevin theme

README.md
* Add [bastard](https://github.com/jsundqvist/bastard.zsh-theme) theme
* Add [funkyberlin](https://github.com/Ottootto2010/funkyberlin-zsh-theme)
* Add [rb](https://github.com/rberenguel/rb-zsh-theme) theme
=> Add themes

README.md
=> add jenv-lazy plugin

README.md
Add link to https://github.com/brucehsu/oh-my-zsh-powerline-theme
=> Add brucehsu/powerline

README.md
* Add rad-zshell
* Update zsh-quickstart-kit description
* Add link to [zsh-artisan](https://github.com/jessarcher/zsh-artisan) plugin
* Add link to [zsh.deepjira.plugin](https://github.com/korniux/zsh.deepjira.plugin)
=> Halloween additions

README.md
* Add droolscar, prompt_j2, schminitz-v2 themes
* Fix sort in themes section
* Fix plugins sort
=> Add droolscar, prompt_j2 and schminitz-v2 themes

zsh-plugin-assesor/git-process-output.zsh, zsh-plugin-assesor/zpa.config, zsh-plugin-assesor/zsh-plugin-assessor
Could the script be commited to awesome-zsh-plugins now? I would then develop it limiting number of commits, and you could always stash-merge. The emoji support is easy to add but I'm waiting for your response.
This script parses and processes the data in the unixorn/awesone-zsh-plugins README.md page. It extracts plugins from the "Plugins" section of the document, clones each of them, runs a few git commands to establish facts about the plugin and outputs the plugin's overall score.
=> ZPA: Initial commit of a working evaluation-script, before emoji support

README.md
* Add asdf and baseballfunfacts plugins
* Update percol entry
* Remove dead theraveler theme
* Add thetraveler theme
=> Add asdf, baseballfunfacts

README.md
Add link to [seppuku](https://github.com/Helianthella/seppuku)
=> Add seppuku theme

README.md
* Add link to cd-reminder plugin
* Add link to vi-mode plugin
* Update virtualz entry
=> Update virtualz entry, add plugins

README.md
I recently updated this plugin to have additional functionality. This updates its description to match the new features.
=> Update iterm-tab-color description in README

README.md
Add link to [pointer-zsh-theme](https://github.com/gpinkard/pointer-zsh-theme)
=> Add pointer theme

README.md
Add [actiona](https://github.com/matthieusb/act) and [magento-2](https://github.com/dambrogia/oh-my-zsh-plugin-magento-2) plugins
=> Add actiona and magento-2 plugins

README.md
* Add link to [MooseX-App](https://github.com/perlpunk/MooseX-App-Plugin-ZshCompletion)
* Remove 404 link to pieni theme
=> Add MooseX-App completions

README.md
=> Add simpalt theme

README.md
Add last commit badge to readme
=> Add last commit badge

README.md
* Update description of the pastel theme
* Add gocilla theme
=> 2018-11-25 updates

README.md
* Add link to [ryner-zsh-theme](https://github.com/DoctorRyner/ryner-zsh-theme)
=> Add ryner theme

README.md
* Add [dotfiles](https://github.com/vladmyr/dotfiles-plugin) plugin
* Add [gumsible](https://github.com/Lowess/gumsible-oh-my-zsh-plugin) plugin
* Remove trailing `.zsh` from opp link name
*Add  [web-search](https://github.com/sinetoami/web-search) plugin
=> 2018-11-28 Additions

README.md
Add link to https://github.com/iboyperson/zsh-pipenv. Closes https://github.com/iboyperson/zsh-pipenv/issues/1
=> Add link to zsh-pipenv plugin

README.md
Update trinity theme description
=> Update trinity theme description

README.md
Add lambda-mod, minimal-improved and xm themes
=> 2018-12-02

README.md
Added [zapack](https://github.com/aiya000/zsh-zapack) framework
=> Add zapack plugin loader

README.md
Add link to [moux](https://github.com/gagbo/moux) theme
=> Add moux theme

README.md
Add link to [dotfiles](https://github.com/vladmyr/dotfiles-plugin)
=> Add dotfiles plugin

README.md
Add link to [phpenv.plugin.zsh](https://github.com/sptndc/phpenv.plugin.zsh)
=> Add phpenv plugin

README.md
Add link to https://github.com/evanthegrayt/grayt-zsh-theme
=> Add grayt theme

README.md
* Add pustelto theme, closes https://github.com/Pustelto/shell_theme/issues/1
=> Add pustelto theme

PULL_REQUEST_TEMPLATE.md
Clean up `PULL_REQUEST_TEMPLATE.md`
=> Tweak PULL_REQUEST_TEMPLATE.md

README.md
* Add [aws-mfa](https://github.com/FreebirdRides/oh-my-zsh-aws-mfa) plugin
* Add [cdc](https://github.com/evanthegrayt/cdc) plugin
* Update fzf-finder description
=> 2018-12-16 additions

README.md
* Add sdkman tab completions
* Add gruvbox theme
=> 2018-12-18 additions

README.md
=> Add whobrokemycode

README.md
Add jbrain4, ludwigws and saltine themes
=> 2018-12-29

README.md
* Fix url for tmux plugin
* Add [rbjorklin](https://github.com/rbjorklin/rbjorklin-zsh-theme) theme
=> 2019-01-06 Updates

README.md
* Add links to [nidoranarion](https://github.com/NicolaiRuckel/nidoranarion) and [skill](https://github.com/frontendmonster/oh-my-zsh-skill-theme) themes
* Add link to [rustup](https://github.com/pkulev/zsh-rustup-completion) tab completions
=> 2019-01-06/07

README.md
=> Add chaotic-beef theme

README.md
=> Add clipboard plugin

README.md
Add brs theme
Closes https://github.com/evenhold/brs-zsh-theme/issues/2
=> Add brs theme

README.md
=> Add zsh-proxy plugin

README.md
Add z.lua, assume-role and zimfw-extras plugins
=> Add z.lua, assume-role and zimfw-extras

README.md
* Update fishy-lite description
* Add sushi theme
* Add zeroastro theme
=> 2019-02-02

README.md
* Add russtone and papercolor themes
=> 2019 02 03

README.md
=> Add gcloud-project

README.md
=> 2019-02-09 Additions

.travis.yml, README.md
* Update `awesome_bot` whitelist to deal with SSL issues on some links
* Add jwalter, siegerts and sukeesh themes
=> 2019-02-10

README.md
=> Add raytek theme

README.md
* Add pks-autocomplete
* Add fast-alias-tips
=> 2019-02-11

README.md
* Add sfdx autocomplete plugin
* Remove 404 mango theme
* Add cherry theme
=> Add sfdx autocomplete plugin

README.md
Add [cayun](https://github.com/comeacrossyun/ys-cayun.zsh-theme) now that https://github.com/comeacrossyun/ys-cayun.zsh-theme/issues/1 is closed.
=> Add cayun theme

README.md
Closes eduardnikolenko/minima#1
=> Add minima theme

README.md
* Add system-clipboard plugin
* Add akzsh theme
* Fix sort in themes section
- [*] Add/remove a plugin
- [*] This document is covered by the [BSD License](https://github.com/unixorn/awesome-zsh-plugins/blob/master/LICENSE), and I agree to contribute this PR under the terms of the license.
- [*] I have confirmed that the link(s) in my PR are valid.
- [*] My entries are single lines and are in the appropriate (plugins, themes or completions) section, and in alphabetical order in their section.
- [*] I have read the **CONTRIBUTING** document.
- [*] All new and existing tests passed.
- [*] I have stripped leading and trailing **zsh-** or **oh-my-zsh-** substrings from the link name. This makes it easier to find plugins/themes/completions by name since there aren't big clusters in the **O** …
=> Add system-clipboard plugin and akzsh theme

Writing_Plugins.md
Update the plugin author howto recommendations
=> Update plugin howto

.circleci/config.yml
Add circleci configuration file
=> Add CircleCI, R.I.P travis

.circleci/config.yml
* First try at validating README.md with CircleCI
=> First pass at a CircleCI configuration

.travis.yml, README.md
* Add CircleCI build status badge
* Remove travis configuration file
* Remove travis build status badge
=> Finish switch to CircleCI

README.md
* Add deepx plugin
* Update alien theme description
=> 2019-03-09 Updates

README.md
* Update apple-touchbar description
* Update Peco-history description
* Add pi theme
=> 2019 03 updates

README.md
* Add dangerroom theme
* strerror.plugin.zsh is 404, removed.
* Add Sheldon framework
=> Pi Day updates

README.md
Add the gentoo ZSH completions
=> Add gentoo completions

README.md
* Add chaffee theme
* Add logico theme
* Fix sort in Fonts section
* Standardize case of Nerd Fonts entry
=> 2019-03-17 Updates

README.md
* Add archie theme
* omz-vira theme is 404, removed.
=> Add archie theme

README.md
* Add elessar theme
* Add yyl-ys theme
* Add superkolo theme
- [*] Add/remove a theme
- [*] This document is covered by the [BSD License](https://github.com/unixorn/awesome-zsh-plugins/blob/master/LICENSE), and I agree to contribute this PR under the terms of the license.
- [*] I have confirmed that the link(s) in my PR are valid.
- [*] My entries are single lines and are in the appropriate (plugins, themes or completions) section, and in alphabetical order in their section.
- [*] I have read the **CONTRIBUTING** document.
- [*] All new and existing tests passed.
- [*] I have stripped leading and trailing **zsh-** or **oh-my-zsh-** substrings from the link name. This makes it easier to find plugins/themes/completions by name since there aren't big clusters in the **O** and **Z** sections …
=> 2019-03-20 Updates

README.md
=> Add luke theme

README.md
New plugin: [passwordless-history](https://github.com/jgogstad/passwordless-history). Keep passwords out of the ZSH history file.
=> Plugin: passwordless-history

README.md
Add [powerlevel10k](https://github.com/romkatv/powerlevel10k), [zinc](https://gitlab.com/robobenklein/zinc) theme.
=> add two themes.

README.md
=> Add kote theme

README.md
* Add sixlive theme
* Add simplex theme
* Add shocm theme
* Add fzf-git plugin
=> 2019-04-02 Updates

README.md
=> Add oh-flowers theme

README.md
* Add gumbo theme
* Add kotterstep theme
=> 2019-04-04 Theme updates

README.md
* Add adamdodev theme
* Add cactus theme
=> 2019-04-05 updates

README.md
Added an entry for the [slugify](https://github.com/lashoun/slugify) plugin. Not sure what sort of tests I am supposed to run so I did not check the corresponding checkbox below.
**EDIT**: nevermind, the tests all passed.
=> add slugify plugin

README.md
* Update liquidprompt description
=> Update liquidprompt description

README.md
=> Add krak3n theme

README.md
* Add alehouse, exa, and evalcache plugins
* Add bazel tab completions
=> 2019-04-13 updates

README.md
* Add fluent-git theme
* Add phalanx theme
* Add whale theme
* Update aphrodite theme description
=> 2019-04-15 updates

README.md
* Add pr-is-root plugin
* Add pr-node plugin
* Add check-reps plugin
* Add pr-git plugin
=> 2019-04-17 Updates

.github/PULL_REQUEST_TEMPLATE.md, README.md
* Add small-terminal-diy theme
* Add yechen theme
* Add pr-exec-time plugin
* Markdown fixes
=> 2019-04-19 Updates

README.md
* Add aronhoyer theme
* Add hyper theme
* Add dkniffin theme
=> April 22nd 2019 Updates

README.md
=> Add coffeenostor theme

README.md
* Add poetry plugin
* Add pr-jobs plugin
* Add xVanjaZ's oh-my-zsh-quickstart
=> 2019-04-24 Updates

README.md
=> Add musy theme

README.md
=> Add toggl plugin

README.md
add this plugin https://github.com/qoomon/zsh-history-search
=> plugin - lazyload

README.md
=> Add iterm2 plugin

README.md
=> Add gideon theme

README.md
* Add bar theme
* Add tepig-ys theme
=> 2019 May 6th updates

README.md
=> Add common theme

README.md
* Add arity theme
* Add bryce-robbyrussell theme
=> 2019 may updates

README.md
Add my own theme, [sm-theme](https://github.com/blyndusk/sm-theme), a **Simplist** & **Minimalist** theme for your **favorite** terminal.
=> Add sm-theme

README.md
* Update link address for logico theme
* Add thefuck plugin
* Add ipip plugin
* Add undollar plugin
=> 2019 May 20th Updates

README.md
* Add link to [zsh-theia-dev-tools](https://github.com/taPublic/zsh-theia-dev-tools)
=> Add theia-dev-tools

README.md
* Add that-human-jason-theme
* Update description of clipboard plugin
=> 2019 May 22 updates

README.md
=> Add terragrunt plugin

README.md
* Add furry-umbrella theme
* Add midin theme
* Update grayt theme's description
=> 2019 May 26 updates

README.md
Update the description of the `sheldon` framework.
=> Update sheldon description

README.md
=> Add phantomk

README.md
* Add php-version-rcfile-switcher plugin
=> Add php-version-rcfile-switcher plugin

README.md
=> Add moderno theme

README.md
=> Add bliss theme

README.md
* Add illuvia-gitster theme
* Add rainbowie theme
* Add lambda theme
* Update spaceship theme description
=> June 10 2019

README.md
=> Add eucalyptus theme

README.md
* Update almostontop description with link to original bash plugin
=> Update almostontop description with link

README.md
* Tweak some descriptions in the plugins section
=> Minor text tweaks in plugins section

.circleci/config.yml, README.md
* Themes
* Added sy theme
* Added matrix theme
* Text cleanups in plugins section
* Phrasing fixes in descriptions
* Made references to git and vi mode more consistent
* Consistently refer to oh-my-zsh
* Added links to tools some helper plugins assist with
=> Plugin section cleanup

README.md
* Add igit plugin
* Add mexassi theme
=> Add igit plugin and mexassi theme

README.md
=> Add jake theme

README.md
=> Add kubecolor plugin

README.md
* Moved pure-agnoster and purs themes from plugins section to themes
* Added quotify plugin
=> Theme cleanups and add quotify plugin

README.md
* Add gime theme
* Add grs theme
=> Add grs and gimezsh themes

README.md
=> Add arrow-minimal theme

Contributing.md
* Update Contributing.md to show we prefer new submissions have a license file
* Minor wording tweaks
=> Update Contributing guidelines

README.md
Update descriptions for simplezsh and sinon themes
=> Update descriptions for simplezsh and sinon themes

README.md
* Update descriptions for lamdba and powerline-go themes
=> update descriptions for lamdba and powerline-go themes

README.md
Add lambda-minimal now that https://github.com/sohnryang/lambda-minimal-theme/issues/1 is closed.
=> Add lambda-minimal theme

README.md
Adds pew plugin now that https://github.com/shosca/zsh-pew/issues/1 is closed
=> Add pew plugin

README.md
* Update autoswitch-virtualenv desc to include that it works with pipenv
* Add powerbash theme
=> Update autoswitch-virtualenv desc, add powerbash theme

README.md
* Add forerunner theme
* himself theme is 404, removed
=> Add forerunner theme

README.md
=> Add pr-eol plugin

README.md
=> Add zsh-auto-notify plugin

README.md
* Add Nord theme now that https://github.com/TyWR/Nord-zsh/issues/1 is completed.
=> Add nord theme

README.md
* Add link to crasis zplugin helper
=> Add link to crasis zplugin helper

README.md
Add some plugins from [zpm-zsh](https://github.com/zpm-zsh)
=> Add some plugins from zpm-zsh

README.md
Replace "dotfines" with "dotfiles" in the description of the dotfiles plugin
=> Fix typo in the description of the dotfiles plugin

README.md
* Update jwalter theme description
=> Update jwalter description

README.md
Add [pr-cwd](https://github.com/zpm-zsh/pr-cwd) from zpm-zsh
=> Add pr-cwd from zpm-zsh

README.md
* Fix sort in plugins and completions sections
=> Fix sort in plugins and completions sections

README.md
* Add hana-matcha theme
* Add kyu theme
* Add rei theme
* Add shichi theme
* Minor theme description tweaks
=> Add arturoalivar's themes

README.md
=> Add simple theme

README.md
* Add tsotra theme
* Disambiguated cdimascio and halfo's lambda themes
* Updated name and description for lambda-v theme
=> Add tsotra theme, cleaned up lambda section

README.md
=> Add thyme theme

README.md
=> Add  owiewestside theme

README.md
* Add code-review and presenter-mode plugins
=> Add code-review and presenter-mode plugins

.github/PULL_REQUEST_TEMPLATE.md, Contributing.md
* Add checklist items to PR templates to confirm new entries have license files
* Add checklist item to PR template to confirm new themes have screen shots
* Reorganize Contributions.md
=> Update Contributions guideline and PR Template

README.md
* Add celestialorb  theme
* Add windows-title plugin
=> Aug 21, 2019 updates

README.md
* Add tmux-multisession plugin
=> Add tmux-multisession plugin

README.md
=> Add npm plugin

README.md
=> Add gitsterv2 theme

README.md
* Add standalone plugin for [homebrew](https://brew.sh/)
=> Add brew plugin

README.md
* Fixed antibody plugin install instructions
* Added duckster theme (per https://github.com/ducky/duckster/issues/1)
* Added ristovic theme (per https://github.com/ivan-ristovic/zsh-theme/issues/1)
=> Update antibody section, add some themes

.circleci/config.yml, README.md
* Renamed ristovic to xris47 per author request
* Added fall and seashell themes
* Whitelisted en.ipip.net since it occasionally throws 5xx errors when circleci is running the test suite
=> 2019-08-31 theme additions

README.md
* Added rhklite's palenight and disambiguated jenssegers' palenight entry
=> Added rhklite's palenight theme

README.md
* Add z-p-test and z-p-man plugins
=> Add z-p-test and z-p-man plugins

README.md
=> Add hug theme

README.md
* Add kasperhesthaven's vscode plugin
* Remove tahuri theme that has gone 404
=> Add kasperhesthaven's vscode plugin

README.md
=> Add safe-kubectl plugin

README.md
Closes https://github.com/jeromescuggs/jerome-theme/issues/1
=> Adds jerome theme.

README.md
* Add hanjunlee's terraform plugin, disambiguate pbar1's
=> Add hanjunlee's terraform plugin

README.md
* Add wyntau's fzf wrapper plugin
Closes  https://github.com/wyntau/fzf-zsh/issues/2
=> Add wyntau's fzf wrapper plugin

README.md
* Add [node-path](https://github.com/andyrichardson/zsh-node-path) plugin
=> Add node-path plugin

.github/PULL_REQUEST_TEMPLATE.md
Fixes #772
I mostly meant something like this.
=> Suggest adding a link in the PR description

README.md
* Add maivana theme
* Update description of phalanx theme - make references live links
* Update description of yarn completions
=> September 15th, 2019 Updates

README.md
* Add [damino](https://github.com/njdom24/Damino-Zsh-Theme) theme
* Add [ohmypc](https://github.com/joselpadronc/OhMyPC) theme
* Add [zsh313](https://github.com/amirali313/zsh313-theme) theme
Closes https://github.com/joselpadronc/OhMyPC/issues/1
Closes https://github.com/amirali313/zsh313-theme/issues/1
=> September 16, 2019 changes

README.md
* Adds [cxzh](https://github.com/MakeWorkSimple/cxzh.zsh-theme)
Closes https://github.com/MakeWorkSimple/cxzh.zsh-theme/issues/1
=> Add cxzh theme

README.md
* Add link to [iterm2-utilities](https://github.com/decayofmind/zsh-iterm2-utilities)
=> Add iterm2-utilities plugin

README.md
I'm adding the two Zplugin extensions:
- https://github.com/zplugin/z-a-bin-gem-node
- https://github.com/zplugin/z-a-patch-dl
and also updating the links/names to the renamed/moved 2 other Zplugin extensions.
Also the following zsh-plugins are added:
- https://github.com/zdharma/declare-zsh
- https://github.com/zdharma/zsh-github-issues
- https://github.com/zdharma/zsh-tag-search
- https://github.com/zdharma/zsh-startify
And a link in Zplugin description is updated.
=> Add zplugin/{z-a-bin-gem-node,patch-dl} Zplugin extensions

README.md
=> Remove some 404ed entries

README.md
The link to one plugin was wrong + extended the description of Zplugin a bit.
=> Fix zplugin/z-a-patch-dl link and add declare-zsh to Zplugin description

README.md
* Add[fzf-fasd](https://github.com/wookayin/fzf-fasd) plugin
=> Add fzf-fasd plugin

README.md
Update description for [powerlevel10k](https://github.com/romkatv/powerlevel10k) to clarify it is a drop-in replacement for [powerlevel9k](https://github.com/bhilburn/powerlevel9k).
=> Update powerlevel10k description

README.md
* Add [zlong_alert](https://github.com/kevinywlui/zlong_alert.zsh) plugin
=> Add zlong_alert plugin

README.md
* Add [safe-rm](https://github.com/mattmc3/zsh-safe-rm) now that https://github.com/mattmc3/zsh-safe-rm/issues/1 is closed.
=> Add safe-rm plugin

README.md
A completion plugin for `conda`.
=> Add conda-zsh-completion

README.md
* Add [hina](https://github.com/ucpr/hina) theme
* Add [sm](https://github.com/blyndusk/sm-theme) theme
=> Hacktoberfest 2019

README.md
* Add anki-code bar theme, disambiguate xp-bar bar theme
=> Add anki-code bar theme, disambiguate xp-bar bar theme

README.md
Nice [zplugin](https://github.com/zdharma/zplugin)'s tutorial repos.
TOC - Intallation typo fix
=> add Zplugin tutorial

README.md
* Add [kubectx](https://github.com/unixorn/kubectx-zshplugin) plugin
=> Add kubectx plugin

README.md
* Add [rbpi](https://github.com/kcousot/rbpi-plugin) plugin
=> Add rbpi plugin

README.md
* Add [nonotes](https://github.com/stevemcilwain/nonotes) plugin
=> Add  nonotes plugin

README.md
* Add [samshell](https://github.com/samuelb/samshell) theme
Closes https://github.com/samuelb/samshell/issues/1#issuecomment-541321189
=> Add samshell.

README.md
This adds https://github.com/zplugin/zplugin-console to the plugins list and also extends description of Zplugin + changes "zplugin" to "Zplugin".
=> Add zplugin-console

README.md
* Add [nvm-lazy](https://github.com/davidparsson/zsh-nvm-lazy) plugin
=> Add nvm-lazy plugin

README.md
* Add [ice](https://github.com/Lenart12/ice.zsh-theme) theme
=> Add ice theme

README.md
* Add [iguanidae](https://github.com/btd1337/iguanidae-zsh-theme) theme
=> Add iguanidae theme

README.md
* Add [daily](https://github.com/ghlin/zsh-theme-daily) theme
* Add [mdmini](https://github.com/MarioDena/MDmini) theme
=> Add daily and mdmini themes

README.md
* Add [hexagon](https://github.com/diogoazevedos/hexagon) theme
* Add [neurosimple](https://github.com/davidsierradz/neurosimple-oh-my-zsh-theme/blob/master/neurosimple.zsh-theme)
* Fix typo in [bar (anki-code)](https://github.com/anki-code/zsh-bar-theme) link text
=> Add neurosimple and hexagon themes

README.md
* Add [shrikant](https://github.com/shr1k4nt/shrikant_zsh_theme) theme
=> Add shrikant theme

README.md
* Add [blazux](https://github.com/blazux/omz-theme) theme
* Add [FDT2K](https://github.com/FDT2k/FDT2K-theme) theme
* Fix [kubectl](https://github.com/mattbangert/kubectl-zsh-plugin) link text
* Update [eriner](https://github.com/zimfw/eriner) description
=> October 24 theme additions and minor edits

.circleci/config.yml, README.md
* Add link to zdharma's [zdharma/pm-perf-test](https://github.com/zdharma/pm-perf-test)
* Add link to [z-a-rust](https://github.com/zplugin/z-a-rust) zplugin extension
* Whitelist https://docs.virtuozzo.com in circleci tests since the site sporadically fails during tests
=> Add z-a-rust, perf benchmarks

README.md
* Add [zshred](https://github.com/redxtech/zshred) theme
=> Add zshred theme

README.md
=> Minor edits in theme links

README.md
* Add [history-enquirer](https://github.com/zthxxx/zsh-history-enquirer) plugin
* Add [workbench](https://github.com/u8slvn/oh-my-zsh-workbench-theme) theme
=> Add history-enquirer and workbench

README.md
* Add [leverage](https://github.com/gschnall/leverage) theme
=> Add leverage theme

README.md
=> Change description for zpm

README.md
Update link to ZSH gem 24.
Closes #812
=> Update link to ZSH gem 24

README.md
* Add link to [snakypy](https://github.com/snakypy/snakypy-prompt)
=> Add snakypy theme

README.md
* Add [laravel-au](https://github.com/Saleh7/laravel-au-zsh-plugin) plugin
* Add [saml2aws-auto](https://github.com/devndive/zsh-saml2aws-auto) plugin
* Add [bougenville](https://github.com/bougenville/zsh-theme) theme
=> November 4, 2019 Updates

README.md
* Add [async](https://github.com/mje-nz/zsh-themes) theme
* Add [matter](https://github.com/mrobillard/matter-zsh-theme) theme
=> Add async and matter themes

README.md
* Add link to [banana](https://github.com/sorcererxw/banana-zsh-theme)
=> Add banana theme

README.md
* Add [parrot](https://github.com/kennedy69/parrot-zsh-theme) theme
=> Add parrot prompt

README.md
* Add [dtheme](https://github.com/OlukaDenis/DTheme) theme
* Update minima entry
=> Add dtheme, update minima

.github/PULL_REQUEST_TEMPLATE.md
Update instructions inside PR template
=> Update instructions inside PR template

README.md
* Add [boss-git](https://github.com/bossjones/boss-git-zsh-plugin) plugin
* Add [gnrnzh](https://github.com/PaoloneM/gnrnzh-zsh-theme) theme
=> Nov 13th updates

README.md
* Add [history-here](https://github.com/leonjza/history-here) plugin
=> Add history-here plugin

README.md
* Add [collon](https://github.com/lambdalisue/collon.zsh) theme
*  Add [gitster](https://github.com/zimfw/gitster) theme
* Add [magicmace](https://github.com/zimfw/magicmace) theme
* Add [s1ck94](https://github.com/zimfw/s1ck94) theme
=> Add collon,  gitster, magicmace and s1ck94 themes

README.md
* Add [lando](https://github.com/JoshuaBedford/lando-zsh) plugin
* Add [vagrant-box](https://github.com/evanthegrayt/vagrant-box-wrapper) plugin
=> Add lando and vagrant-box

README.md
* Add link to [pmy](https://github.com/relastle/pmy)
=> Add pmy completion engine

README.md
* Add link to [nuts](https://github.com/rafaelsq/nuts.zsh-theme) theme. Closes https://github.com/rafaelsq/nuts.zsh-theme/issues/1
=> Add nuts theme

README.md
=> Add containerized-ansible and sdkman plugins.

README.md
*  Add link to [guish](https://github.com/gcarrarom/oh-my-guish). Closes https://github.com/gcarrarom/oh-my-guish/issues/1.
*  Add link  to [neewbie](https://github.com/neewbee/neewbee.zsh-theme) theme
* feddamisch's github account is 404, remove their themes
=> Add guish and neewbie

README.md
* Add [zemoji](https://github.com/mashaal/wild-cherry/tree/master/zsh)
Closes https://github.com/therzka/zemoji/issues/1
=> Add zemoji theme

README.md
* Add link to [ducula](https://github.com/janjoswig/Ducula) theme
=> Add ducula theme

README.md
* Add [goenv (CDA0)](https://github.com/CDA0/zsh-goenv/blob/master/zsh-goenv.plugin.zsh) plugin
* Disambiguate between [goenv (CDA0)](https://github.com/CDA0/zsh-goenv/blob/master/zsh-goenv.plugin.zsh) and [goenv (bbenne10)](https://github.com/bbenne10/goenv)
=> Add another goenv plugin and disambiguate the two in the list

README.md
* Add link to [print-alias](https://github.com/brymck/print-alias)
=> Add print-alias plugin

README.md
* Add link to [tig](https://github.com/zdharma/zsh-tig-plugin) plugin
=> Add tig plugin

README.md
* Add link to [salesforce-cli](https://github.com/wadewegner/salesforce-cli-zsh-completion)
=> Add link to salesforce completions.

README.md
* Add link to [history-popup](https://github.com/lcrespom/oh-my-zsh-history-popup) plugin
Closes https://github.com/lcrespom/oh-my-zsh-history-popup/issues/1
=> Add link to history-popup plugin

README.md
* Add link to [zflai](https://github.com/zdharma/zflai) framework
=> Add zflai framework

README.md
* Add link to [cypher-ruby](https://github.com/ston1x/cypher-ruby)
Closes https://github.com/ston1x/cypher-ruby/issues/1
=> Add cypher-ruby theme

README.md
* Add [redline](https://github.com/DrissTM/redline.zsh-theme) theme
* Add [short-ys](https://github.com/OREOmini/short-ys-zsh-theme) theme
=> 2019-12-6 updates

README.md
* Add link to [bruh](https://github.com/haze/bruh) theme.
Closes https://github.com/haze/bruh/issues/1
=> Add bruh theme

README.md
* Add link to [griffin](https://github.com/GriffinLedingham/griffin.zsh-theme) - Closes https://github.com/GriffinLedingham/griffin.zsh-theme/issues/1
* Add link to [sunrise-ruby](https://github.com/ston1x/sunrise-ruby) - Closes  https://github.com/ston1x/sunrise-ruby/issues/1
=> Add sunrise-ruby theme

README.md
* Add [hedroed-bureau](https://github.com/Hedroed/hedroed-bureau.zsh-theme)  theme
=> Add hedroed-bureau theme

README.md
* Add link to [metalmajor](https://github.com/deblauwetom/metalmajor-zsh-theme) - closes https://github.com/deblauwetom/metalmajor-zsh-theme/issues/1#event-2878802818
=> Add metalmajor theme

README.md, Writing_Plugins.md
Add link to [thnikk](https://github.com/thnikk/zsh-theme-thnikk) theme
=> Add thnikk theme

README.md
* Add new extract plugin and disambiguate the old one
* Update thnikk and simpalt descriptions
=> Add new extract plugin; update text descriptions

README.md
* Update descriptions for nix-shell and last-working-directory plugins
=> Tweak descriptions

README.md
Add [hapin](https://github.com/hanamiyuna/hapin-zsh-theme/blob/master/hapin.zsh-theme) theme. Closes https://github.com/hanamiyuna/hapin-zsh-theme/issues/1
=> Add hapin theme

README.md
* Add new symfony completions plugin
* Disambiguate symfony plugin and completion
=> Add symfony completions

README.md
* Add [systemd](https://github.com/le0me55i/zsh-systemd) plugin. Closes https://github.com/le0me55i/zsh-systemd/issues/1
=> Add systemd plugin

README.md
Geometry has been updated to be easier to customize, I figure its worth differentiating a bit from other prompts.
* [geometry](https://github.com/geometry-zsh/geometry) - A minimal ZSH theme where any function can be added to the left prompt or (async) right prompt on the fly.
=> geometry: update description

README.md
* Add link to [terraform (macunha1)](https://github.com/macunha1/zsh-terraform)
=> Add macunha1's terraform plugin

README.md
Closes https://github.com/philFernandez/printc/issues/1
=> Add printc plugin

README.md
* Add [youtube-dl-aliases](https://github.com/katrinleinweber/oh-my-zsh-youtube-dl-aliases)
Closes https://github.com/katrinleinweber/oh-my-zsh-youtube-dl-aliases/issues/1
=> Add youtube-dl-aliases plugin

README.md
* Add tab-title plugin
* Update url for cf-zsh-autocomplete plugin
=> Add tab-title

README.md
* Add [lambda (azahi)](https://github.com/azahi/zsh-lambda), closes https://github.com/azahi/zsh-lambda/issues/1
* Delete 404ed ciacho and containerized-ansible themes
=> Add azahi's lambda theme

README.md
*  Adds [apollo](https://github.com/mjrafferty/apollo-zsh-theme), closes https://github.com/mjrafferty/apollo-zsh-theme/issues/1
=> Add apollo theme

README.md
* Add [node-env-installer](https://github.com/shiro-saber/node-env-installer)
=> Add node-env-installer plugin

README.md
* Adds [case](https://github.com/rtuin/zsh-case) plugin
=> Add case plugin

README.md
A new plugin [zdharma/zzcomplete](https://github.com/zdharma/zzcomplete) and add a mention about Zplugin project being very active.
- [ x] I have confirmed that the link(s) in my PR are valid.
=> Add zdharma/zzcomplete and update Zplugin description

README.md
* Add arael, lilith and ramiel themes
* Fix name of fishy2 theme
* Update description of the-time-lord theme
* Add t2er theme
=> Add arael, lilith, ramiel and t2er themes

README.md
* Add [plankton](https://github.com/tobiaseichert/plankton-zsh-theme) theme. Closes https://github.com/tobiaseichert/plankton-zsh-theme/issues/1
=> Add plankton theme.

README.md
* Add [typewritten](https://github.com/reobin/typewritten) theme
* Add [mbolis](https://github.com/mbolis/mbolis-zsh-theme) theme now that https://github.com/mbolis/mbolis-zsh-theme/issues/1 is closed
=> Add typewritten and mbolis themes

README.md
* Add [agnoster-j](https://github.com/apjanke/agnosterj-zsh-theme) theme
* Update links in ansible-role-zsh entry
=> Add agnoster-j theme

README.md
* Add [ez-pz](https://github.com/mangosmoothie/ez-pz) theme.
=> Add ez-pz theme

README.md
* Rename Zplugin to Zinit
* Update entries for some of zdharma's plugins that were affected by rename
* Update toc
=> Rename zplugin to zinit

README.md
* Add [aws2](https://github.com/drgr33n/oh-my-zsh_aws2-plugin) plugin
=> Add aws2 plugin

README.md
* Add homebrew plugin now that https://github.com/digitalraven/omz-homebrew/issues/1 is closed
=> Add homebrew plugin

README.md
=> Add vi-quote plugin

README.md
* Add [kiss](https://github.com/rileytwo/kiss)
Closes https://github.com/rileytwo/kiss/issues/1
=> Add kiss theme

README.md
* Update slimline url
* Add [eckig](https://github.com/fouladi/eckig) theme
=> Update url for slimline theme, add eckig theme

README.md
Removed dead plugin links from my repositories that got merged into ohmyzsh.
=> Remove dead plugins.

.circleci/config.yml, README.md
* Update circleci configuration to deal with some problem links
* Add birav2 and halil themes
=> Add birav2, tweak circleci config

README.md
Add [halfeld](https://github.com/IgorHalfeld/halfeld-zsh-theme) now that https://github.com/IgorHalfeld/halfeld-zsh-theme/issues/1 is closed
=> Add halfeld theme

.circleci/config.yml, README.md
* Remove kitchen.ci from the circleci whitelist
* Add zelda theme
=> Add Zelda, update whitelist

README.md
zinit used to be called zplugin, and it was difficult for me to find it on this list (or even google it!) because online resources (blog posts and such) still call it zplugin. So, this PR adds mention of the old name.
=> Update zinit description with name change

README.md
I refrained from adding vi-motions before since it used to just enable existing zsh functions.
However, I added a lot more custom text objects now.
=> Add vi-motions, vi-increment, toggle-command-prefix

README.md
I've rebuilt the Zinit description and extended it – it now is enumeration oriented and a little longer than before. Is the length OK?
=> Update Zinit description + fix some related typos

README.md
* Add mattberther/zsh-nodenv
* Update command-time description
=> Add mattberther/zsh-nodenv

README.md
Add link to ubuntu-ish now that https://github.com/Thesola10/zsh-ubuntu-ish/issues/1 is resolved.
Closes https://github.com/Thesola10/zsh-ubuntu-ish/issues/1
=> Add ubuntu-ish theme

README.md
Add reggae theme now that https://github.com/nmercado1986/zsh-reggae-theme/issues/1 is closed.
=> Add reggae theme

README.md
* Add brolly0204's minima, disambiguate eduardnikolenko's minima
=> Add brolly0204's minima theme

README.md
* Add [clearance](https://github.com/H00N24/clearance-theme-oh-my-zsh) theme
* Update TOC
=> Add clearance theme

README.md
Made a plugin, would like to add it to the list.
https://github.com/bhayward93/Linus-rants-ZSH
=> Adding linus-rants plugin

README.md
* Add rc-files plugin
* Update history-here entry formatting
=> Add rc-files plugin, update history-here entry formatting

README.md
* Add [venv-wrapper](https://github.com/glostis/venv-wrapper) plugin now that https://github.com/glostis/venv-wrapper/issues/1 is fixed.
=> Add venv-wrapper plugin

README.md
=> add mouse-status

README.md
=> Add zsh-om theme

README.md
* Add Meroje's rbenv plugin now that https://github.com/Meroje/zsh-rbenv/issues/1 is closed
=> Add Meroje's rbenv plugin

README.md
* Update z.lua description
* Update z-a-bin-gem-node description
* Update description for yarn autocompletions
* Add z-a-submods zinit extension
=> 2020 March 1 updates

README.md
*  Add jacobin and squanchy themes
=> Add jacobin and squanchy themes

README.md
* Add nnvm plugin now that https://github.com/torifat/nnvm/issues/1 is closed
* Add npms plugin
=> Add nnvm and npms plugins

README.md
* Add biradate theme
* atom_plugin.zsh is 404; remove
=> Add biradate theme

README.md
Add JHLeeeMe theme. Closes https://github.com/unixorn/awesome-zsh-plugins/issues/909
=> Add JHLeeeMe theme

README.md
=> doc: added edward cli links

README.md
=> Add oath plugin

README.md
* Clean up tutorial section
* Add belak's antigen QuickStart
* Update astral theme entry
* Author changed their GH username
* Description update
=> Update astral theme entry, tutorial cleanups

README.md
=> Add miramare and ysr themes

README.md
=> Add saml2aws plugin

README.md
Add [theta](https://github.com/eendroroy/theta) and [theta-async](https://github.com/jesec/zsh_theme_theta-async) themes.
=> Add theta and theta-async themes

README.md
I created a [ph-marks](https://github.com/lainiwa/ph-marks) plugin for bookmarking pornhub videos and I want to share it with others!
=> Add ph-marks plugin

README.md
* Add glsorre's minimal theme
* Disambiguate subnixr's minimal
Closes https://github.com/glsorre/minimal/issues/2
=> Add glsorre's minimal theme

.circleci/config.yml, README.md
Adds [session-sauce](https://github.com/ChrisPenner/session-sauce). A plugin for managing tmux sessions at the project level using fzf.
✅ Also fixes the circle-ci builds. Unfortunately they run more slowly now, but it's better than being completely broken 😄
=> Add session-sauce plugin (And fix circle-ci builds)

README.md
* Add blinks and theto themes now that https://github.com/max13fr/blinks.zsh-theme/issues/1 and https://github.com/victorgama/theto-zsh-theme/issues/1 are closed.
=> Add blinks and theto themes

README.md
Now that https://github.com/unixchad/shtr0m/issues/1 is closed, add shtr0m theme
=> Add shtr0m theme

README.md
=> Add fzf-tab plugin

README.md
* Add antsy theme now that https://github.com/jeffmhubbard/antsy-zsh-theme/issues/1 is closed.
=> Add antsy theme

README.md
=> Add traista theme

README.md
I've added 2 links, to the packages and to a Wiki document..
=> Extend Zinit description a little

README.md
Adds a link to yazpt - a clean, fast, good-looking zsh prompt theme that thoughtfully incorporates Git/Subversion/TFVC status info, integrates with popular plugin managers like Oh My Zsh, and is straightforward to customize and extend. 
https://github.com/jakshin/yazpt
=> Add the yazpt theme

README.md
* Add switch-git now that https://github.com/robin-mbg/switch-git/issues/1 is closed.
* Add rhuang2014's brew plugin and disambiguate wolffaxn's
* Update url for squanchy theme
=> Add switch-git plugin

README.md
Add arc plugin now that https://github.com/anton-rudeshko/zsh-arc/issues/1 is closed.
=> Add arc plugin

README.md
[autocomplete](https://github.com/marlonrichert/zsh-autocomplete) - Automatically lists completions as you type. Press Tab to insert the top match or press Down to select a different one. Press Shift-Tab for more choices/info, Space to correct the last word, Up to search history and Ctrl-Space to search dirs/files.
=> Add marlonrichert/zsh-autocomplete

README.md
* Add wdnote now that https://github.com/Vesdii/zsh-wdnote/issues/1 is closed.
=> Add wdnote plugin

.circleci/config.yml, README.md
Add zsh-bash-completions-fallback, hub, gtr and direnv plugins
=> 2020 may updates

README.md
[dotbare](https://github.com/kazhala/dotbare) - A command-line utility to interactively manage dotfiles through `git bare` method and `fzf`. It is inspired by [forgit](https://github.com/wfxr/forgit), but focus on dotfile management. It could also easily integrates with any symlink or GNU stow setup. `dotbare` aims to solve the lack of completion problem for `git bare` method and the tedious `git checkout` conflict during migration by providing a simple command to migrate dotfiles to new systems.
=> Add kazhala/dotbare plugin

README.md
=> Add instructions for `zpm`

README.md
Add homeassistant-cli now that https://github.com/frosit/zsh-plugin-homeassistant-cli/issues/1 is closed.
=> Add homeassistant-cli plugin

README.md
Add Crème fraîche now that https://github.com/koenwoortman/creme-fraiche-zsh-theme/issues/1 is resolved.
=> Add Crème fraîche theme

README.md
Add boss-docker now that https://github.com/bossjones/boss-docker-zsh-plugin/issues/1 is closed.
=> Add boss-docker plugin

README.md
* Add link to [tmux-auto-title](https://github.com/mbenford/zsh-tmux-auto-title)
=> Add tmux-auto-title plugin

README.md
Add icicle now that https://github.com/JamesConlan96/Icicle/issues/1 is closed.
=> Add icicle theme

README.md
* Remove bazel - it is 404
* Remove timewarrior - the app it is a plugin for hasn't renewed their DNS.
* Update homebrew plugin description.
=> Remove bazel - it is 404

README.md
* Update url for zit framework
* Add pkenv plugin
* Add linkfile plugin now that https://github.com/JaumeRF/linkfile-zsh/issues/1 is closed
=> 2020 june updates

README.md
* Add lambder now that https://github.com/avillen/zsh-theme-lambder/issues/1 is closed.
=> Add lambder theme
