- README.md
Add git-simple theme now that https://github.com/ZakharEl/git-simple-theme/issues/1 is closed.
> Add git-simple theme

- README.md
Add garden theme now that it has a license and screen shot, closes https://github.com/fecat233/garden/issues/1
> Add garden theme

- README.md
Add [ztupide](https://github.com/mpostaire/ztupide) framework now that https://github.com/mpostaire/ztupide/issues/1 is closed.
> Add ztupide framework

- README.md
* Fixed several plugin descriptions didn't have capitalization consistent with other list entries.
* Some minor phrasing tweaks in plugin descriptions.
> Text cleanups in Plugins section

- README.md
* Update zgen framework's description
* Fixed various inconsistencies in casing, missing dashes and a variety of typos in the themes section.
> Update zgen description, clean up Themes section

- README.md
> Update Black-Void description

- README.md
> Add PMS framework

- README.md
* Add envrc plugin now that https://github.com/fabiogibson/envrc-zsh-plugin/issues/1 is closed
> Add envrc plugin

- README.md
Add zsh-recall plugin now that https://github.com/mango-tree/zsh-recall/issues/1 has been resolved.
> Add recall plugin

- README.md
> Add z-a-unscope plugin

- README.md
> Add minimal-prompt theme

- README.md
Add command-execution-timer plugin
> Add command-execution-timer plugin

- README.md
Add Kallahan23's colorls plugin
> Add Kallahan23's colorls plugin

- README.md
> Add uz framework

- README.md
* Add link to ztheme framework & update TOC
* Remove webicons theme, it's gone 404
> Add ztheme framework

- README.md
This PR adds the [easy-motion plugin](https://github.com/IngoHeimbach/awesome-zsh-plugins).
> Add easy-motion plugin

- README.md
* Add z-a-meta-plugin
* Update description of macunha1's terraform plugin
> Add z-a-meta-plugin

- README.md
Add link to a plugin with an example rust program that listens to and processes commands sent by ZSH.
Closes https://github.com/al-jshen/zshplug-rs-example/issues/1
> Add Rust example

- README.md
Add link to Windows ZSH superconsole and closes https://github.com/alexchmykhalo/superconsole/issues/1
> Add superconsole tutorial/plugin for ZSH on Windows

- README.md
Add hitokoto. Closes https://github.com/derry96/hitokoto/issues/1
> Add hitokoto plugin

- README.md
* Add persi theme
* Add docker-completion tab completion
* Move other docker completions from plugins section to completions section
> 2020-08-08 updates

- README.md
* Add link to [Frictionless zsh And oh-my-zsh Management With Antigen](https://thorsten-hans.com/frictionless-zsh-and-oh-my-zsh-management-with-antigen) article
> Add "Frictionless zsh And oh-my-zsh Management With Antigen" article

- README.md
Add now that https://github.com/roman-geraskin/xxh-plugin-zsh-zshrc/issues/1 is closed
> Add xxh-plugin-zsh-zshrc plugin

- README.md
* Add search-directory-history plugin
* Add per-directory-history plugin
* Add doas now that https://github.com/anatolykopyl/doas-zsh-plugin/issues/1 is closed.
> Add search-directory-history, per-directory-history and doas plugins

- README.md
> Add git-flow-avh plugin

- README.md
* Add probe_zsh theme now that https://github.com/probe2k/probe_zsh/issues/1 is closed.
> Add probe_zsh theme

- README.md
Adds [hangul](https://github.com/gomjellie/zsh-hangul). A plugin for Korean users.
Auto correct hangul(한글, korean) to english when it was supposed to be typed english. 영어를 타이핑 해야되는데 한글로 타이핑된경우 자동으로 수정합니다.
> Add hangul

- README.md
* Add @hermitmaster's exa plugin and disambiguate @DarrinTisdale's
> Add hermitmaster's exa plugin

- README.md
* Add [git](https://github.com/davidde/git) plugin
> Add another git plugin

- README.md
* Add [ppsmon](https://github.com/mzpqnxow/ppsmon) plugin
> Add ppsmon plugin

- README.md
Update location of exa plugin. Closes #992.
> Update url for exa plugin

- README.md
Add Dr4kk0nnys_v2 theme now that https://github.com/Dr4kk0nnys/Dr4kk0nnys_theme_ohmyzsh_v2/issues/1#issuecomment-685870212 is closed
> Add Dr4kk0nnys_v2 theme

- README.md
* Add [dino](https://github.com/OdilonDamasceno/dino-zsh-theme) theme
> Add dino theme

- README.md
* Add simple-git now that https://github.com/BazaJayGee66/simple-git-theme/issues/1 is closed.
> Add simple-git theme

- README.md
> zpwr uses zinit

- README.md
I've smoothed the description and slightly rephrased a few sentences.
> Update Zinit paragraph.

- README.md
* Fix PMS entry, update TOC too
> Fix PMS entry

- README.md
> Add nikitakot theme

- README.md
* Add anki-code's bar theme settings
> Add anki-code's bar theme settings

- README.md
Add [ShellSpec](https://shellspec.info) to ZSH Tools section. (Are additions to the ZSH Tools section allowed?)
> Add ShellSpec to ZSH Tools section

- README.md
Add another fzf plugin, disambiguate it from wyntau's
> Add another fzf plugin, disambiguate it from wyntau's

- README.md
Add [znap](https://github.com/marlonrichert/zsh-snap) framework
> Add znap framework

- README.md
Merge changes missed on old staging branch
> Merge changes missed on old staging branch

- README.md
* Add kgzsh now that Kashugoyal/kgzsh#1 is closed.
* Add bureau-env now that angus-lherrou/bureau-env#1 is closed
> Add bureau-env and kgzsh themes

- README.md
> Add azcli plugin

- README.md
* Add s7c theme now that https://github.com/Samega7Cattac/s7c.zsh-theme/issues/2 is closed.
> Add s7c theme

- README.md
> Update Znap info

- README.md
* Add ale theme now that https://github.com/alepimentel/ale-zsh/issues/2 is closed
> Add ale theme

- README.md
* Add miniplug framework
* Update pyenv plugin
> Add miniplug framework

- README.md
> Add git-lfs plugin

- README.md
Update description of pure prompt
> Update description of pure prompt

- README.md
Add gitstatus theme now that https://github.com/kimyvgy/gitstatus-zsh-theme/issues/1 is closed
> Add gitstatus theme

- README.md
Add zsh-arduino plugin now that https://github.com/raghur/zsh-arduino/issues/1 is closed.
> Add arduino plugin

- .github/PULL_REQUEST_TEMPLATE.md
Add a spammer warning.
I never thought I'd have to do this, but people suck.
> Add spammer warning

- README.md
https://github.com/cryocaustik/cryo-zsh-theme/issues/1#event-3825608253 is closed, add cryo theme
> Add cryo theme

- .github/PULL_REQUEST_TEMPLATE.md
Make spam warning less in your face
> Make spam warning less in your face

- README.md
> Add duration plugin

- Contributing.md
> Update Contributing.md to cope with hacktoberfest spam

- README.md
> Update toc for miniplug

- README.md
> Add monthrename plugin

- README.md
zgen is stagnant, zgenom is a fork that's still getting development effort. Add to framework list.
> Add zgenom framework

- README.md
Fixed the heading value for the Font section
> Fix Font section heading 

- README.md
Move zgenom framework entry to Frameworks section
> Added zgenom in the wrong place :-(

- README.md
Add watch now that https://github.com/enrico9034/zsh-watch-plugin/issues/1 is closed.
> Add watch plugin

- README.md
Add a link to [code-stats-zsh](https://gitlab.com/code-stats/code-stats-zsh).
> Add code-stats-zsh plugin

- .circleci/config.yml
- README.md
Add mh-fzj, closes https://github.com/mh-firouzjaah/mh-fzj-oh-my-zsh-theme-v1/issues/1
> Add mh-fzj theme.

- README.md
> Add cdc plugin

- README.md
> Add vapor plugin

- README.md
* Add zerocake theme now that https://github.com/ZeroPoke/ZeroCake.zsh-theme/issues/1 is closed
> Add zerocake theme

- README.md
Added Lighthaus theme. [Project Repo](https://github.com/lighthaus-theme/zsh)
> Added Lighthaus theme for zsh

- README.md
Add clean theme now that https://github.com/Patr1ot/clean.zsh-theme/issues/1 is closed.
> Add clean theme

- README.md
* Update heart theme link
* Add fnm plugin
> Add fnm, update heart

- .github/PULL_REQUEST_TEMPLATE.md
> Clean up PR template

- README.md
* Add jsporna's terraform plugin
* Add git-prune now that https://github.com/diazod/git-prune/issues/17 is closed
> Add jsporna's terraform and diazod's git-prune plugins

- README.md
Add the Dien Bui oh-my-zsh beginners guide to the list.  This tutorial covers the basic installation and usage of oh-my-zsh.
> Add Getting started with oh-my-zsh to the list of tutorials

- README.md
Add the Karl Hadwen Youtube tutorial on how to get started with oh-my-zsh on macOS. This video covers the basics of what oh-my-zsh is, what it is used for and how to use it on macOS.
> add Learn Zsh in 80 Minutes macOS to the list of tutorials

- .github/PULL_REQUEST_TEMPLATE.md
Remove spam notice from PR template
> Remove spam warning from PR template

- README.md
* Add chello theme. Closes https://github.com/Abdalla981/chello/issues/1 and https://github.com/Abdalla981/chello/issues/2
> Add chello theme

- README.md
> Add Oh My Posh theme

- README.md
Added theme as requested [here](https://github.com/rslavin/af-magic-dynamic/issues/1)
> added af-magic-dynamic theme

- README.md
> Add coldark theme

- README.md
* Add ys theme now that https://github.com/tinyRatP/ys/issues/1 is closed.
* Add bruse plugin now that https://github.com/aubreypwd/zsh-plugin-bruse/issues/2 is closed.
* Disambiguate tinyRatP and cristiancavalli ys themes
> Add ys theme and bruse plugin

- README.md
Add bubblified and guezwhoz themes
> Add bubblified and guezwhoz themes

- README.md
Add plain-ui now that https://github.com/purveshpatel511/plain-ui/issues/1 is closed
> Add plain-ui theme

- README.md
Add mochi and mochi2 themes now that https://github.com/mochidaz/zsh-themes/issues/1 is closed
> Add mochi and mochi2 themes

- README.md
* Add panda theme
* Add gunstage plugin
* Add zsh-in-docker plugin
> Add panda theme, gunstage & zsh-in-docker plugins.

- README.md
* Add classyTouchName theme
* Add purify theme
> Add classyTouchName and purify themes

- README.md
* Add fish theme now that https://github.com/Raniconduh/zshfish/issues/1 is closed
* Add avil theme now that https://github.com/avil13/avil-zsh-theme/issues/2 is closed.
> Add avil and fish themes

- README.md
> Add 1999 theme

- README.md
* Add termux now that https://github.com/rooted-cyber/Termux-zsh-theme/issues/1 is closed.
* Update histdb entry
> Add termux theme

- README.md
> Add instant-repl plugin

- README.md
* Update robbyrussell/oh-my-zsh links to ohmyzsh/ohmyzsh
* Add fav plugin
> Add fav plugin, update oh-my-zsh links

- README.md
> Add bubblegum theme

- README.md
* Add [awsume](https://github.com/Sordie/AWSume) plugin
* Update descriptions for autoswitch-virtualenv and aws-cli-mfa plugins
* Add saravanbalagi's humbled and modesty themes
* Add tianheg's nodeys theme, disambiguate marszall87's
> Add plugins, themes, text updates

- Writing_Plugins.md
Clarify plugin writing recommendations
> Clarify plugin writing recommendations

- README.md
* Add [passion](https://github.com/ChesterYue/ohmyzsh-theme-passion) theme now that https://github.com/ChesterYue/ohmyzsh-theme-passion/issues/5 is closed
* Add [unit-1](https://github.com/nerdbude/Unit-1) now that https://github.com/nerdbude/Unit-1/issues/1 is closed.
> Add passion and unit-1 themes

- README.md
* Add jon theme
* Add sulfurium theme now that it has a screen shot. Closes https://github.com/Sulfurium/zsh-theme/issues/1.
* Fix nodesys (tianheg) link
> Add jon and sulfurium themes

- README.md
> Add kube theme

- README.md
> Add macos and rho themes

- README.md
> Add zsh1999 theme

- README.md
> Add osx-autoproxy plugin

- README.md
* Add plantyhoe now that https://github.com/totoroot/plantyhoe.zsh-theme/issues/1 is closed.
* Remove linuxbrew plugin now that linuxbrew has merged with homebrew
> Add plantyhoe theme

- README.md
A ZSH plugin for s3cmd - Amazon S3 and other cloud storage service providers that use the S3 protocol.
> Add s3cmd plugin

- README.md
* Add zlambda theme now that https://github.com/wdhg/zlambda/issues/1 is closed.
> Add zlambda theme

- README.md
Add ampel now that https://github.com/jeetelongname/Yeet-theme/issues/1 is closed.
> Add ampel theme

- README.md
* Add nbrylevv theme now that it has a license (closes https://github.com/nbrylevv/nbrylevv-zsh-theme/issues/1)
* Add ptaveres' zsh-z plugin and disambiguate agkozak's.
> Add nbrylevv theme and zsh-z plugin

- README.md
Fix case of zr framework. Closes https://github.com/unixorn/awesome-zsh-plugins/issues/1083
> Fix case of zr framework

- README.md
> Add roundy theme

- README.md
* Add neon-potato theme
* Remove deprecated [fzf (wyntau)](https://github.com/wyntau/fzf-zsh) plugin
> Add neon-potato theme

- README.md
> Add lambda-zen theme

- README.md
Add [emoji](https://github.com/masaakifuruki/emoji.zsh-theme) theme
> Add emoji theme

- README.md
> Add msfvenom tab completions

- README.md
* Add mira now that https://github.com/mbStavola/mira/issues/1 is closed.
> Add mira theme

- README.md
> Add buster and dbern themes

- README.md
Add robbyrussell-fullpath theme now that https://github.com/toytag/robbyrussell-fullpath.zsh-theme/issues/1 is closed.
> Add robbyrussell-fullpath theme

- README.md
Add lightbulb and newton themes.
> Add lightbulb and newton themes

- README.md
* Add chenhao-ye's thyme theme
* Disambiguate kawamurakazushi's thyme theme
* Add 99hud theme
> Add thyme and hud themes

- README.md
Add andy's theme now that https://github.com/andymcguinness/andys-theme/issues/1 is closed
> Add andy's theme

- README.md
[vi-mode](https://github.com/jeffreytse/zsh-vi-mode) - 💻 A better and friendly vi(vim) mode plugin for ZSH.
> docs: add `zsh-vi-mode` plugin

- README.md
> Add zplugr framework

- README.md
* Add riddle-me and random-quotes plugins
* Add minimal-signal theme
> 2020-12-29 Update

- README.md
* Add bogo, frank and omuse themes.
* Remove 99hud theme - it is 404.
> 2021 New Year's Day update

- README.md
> Add simpleTheme

- README.md
> Fix bad sort in list sections

- README.md
> Add hist plugin

- README.md
> Add zcolors plugin

- README.md
Add bofh, dev and smile plugins
> 2021-01-13 updates

- README.md
Add chgo now that https://github.com/sbfaulkner/chgo-plugin-zsh/issues/1 is closed
> Add chgo plugin

- README.md
* Add klassiker & mnml themes
* Add carapace completion generator
* Add haskell completions
> 2021-01-15 Updates

- .github/PULL_REQUEST_TEMPLATE.md
Update frameworks checkbox in PR template
> Update frameworks checkbox in PR template

- README.md
Zplugr is now PZ, change framework entries accordingly.
> Zplugr is now PZ

- README.md
- Add xor theme
- Update shtr0m theme location
- Add web-open plugin
> 2021 MLK day updates

- .github/workflows/awesomebot.yml
- README.md
- Update url for logico theme, they've changed their github username
- Fix typo in mnml theme description
> 2021-01-19 Text cleanups

- README.md
- Add mike-was-here theme. Closes https://github.com/leguim-repo/mike-was-here-theme/issues/1
> Add mike-was-here theme

- README.md
- Add zpm-zsh's f-shortcuts plugin
- Add zpm-zsh's pretty-time plugin
- Add termux plugin
> 2021-01-20 updates - Inauguration Day!

- README.md
> Add update-zsh plugin

- README.md
> Add mad theme

- README.md
Add shelf plugin now that https://github.com/ecmma/shelf/issues/1 is closed.
> Add shelf plugin

- README.md
Antibody is deprecated by the author. Remove. Closes #1117
> Antibody is deprecated by the author. Remove.

- README.md
Add vulcan theme now that it has a license and screen shot.
Closes https://github.com/Bruceboy/vulcan-zsh-theme/issues/1
> Add vulcan theme

- README.md
* Add shini and my-hl2 themes
* Tweak wording in zcolors theme description
> 2021-01-28 Updates

- README.md
* Update miramare description
* Add reegnz's aws-vault plugin and disambiguate blimmer's
* Add rust plugin
* Add vcshr plugin
> 2021-01-30 updates

- README.md
- https://github.com/narrensingh/zsh-custom-theme-narren/issues/1 is closed, add narren theme.
> Add narren theme

- README.md
Add prompt-generator. Closes https://github.com/the10thWiz/zsh-prompt-generator/issues/1
> Add prompt-generator

- README.md
- Add bedbugs theme
- Add cmd-status plugin
- Add mzpm framework
> 2021-02-02 Updates

- README.md
- Update znap entry
- Add cargo tab completions
- Add gitlab-runner tab completions
> 2021-02-03

- README.md
> Add saturn prompt

- README.md
- Add gaia theme
- parrot theme is 404, removing
> Add gaia theme

- README.md
> Adds gaia theme

- README.md
- Add delta now that https://github.com/asavoy/delta-zsh-theme/issues/1 is closed.
- Disambiguate asavoy and dongri's delta themes.# Type of changes
- Add lish now that https://github.com/bashelled/lish/issues/1 is closed
> Add delta and lish themes

- README.md
> zpwr update counts

- README.md
> Add vercel theme

- README.md
Update silver theme's description
> Update silver theme description

- README.md
> Add terminal-title plugin

- README.md
> Add auto-nvm plugin

- README.md
Update proxy plugin description
> Update proxy plugin description

- README.md
> Add r3verse theme

- README.md
Update link now that https://github.com/C-uo/zsh-nodenv/issues/3 is closed.
> Update link to C-uo's nodenv plugin

- README.md
Add jyumpp theme now that https://github.com/Jyumpp/jyumpp-zsh-theme/issues/1 is closed
> Add jyumpp theme

- README.md
> Add yazt theme/plugin manager

- README.md
* Add last-working-directory-tmux plugin
* Add cpan tab completion
> Add last-working-directory-tmux

- README.md
- Add laravel sail plugin
- Add node ace plugin
- Add zabb plugin
> February 22nd, 2021 updates

- README.md
- Add pnpm plugin
- Add apple theme
> 2021-02-25 updates

- README.md
Lots of name fixes.
- Fix name of conda, nix, gcloud, git-annex, git-flow, grid5000 and joe completions
- Update git-flow description
- Disambiguate gulp names
> 2021-02-26 updates

- README.md
Adds the following plugin:
- [zfzf](https://github.com/b0o/zfzf) - A fzf-powered file picker for ZSH which allows you to quickly navigate the directory hierarchy.
> Add zfzf plugin

- README.md
- Add p10k-promptconfig  plugin
- Add ch4rli3 theme
- Add alarangeiras theme
> 2021-03-03 update

- README.md
- Add emoji-fzf plugin
- Update fz description
> 2021-03-06 updates

- README.md
Add quewui theme now that https://github.com/kauefontes/oh-my-quewui/issues/1 and https://github.com/kauefontes/quewui-zsh/issues/1 are closed.
> Add quewui theme

- README.md
> Update shini description

- README.md
> Add compe completion

- README.md
> Add qi3ber2 theme

- README.md
Add bol plugin. Closes https://github.com/ikhurramraza/bol/issues/1
> Add bol plugin

- README.md
Add svn-n-zsh plugin now that https://github.com/khrt/svn-n-zsh-plugin/issues/4 is closed
> Add svn-n-zsh plugin

- README.md
- Add nx tab completion
- Add 000 theme
- Add gentoo plugin
- Add handy theme
> March 23 2021 updates

- README.md
> Add doodleshell theme

- README.md
Add vitesse theme now that https://github.com/rafaeldellaquila/zsh-vitesse-theme/issues/1 is closed.
> Add vitesse theme

- README.md
> Update newt theme entry

- README.md
> Add black-void theme

- README.md
- Add ghoti theme
- Add jpegleg theme
> 2021-04-07 updates

- README.md
Add lambda-blazinggit theme now that https://github.com/zalefin/lambda-blazinggit/issues/1 is closed.
> Add lambda-blazinggit theme

- README.md
Add ubuntu theme now that https://github.com/janstuemmel/zsh-ubuntu-theme/issues/1 is closed.
> Add ubuntu theme

- README.md
> Add sshukh plugin

- README.md
* Add sit theme now that https://github.com/svensen/sit.zsh-theme/issues/1 is closed.
* Add flowr tab completion plugin for [git-flow](http://github.com/nvie/gitflow).
* Update eckig description
> Add sit theme

- README.md
Add yabai completions now that https://github.com/Amar1729/yabai-zsh-completions/issues/1 is closed.
> Add yabai tab completion

- README.md
- Add @mannuel's lando plugin
- Disambiguate @joshuabedford's lando plugin
> Add mannuel's lando alias plugin

- README.md
Theme added to table of contents.
Refactored existing code and packaged as a common Zsh theme
Note: My personal code is GPLV3, because I understand this license best. I have no problems with your release under BSD. I'm just happy if someone finds my theme useful.
> Added michaelpass theme

- README.md
- Add tinygo tab completion
- Add helmfile tab completion
- Add 14degree theme
> 2021-04-23 updates

- README.md
Add cleansh theme now that https://github.com/diegoos/cleansh/issues/1 is closed.
> Add cleansh theme

- README.md
Add batect completion now that https://github.com/batect/batect-zsh-completion/issues/31 is closed.
> Add batect completion

- README.md
- Fix chr-fritz's docker completion entry
- Add enhancd plugin
> 2021-04-26 Updates

- README.md
- Add raspberrysh, closes https://github.com/MaxMalinowski/raspberrysh/issues/1
> Add raspberrysh theme

- README.md
> Add ubunly theme

- README.md
Update `arduino` and `nx` entries with links to [jq](https://stedolan.github.io/jq/)
> 2021-05-14 Updates

- README.md
Add kido now that https://github.com/KidoThunder/kido-zsh-theme/issues/1 is closed
> Add kido theme

- README.md
- Add lukerandall-extended theme
- Add dotnet completion
- Remove duplicate exercism entry
- Add fzf-tab-completion
- Update zgen and zgenom entries
- Update TOC
> 2021-05-18 Updates

- README.md
- Now that https://github.com/Bhupesh-V/ugit/pull/11 is closed, add `ugit` to plugin list.
- Add `gitstatus` plugin
- Move `gitster` and `gitsterv2` from plugin section to theme section
> git tool related updates

- README.md
- Add  [terraform (thuandt)](https://github.com/thuandt/zsh-terraform) plugin
- Add [aliyun](https://github.com/thuandt/zsh-aliyun) completion
> 2021-05-22 Updates

- README.md
- Add 5amu's minimal prompt, This prompt includes a VPN status which is nice
> Add 5amu's minimal prompt

- README.md
- Add **skim** plugin
- Update **aws-vault** description
- Update **simpleserver** description
> Add skim + text updates

- README.md
- Add fizzy theme (closes https://github.com/Brokenhammer72/fizzy/issues/1 ).
> Add fizzy theme

- README.md
- Add zeno plugin now that https://github.com/yuki-yano/zeno.zsh/issues/26 is closed.
- Add unicorn theme
> Add zeno plugin and unicorn theme

- README.md
- Add chrisandrew.cl theme
- Fix some link descriptions
- Add reload plugin
- Add worktree plugin
> 2021-05-29 updates

- README.md
- Add bash theme
- Add starship theme
- Update purs description
- Add turs theme
> 2021 may updates

- README.md
> Add exa and pipx plugins

- README.md
> Add tzpm framework

- README.md
> Add qiime and lifeway plugins

- README.md
- Add **tm** plugin
- Update **tmux-vim-integration** entry
> Add tm plugin

- README.md
> Add gndx theme

- README.md
- Add cmdtime now that https://github.com/tom-auger/cmdtime/issues/1 is closed.
- Add atuin - Closes #1224
> Add atuin and cmdtime plugin

- README.md
- Add c plugin
- Add posh-git-bash
> Add c and posh-git-bash

- README.md
- Add kali theme now that https://github.com/h4ck3r0/kali-theme/issues/3 is closed.
> Add kali theme

- README.md
- Add longsilvern theme now that now that https://github.com/long263/longsilvern-zsh-theme/issues/6 is closed
- Add bureau-parrot now that it has a license - closes https://github.com/BenjaminGuzman/bureau-parrot/issues/1
> Add longsilvern and bureau-parrot

- README.md
> Add zsh-not-vim plugin

- README.md
- Add emacs plugin - closes https://github.com/Flinner/zsh-emacs/issues/1
- Add zaw-source plugin
> Add emacs and zaw-source

- README.md
Update descriptions for lish theme and PMS framework
> Update lish and PMS descriptions

- README.md
Adds https://github.com/redxtech/zsh-fzf-utils to the plugins list.
> add zsh-fzf-utils to plugins list

- README.md
Clarify/Update calibre-zaw-src description
> Clarify/Update calibre-zaw-src description

- README.md
> Add show-path plugin

- README.md
- Add fzf-it plugin
- Add serious theme
- Remove trailing spaces from zaw entry
> Add fzf-it plugin and serious theme

- README.md
> Add gbt theme

- README.md
Though [this plugin](https://github.com/benvan/sandboxd) isn't strictly for ZSH, I've found it incredibly useful and only stumbled upon it by some serendipitous searching… I'd imagine other people could enjoy it as well!
> Add sandboxd plugin

- README.md
Add mini-simple now that https://github.com/ysl2/mini-simple-zsh-prompt/issues/1 is closed.
> Add mini-simple theme

- README.md
Adds https://github.com/redxtech/zsh-asdf-direnv to the plugins list.
> add asdf-direnv plugin

- README.md
> Add whales theme

- README.md
> Add raz theme

- README.md
Now that https://github.com/gustavohellwig/gh-zsh/issues/1 is closed, add gustavohellwig's script for setting up ZSH on debian/ubuntu-based linuxes.
Don't merge until https://github.com/gustavohellwig/gh-zsh/issues/2 is closed.
> Add GH setup script

- README.md
- Add volta plugin
- Update mau theme entry
- Add lunachar theme
> 2021-06-30 Updates

- README.md
Add zinsults plugin now that https://github.com/ahmubashshir/zinsults/issues/1 is closed.
> Add zinsults

- README.md
> Add zpico framework

- README.md
> feat: add Lemon theme zsh

- README.md
> Update lemon theme entry

- README.md
- Add tre plugin
- Add kitty tab completions
> 2021-07-05 Updates

- README.md
- Add navi plugin
- Add simple-yet-beautiful theme
> 2021-07-06 Updates

- README.md
Add sudosabin's poetry plugin and disambiguate darvid's.
> Add sudosabin's poetry plugin

- README.md
https://github.com/tfiala/zsh-perlbrew/issues/1 is closed, add perlbrew plugin.
> Add perlbrew plugin

- README.md
> Add yup plugin

- README.md
- Add git-branches plugin
- Update zeta description
> Add git-branches plugin

- README.md
https://github.com/rogeliosamuel621/rs-zsh-theme/issues/1 is closed, add rs theme
r3verse is 404, remove
> Add rs theme

- README.md
Add replace-multiple-dots plugin
> Add replace-multiple-dots plugin

- README.md
- Add lean theme
- Add exa plugin
> Add lean and exa

- README.md
> Add simple prompt

- README.md
- Add roz theme now that https://github.com/rozNum/roz-zsh-theme/issues/1 is closed.
- Add stellachar theme now that https://github.com/r-mohammadi1/stellachar/issues/1 is closed,
> Add roz and stellachar

- README.md
Add shadow now that https://github.com/agentshadow/shadow-zsh-theme/issues/1 is closed
> Add shadow theme

- README.md
- Add yeet and shirnschall themes
> Add yeet and shirnschall themes

- .github/PULL_REQUEST_TEMPLATE.md
- Contributing.md
- README.md
Update the contributing guidelines.
- Minor wording changes
- Added link to Contributing.md to the PR template
- Spell out that we don't want leading or trailing `zsh-plugin`, `zsh-theme` or similar phrases in the visible link text.
> Update the contributing guidelines.

- README.md
Add zzshell now that https://github.com/thezzisu/zzshell/issues/1 is closed.
> Add zzshell prompt

- README.md
Now that https://github.com/AndreyPuzanov/tonni4-zsh-theme/issues/1 is closed, add tonni4
> Add tonni4 theme

- README.md
nodeys and r3vers are 404, remove
> Remove dead nodeys and r3vers links

- README.md
- Add vertepommes theme
- Add kctl plugin
> Add vertepommes and kctl

- README.md
- Add tron & momoyo themes
- Add smartinput plugin
> Add smartinput, tron and momoyo

- README.md
> Update theto entry

- README.md
-  Add https://github.com/Ryooooooga/zabrze 
- Add https://github.com/warrensbox/terraform-switcher
> Add tfswitch and zabrze

- README.md
- Add kube-aliases plugin
- Add daniloheraclio theme
- Add gal theme
- Update mau theme entry
> 2021-08-21 updates

- README.md
Add erfan now that https://github.com/ekm507/erfan-zsh-theme/issues/1 is closed.
> Add erfan theme

- README.md
> Add fzf-pass plugin

- README.md
> Add oblong theme

- README.md
> Add laravelX plugin

- README.md
> Add lamdba-p theme

- README.md
Add hip-fellow. Closes https://github.com/haitaim/hip-fellow/issues/1
> Add hip-fellow theme

- README.md
> Add vterm plugin

- README.md
- Add path-ethic plugin
- Add auto-ls plugin
> Add path-etch and auto-ls

- README.md
- Add cros-auto-notify
- Update PZ description
> Add cros-auto-notify plugin

- README.md
- [xI have stripped leading and trailing **zsh-**, **zsh-plugin** and/or **oh-my-zsh-** substrings from the link name. This makes it easier to find plugins/themes/completions by name by preventing big clusters in the **O** and **Z** sections of the list.
> Add zcomet

- README.md
- Fix sort in frameworks section
- Add shakir-abdo's github plugin
> 2021-09-14 updates

- README.md
- Add link to Mastering ZSH tutorial
> Add Mastering ZSH tutorial

- README.md
- Add radius theme (closes https://github.com/erikcc02/radius-zsh-theme/issues/1)
> Add radius theme

- README.md
- Add bluo theme
- Add zargparse completion generator
> Add bluo and zargparse

- README.md
- Add aws plugin
- Add mirage theme
- Add efibootmgr tab completion
- Add doas plugin
> 2021-09-20 Updates

- README.md
- Add drkat theme
- Add zlitefetch plugin
- Add wkentaro theme
> 2021-09-22 updates

- README.md
- Update broken input.fontbureau.com link
- Update fzf-pass entry
- Add toledo theme
> 2021-09-24 updates

- README.md
- Add `prompt` theme
- Add `window-title` plugin
- Update `windows-title` and `mike-was-here` entries that had urls with  issues in them instead of pointing at repo properly
> Update window_s_-title, add window-title plugin

- README.md
- Add hydrogen theme
- Update handy theme
- Add aramirol's apple theme, disambiguate bjrowlett2's.
> 2021-09-30 Updates

- README.md
- Add packer plugin
- Update mad theme description
- Add skull theme
> 2021-10-05 Updates

- Writing_Plugins.md
Mostly minor wording tweaks to the plugin guide.
> Update guide for writing plugins

- README.md
Add [zsh-bench](https://github.com/romkatv/zsh-bench).
- [x ] This document is covered by the [BSD License](https://github.com/unixorn/awesome-zsh-plugins/blob/master/LICENSE), and I agree to contribute this PR under the terms of the license.
> Add zsh-bench

- README.md
add [aur-install](https://github.com/redxtech/zsh-aur-install).
> add aur-install plugin

- README.md
add [sb-upgrade](https://github.com/redxtech/zsh-sb-upgrade).
> add sb-upgrade plugin

- README.md
add [unix-simple](https://github.com/redxtech/zsh-unix-simple)
> add unix-simple plugin

- README.md
- Add `tig` plugin
- Add `k3d` plugin
- Add `unique-id` plugin
> 2021 november updates

- README.md
Start adding links to mirrors of psprint's 404ed repositories to begin work on https://github.com/unixorn/awesome-zsh-plugins/pull/1332
- Add links to mirrors of declare-zsh, diff-so-fancy, editing-workbench, history-search-multi-word, z-a-bin-gem-node, z-a-meta-plugins, z-a-patch-dl, z-a-rust, z-a-submods, z-a-unscope, zconvey, zflai, and zui
> Add links to mirrors of some of psprint's plugins

- README.md
Add more links to zdharma-continuum mirror of psprint's purged repos to continue work on #1332 
- Add zsh-navigation tools
- z-a-readurl
- z-a-default-ice
- zbrowse
> More mirror links post psprint purge

- README.md
As a french speaker, I couldn't help but notice that "née" is grammatically incorrect. The "e" suffix denotes a feminine noun, which `zinit` is not. Inferring the right gender in this context is always a bit tricky since there is no such context in english. Nevertheless it's safe to say that here there should be no "e" at the end because it's "the zinit project" ie "le projet zinit" (and not "la").
> (French) Grammar

- README.md
- Add [jq (northismirror)](https://github.com/NorthIsMirror/jq-zsh-plugin)
- Disambiguate [jq (reegnz)](https://github.com/reegnz/jq-zsh-plugin)
- Add [package-any-node](https://github.com/zdharma-continuum/zsh-package-any-node) - more psprint cleanup for #1332
> Add another jq plugin

- README.md
> Add spack plugin

- README.md
- Add link to zinit-console mirror, closes #1341 
- Remove Seppuku theme - has gone 404
> Add link to zinit-console mirror

- README.md
> Update URL for k3d plugin

- README.md
> Add link to zshelldoc

- README.md
Add link to the ZSH plugin standard maintained at zdharma-continuum.
> Add link to the ZSH Plugin Standard

- README.md
- Add eivmosn theme now that https://github.com/eivmosn/eivmosn-omz/issues/1 is closed
- TOC update
> Add eivmosn theme

- README.md
- Update zinit-annex links to use the updated repository names in the zdharma-continuum organization
- Fixed sort order in Plugins and Themes sections
> More zdharma-continuum related changes

- README.md
Add svs theme now that it has a screen shot
Closes https://github.com/SvS30/svs-theme/issues/1
> Add svs theme

- README.md
- Add saml2aws tab completion
- Update okta tab completion entry
- Add exa-ls plugin
> 2021-11-21 updates

- README.md
- Add sealion plugin
- Update almel theme
> Thanksgiving 2021

- README.md
- Add tourcoder's simple theme
- Add owi theme
> 2021-11-26 updates

- README.md
> Add newvwp plugin

- README.md
- Add ribbon theme
- Add quer-ps1 theme
> 11-28-2021 updates

- README.md
- Add two different `zellij` plugins
- Add `twilight` theme
- Add `liver` theme
> 2021-11-29 updates

- README.md
Add elm theme. Closes https://github.com/gacallea/elm-zsh-theme/issues/1
> Add elm theme

- README.md
> Add ranger-zoxide theme

- README.md
- Add Yabanahano's `web-search` plugin
- Disambiguate sinetoami's `web-search` plugin
- Add `zprompts` themes
> 2021-12-06 updates

- README.md
Add gk3000 theme, closes https://github.com/gk3000/gk3000-oh-my-zsh-theme/issues/1
> Add gk3000

- README.md
- Update aws plugin and elm theme entries
- Remove 404 `shprompt`
> Update aws plugin and elm theme entries

- README.md
Now that https://github.com/DevJ121/devj121-zsh-theme/issues/1 is closed, add the devj121 theme.
> Add devj121 theme

- README.md
- Add apparix plugin
- devproductivity.io is offline, remove link
> Add apparix plugin

- README.md
Update link to https://github.com/ednikolenko/minima after github user rename
> Update link to ednikoleno's minima theme

- README.md
- A simple and elegant multi-line theme for ZSH. Includes a colourized timestamp, `git` & syntax highlighting, and elevated root theme. 
- [ √ ] Add/remove/update a link to a theme
- [ √ ] This document is covered by the [BSD License](https://github.com/unixorn/awesome-zsh-plugins/blob/master/LICENSE), and I agree to contribute this PR under the terms of the license.
- [ √ ] I have read the [CONTRIBUTING](https://github.com/unixorn/awesome-zsh-plugins/blob/main/Contributing.md) document.
- [ √ ] I have confirmed that the link(s) in my PR are valid.
- [ √ ] My entries are single lines and are in the appropriate (plugins, themes or completions) section, and in alphabetical order in their section.
- [ √ ] All new and existing tests passed.
- [ √ ] Any added themes have a screen shot, a …
> Add Piboy Theme

- README.md
> Add piboy to main branch

- README.md
> Add zsh-defer plugin

- README.md
Add Zebrafish framework
Add Zshzoo plugins:
- https://github.com/zshzoo/cd-ls
- https://github.com/zshzoo/completion-zstyles
- https://github.com/zshzoo/copier
- https://github.com/zshzoo/macos
- https://github.com/zshzoo/magic-enter
- https://github.com/zshzoo/xdg-basedirs
> Add plugins from zshzoo

- README.md
Add `chinipage` theme, closes https://github.com/andresemartinez/chinipage-zsh-theme/issues/1
> Add chinipage theme

- README.md
- Add `omz-standalone-themes` - includes just the themes from omz
- Add `rbenv (ecortinas)` and clean up the various `rbenv` variant entries
> Add omz-standalone-themes and rbenv plugins

- README.md
- Add dagger completion
- Add zcraft theme
> Add dagger and zcraft

- README.md
> Add hometown theme

- README.md
> Add zman plugin

- README.md
- Add hermitmaster's zoxide plugin and disambiguate ajeetdsouza's.
> Add zoxide plugin

- README.md
- Add pecodez theme
- Remove klendathu theme - no license or screen shot
> Happy New Year 2022

- README.md
- Add xavi theme
- Add jeop10's dragon theme.
- Closes https://github.com/onthedock/xavi.zsh-theme/issues/1 and https://github.com/jeop10/dragon/issues/1
> Add dragon and xavi themes

- README.md
https://github.com/masterodie/zsh-theme-odie/issues/1 is closed, add odie theme.
> Add odie theme

- README.md
https://github.com/Talon1024/omz-uncloudium/issues/1 is closed, add uncloudium
> Add uncloudium plugin

- README.md
Add NorthIsMirror/jq-zsh-plugin and disambiguate reegnz's jq
> Add NorthisMirror/jq

- README.md
Add antoinechab theme. Closes https://github.com/antoinechab/antoinechab-theme/issues/1.
> Add antoinechab theme

- README.md
New plugin for the list:) 
Shellfirm is a small plugin written in Rust that prompts you a double verification to your terminal when a risky command pattern is detected.
Visit in GitHub project to get more details 
https://github.com/kaplanelad/shellfirm
> Add shellfirm plugin

- README.md
- Add chill theme
- Add illusion theme
- Add js-magic theme
> 2022-01-12 Update

- README.md
> Add alias plugin

- README.md
- Update chill now that https://github.com/JKerboeuf/chill.zsh-theme/issues/1 is closed
- Remove 404 zoxide plugin
> Update chill entry

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- Add `git-prompt-kit`
- `lunachar` doesn't do `git` decorations - closes https://github.com/unixorn/awesome-zsh-plugins/issues/1407
> Add git-prompt-kit, update lunachar

- README.md
> Sort cleanups

- README.md
- Add `alacritty` plugin
- Add `gitgo` plugin
- Add `koritt` theme
- Add `yindev` theme
> MLK Day updates

- README.md
> Add zodiac theme

- README.md
> Add promptus theme

- README.md
https://github.com/honbey/mzt/issues/1 is closed, add `mzt` theme
> Add mzt theme

- README.md
- Update description of `mzpm` framework
- `morpho` and `github-issues` both went 404, remove
> Update mzpm framework entry

- README.md
- Add `zest` theme now that https://github.com/hash-bang/zsh-theme-zest/issues/1 is closed
- `zsh2000` author changed their GitHub username, update theme link to match
- Add `codex` plugin
> 2022-01-24 updates

- README.md
- Update `starship` prompt entry with link to their website
- Update `nx` completions entry
- Fix formatting in `cod` entry
- Add `lazycomplete` completion
> 2022-01-25 updates

- README.md
- Add `git-fzf` plugin
- Update description for **Ax-ZSH**
- Update `wdnote` description
- Update `duckster` description
- Remove`flowr` - it is 404
> 2022-01-29 Updates

- README.md
- https://github.com/ThemysciraData/conda.plugin.zsh/issues/1 is closed, add `conda` plugin
- https://github.com/ThemysciraData/owczarczak.zsh-theme/issues/1 is closed, add `owczarczak` theme.
- Add `gundam` theme
- Update `illusion` theme entry now that https://github.com/shabane/illusion/issues/1 is closed.
> 2022-02-03 updates

- README.md
The completion script the plugin provides has been upstreamed to https://github.com/blimmer/zsh-aws-vault/pull/21.
Therefore I won't be maintaining the removed one anymore. Any improvements will live on in blimmer's repo.
> Remove deprecated aws-vault plugin

- README.md
The link was a plain fork of the one after it, with no value-add.
> Delete duplicate fork

- README.md
- `gundam` theme is 404, remove
- Add `archcraft` theme
> Remove `gundam` theme, add `archcraft`

- README.md
added [carapace-bin](https://github.com/rsteube/carapace-bin)
> Add carapace-bin

- README.md
> Add powermore prompt

- README.md
- Add `autodark` plugin
- Add `zsh-select` plugin
- Update `zsh-diff-so-fancy` entry
> 2022-02-12

- README.md
Closes https://github.com/unixorn/awesome-zsh-plugins/issues/1339
Thanks for finding the mirror, @ss-o
> Add link to mirror of psprint's redis plugin

- README.md
- https://github.com/chmouel/kubectl-config-switcher/issues/1 is closed, add the plugin.
- Add (and disambiguate) `kubectl-color` plugin.
- `unicorn` theme is 404, remove
> Add `kubectl-config-switcher` and `kubectl-color` plugins

- .github/ISSUE_TEMPLATE/new-link-for-the-list.md
Add an issue template for link submissions
> Update issue templates

- README.md
Add a link to [pnpm](https://pnpm.io/).
> Update pnpm plugin entry

- README.md
> Add iay theme

- README.md
- Add `gardenctl` tab completions
> Add gardenctl tab completions

- README.md
Add new plugin https://github.com/jirutka/zsh-shift-select.
> Add shift-select plugin

- README.md
- Add `zservice-py3http`
- Add `mac-zsh-completions`
- Update `bernkastel` theme entry
> Twosday updates

- README.md
The author of devj121 changed their GitHub username, update link accordingly
> Update devj121 link

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- Add xlshiz's pyenv plugin
- Add unwrap plugin
> Add `pyenv` and `unwrap` plugins

- README.md
- Fix heading for windows `superconsole` entry
- Linkify references in `superconsole` entry
- TOC update
> Update windows section

- README.md
Signed-off-by: angelina-tsuboi <angelina.t1832@gmail.com>
- Add `snowflake` theme
Closes https://github.com/angelina-tsuboi/snowflake-zsh-theme/issues/1#issuecomment-1059312547
> Add snowflake theme

- README.md
- Add `cn` theme
- Update `cmder` theme now that https://github.com/potasiyam/cmder-zsh-theme/issues/2 is closed
> 2022-03-05 Updates

- README.md
PZ was renamed Antidote and is a continuation of Antibody
Zebrafish was deprecated
> Add Antidote plugin manager and remove legacy Zebrafish

- README.md
- Add `kalsowerus` theme
- Add rkitover/sh-prompt-simple theme
> 2022-03-08 updates

- README.md
- Update antibody framework entry to point at https://getantidote.github.io/
- Add ultimator theme
- Add kalsowerus' `bitwarden` plugin
- Disambiguate Game4Move78's `bitwarden` plugin
> Update antibody framework entry

- README.md
- Add nicolodiamante's `gitio` plugin
- Disambiguate denysdovhan's `gitio` plugin
> Add nicolodiamante's gitio plugin

- README.md
- Add [One Key Linux Setup](https://github.com/miracleyoo/one-key-linux-setup) - closes https://github.com/miracleyoo/one-key-linux-setup/issues/1
- Add `temeraf` theme now that https://github.com/filiptoma/temeraf-zsh/issues/1 is closed
- Add `gerry` theme now that https://github.com/GerryLarios/gerry-prompt/issues/1 is closed
> Add One Key Linux Setup

- README.md
- Add [voidy](https://github.com/rwejdling/voidy) theme
> Add voidy theme

- README.md
https://github.com/Elagoht/Elagoht.zsh-theme/issues/1 is closed, add [elagoht](https://github.com/Elagoht/Elagoht.zsh-theme)
> Add elagoht theme

- README.md
- Add `shuttle` theme now that https://github.com/Pandademic/Shuttle/issues/2 is closed.
- Add `yuyuko` theme
- Add pftavares' `terraform` plugin
> St. Patrick's Day update

- README.md
- Add [robbyrussell-plus](https://github.com/jackjyq/robbyrussell-plus-zsh-theme) theme. Closes https://github.com/jackjyq/robbyrussell-plus-zsh-theme/issues/1
- Add [risbow](https://github.com/waddupp00/risbow) theme
> Add robbyrussell-plus and risbow themes

- README.md
- https://github.com/NasirNobin/zsh-valet/issues/1 is closed, add valet plugin.
- Add `octo` tab completion
- Add link to `tinygo` tab completion entry
> 2022-03-20 updates

- README.md
> Add lispy theme

- README.md
- Add `lacrimae` plugin - closes https://github.com/caIamity/lacrimae/issues/1
- Add `dango` and `wormwood` now that https://github.com/ann-kilzer/annkilzer.zsh-theme/issues/1 is closed.
> Add dango, lacrimae and wormwood

- README.md
> Add efritas theme

- README.md
- Add `brisa` theme, closes https://github.com/brisa-dev/oh-my-zsh-brisa-theme/issues/1
- Add `clipper` theme, closes https://github.com/Robert-96/clipper/issues/1
- Add `intheloop` theme now that https://github.com/alionapermes/inthedeepspace/issues/1 is closed.
- https://github.com/linkdevk/link-zsh-theme/issues/1 is closed, add `link` theme.
- https://github.com/sgpthomas/zsh-up-dir/issues/1 is closed, add `up-dir` plugin
> 2022-04-02 updates

- README.md
- Add `refpx` theme
- Update `radius` theme
> Add refpx, update radius theme

- README.md
- Add `wordle` plugin
- https://github.com/Eilaluth/rei/issues/1 is closed, add `rei` theme
- Disambiguate arturoalviar's `rei` theme entry from eilaluth's
> 2022-04-07 updates

- README.md
> Add `zenplash` plugin

- README.md
- Add andres-ortizl's `ortiz` theme
- Disambiguate guezwhoz's `ortiz` theme
> Add andres-ortizl' `ortiz` theme

- README.md
- https://github.com/jkergal/hyperjs-wsl-zsh-powerlevel10k-config-on-windows/issues/1 is closed, add article to OMZ section.
- Add `silverstein-quotes` plugin
- Add `omz-git` plugin
- `biradate` plugin has been renamed to `biratime`, update entry
> 2022-04-12 updates

- README.md
Add link to  **iTerm2 + Oh-My-ZSH: Supercharge Your Mac Terminal** article
> Add iTerm2 + Oh-My-ZSH: Supercharge Your Mac Terminal article

- README.md
Add kubectl-plugin-autocompletion
> Add kubectl-plugin-autocompletion

- README.md
- Add `skaffold` plugin
- Add `fd` plugin
- Update `git-prune` entries
> 2022-04-20 updates

- README.md
- Add `def` plugin
- Add `skill` theme
- Sort cleanups
> 2022-04-24 updates

- README.md
- Add `npm-scripts-autocomplete`
- Add `daily-emoji-theme`
- Add `zshange_directory_recent` plugin
> 2022-04-26 updates

- README.md
- Add `mzpt` theme
- Add `winline` theme
- Add `zshify` theme
- Add `bref` theme
- Add `zen` theme
- Add `git-worktrees` plugin
> 2022-04-30 updates

- README.md
Many minor formatting and wording tweaks in the frameworks section.
> Cleanup the frameworks section

- README.md
> Add `cr` theme

- README.md
Add RaspberryPi4TemperaturePromptPlugin plugin
> Add RaspberryPi4TemperaturePromptPlugin plugin

- README.md
https://github.com/pifabs/pifabs-zsh-theme/issues/1 is closed, add `pifabs` theme
> Add pifabs theme

- README.md
> Add deno plugin.

- README.md
> Mothers' Day 2022

- README.md
Add link to `shtab` completion generator
> Add link to `shtab` completion generator

- README.md
- Update links in `ultimator` theme entry.
- Add `shiftys` theme
- Add `zsh-exa` plugin
> Update `ultimator` entry

- README.md
- Add `arrow` theme
- Add `luceast` theme
> Add arrow and luceast themes

- README.md
> Add link to `git-clean-branch`

- README.md
> Add repo theme

- README.md
- Update `gal` theme entry
- Update `kubectl-plugin` entry
- Update link for `headline` theme
> 2022-05-28 updates

- README.md
- Add `acenoster` theme
- Add `cryo-long` theme
> 2022-05-29 Updates

- README.md
- Add `djkakaroto` theme
- Update `owczarczak` entry
- https://github.com/gembaadvantage/octo-oh-my-zsh is 404, removing
> Add `djkakaroto` theme

- README.md
- https://github.com/adamnorwood/adamnorwood-zsh/issues/1 is closed, add Adam's bare ZSH setup.
- Update link to `quotify` plugin
> Add Adam Norwood's ZSH setup

- README.md
- Add `ivabus` theme
- Add `gugulnok` theme. Closes https://github.com/gugulen0k/gugulenok/issues/1
> Add `gugulnok` and `ivabus` themes

- README.md
`hedgehog` theme is 404, removing
> Remove hedgehog theme

- README.md
https://github.com/gaojunbin/zsh-myincr/issues/1 is closed, add `myincr`.
> Add `myincr` completion plugin

- README.md
- Add `fastcache` plugin
- Update url for `link` theme
> Add `fastcache` plugin

- README.md
https://github.com/RubixDev/zish/issues/1 is closed, adding `zish`.
> Add `zish` theme

- README.md
https://github.com/jimratliff/yellow-sea-diamonds-zsh-theme/issues/1 is closed, add yellow-sea-diamonds theme.
> Add `yellow-sea-diamonds` theme

- README.md
- Update URL for `git-sync` plugin
- Add `smartcache` plugin
- Add `fzshell` tab completion plugin
> 2022-06-15 Updates

- README.md
Move `fzshell` entry to completions section
> Move fzshell entry to completions section

- README.md
- Add `gazelle` now that https://github.com/mfurkanndemir/gazelle/issues/1 is closed
- Update `base16` entry
> 2022-06-30 updates

- README.md
- Add `doom` theme now that https://github.com/CMOISDEAD/doom-zsh/issues/1 is closed.
- https://github.com/none9632/zsh-sudo/issues/1 is closed, add `sudo` plugin
> Add `sudo` plugin and `doom` theme

- README.md
I've changed my username, so the the link to ribbon's repo has changed from https://github.com/tactlessfish/ribbon-prompt to https://github.com/pyjamafish/ribbon-prompt.
This PR updates the link in README.md.
> Update link to ribbon repository

- README.md
> Add snazzy theme

- README.md
> Update `remolueoend` entry

- README.md
Add casonadams' skim plugin and disambiguate hackerchai's.
> Add casonadams' skim plugin

- README.md
Many minor edits to theme entries.
> 2022-07-03 theme entry updates

- README.md
chriskempson/base16-shell is 404, remove
> chriskempson/base16-shell is 404, remove

- README.md
In general, this is a revert of 3f3f2ceb4fd13c22c5803144a7ab75fe6bcb857f, but with an updated link.
This adds back base16, linked to in the new org we've been working on for about a month.
> Add base16 back under the new org

- README.md
- Update `kubectl-plugin` description
> Update kubectl-plugin description

- README.md
This PR adds my own plugin, [zpy](https://github.com/AndydeCleyre/zpy), to the list.
It's a ZSH frontend to Python environment and dependency operations, mostly wrapping [pip-tools](https://github.com/jazzband/pip-tools).
> Add andydecleyre/zpy plugin

- README.md
- Fix typo in `fuzzy-wd` entry
- Add `gimbo-git` plugin
> 2022-07-08 updates

- README.md
https://github.com/Saeed-MFarahani/Neo-ZSH-Theme/issues/1 is closed, add `neo` theme.
> Add `neo` theme

- README.md
- Clean up plugins entries - add links, tweak wording, fix spelling mistakes, etc.
- `zeit` was mistakenly added to the plugins section, moved to themes section.
> Clean up the plugins section

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- Add `tgenv` plugin
- Remove `lispy` theme - it is 404
> Add `tgenv` plugin

- .github/ISSUE_TEMPLATE/new-link-for-the-list.md
- README.md
- Update issue template
- Add `bearings` theme now that https://github.com/liamg/bearings/issues/10 is closed
- Text updates in plugins section
> 2022-07-21 updates

- README.md
- Upstream added screen shots, add `vehemence` theme. Closes https://github.com/H1N1-dev/vehemence-zsh/issues/1
- Remove `betterbrew` plugin that has gone 404
> Add `vehemence` theme, remove `betterbrew` plugin

- README.md
- Add sudosubin/zsh-pipenv
- Disambiguate owenstranathan/pipenv.zsh
> Add sudosubin's pipenv plugin

- README.md
> Add ranger-autojump plugin

- README.md
https://github.com/jnooree/jnooree-zsh-theme/issues/1 is closed, add `jnooree` theme
> Add `jnooree` theme

- README.md
Update `jq` plugin description to include its `gojq` support and `fzf` dependency
> Update `jq` entry

- README.md
> Add `pyhack` theme

- README.md
- Update `shellfirm` entry
- Add `pipx` tab completion
- Add `odra` theme
> 2022-08-06 updates

- README.md
- Add zchee/zsh-completions
- Add clarketm/zsh-completions
- Add nilsonholger/osx-zsh-completions
> Add more completions

- README.md
- Add akash329d/zsh-alias-finder
- Add danielparks/danielparks-zsh-theme now that https://github.com/danielparks/danielparks-zsh-theme/issues/1 is closed
- Update fzshell description
> 2022-08-07 updates

- README.md
Add mattmc3/zsh-xdg-basedir plugin
> Add mattmc3/zsh-xdg-basedir plugin

- README.md
- Add aubreypwd/zsh-plugin-cvideo
- Add aubreypwd/zsh-plugin-download
- Add aubreypwd/zsh-plugin-require
> Add entries for aubreypwd's plugins

- README.md
- Update a couple `fzf` references in descriptions
- https://github.com/dinizgab/zskai-theme/issues/1 is closed, add `dinizgab/zskai-theme`
- Add `kraklin/elm.plugin.zsh` tab completion
> Minor description updates

- README.md
https://github.com/git-girl/pseudo-projectile-plugin/issues/6 is closed, add git-girl/pseudo-projectile-plugin
> add git-girl/pseudo-projectile-plugin

- README.md
- https://github.com/LeonardMH/born-in-the-purple/issues/1 is closed, add `LeonardMH/born-in-the-purple`.
- Add `Ryooooooga/qwy`
-
> Add `LeonardMH/born-in-the-purple` theme

- README.md
- Add `justforuse/nanika-zsh-theme` theme
- Add `Elagoht/BashPlusZshTheme` theme
> 2022-08-02 Updates

- README.md
- Add `Junker/zsh-archlinux` plugin
> Add Junker/zsh-archlinux

- README.md
https://github.com/ketlrznt/ketlrznt.zsh-theme/issues/1 is closed, add `ktlrznt/ketlrznt`
> Add `ketlrznt/ketlrznt`

- README.md
> Update Symfony plugins

- README.md
- Update `chenhao-ye/thyme`
- Update `florentinl/openstack-zsh-plugin`
> 2022-09-12 updates

- README.md
- Add `cravend/theme` as `cravend` (closes https://github.com/cravend/theme/issues/1)
- Add `cravend/autodark` plugin
> Add cravend theme and autodark plugin

- README.md
- Add DrgnFireYellow/notenote now that https://github.com/DrgnFireYellow/notenote/issues/1 is closed
- Add salamantos/zoo_sh now that https://github.com/salamantos/zoo_sh/issues/1is closed.
> 2022-09-14 updates

- README.md
Signed-off-by: Dmitry Tikhov <ddtikhov@gmail.com>
Hi, I made zsh plugin to ease archiving. Haven't found anything working on GitHub like it, so it may be useful to add it to this list.
> Add 0xRZ/mkarch

- Writing_Plugins_and_Themes.md
Add example of only defining functions if the supporting program is present.
> Recommend only defining aliases/functions when usable

- README.md
> Add zlugin plugin manager

- README.md
Add `mfurkanndemir/gazelle` theme
> Add `mfurkanndemir/gazelle` theme

- README.md
> zpwr - update counts

- README.md
Add `treyssatvincent/carriage-return.zsh-theme` now that https://github.com/treyssatvincent/carriage-return.zsh-theme/issues/1 is closed
> Add `treyssatvincent/carriage-return.zsh-theme`

- README.md
- Add `huboles/zshmux` plugin
- Fix accumulated sort mistakes in plugins, themes and completions sections
> Add `huboles/zshmux` plugin

- README.md
- Add `iamkirkbater/spaceship-ocm-plugin` for spaceship prompt
- Add `juliavallina/windows-zsh-theme` - closes https://github.com/juliavallina/windows-zsh-theme/issues/2
- Update `zgen` install instructions
- Add Amar Pan's ZSH on Ubuntu article
> 2022-09-28 updates

- README.md
- Add `remino/omz-plugin-mysql-alias` plugin
- Add `remino/omz-plugin-git-aliases` plugin
> 2022-09-29 updates

- README.md
- https://github.com/victoria-riley-barnett/Communism/issues/1 is closed, add `victoria-riley-barnett/Communism` plugin
> Add `victoria-riley-barnett/Communism` plugin

- README.md
- rename `pentesters`  to `lpha3cho`
- Add  `paroape/pareoape-zsh-theme`
> 2022-10-03 updates

- README.md
Adding [fd-zsh](https://github.com/MohamedElashri/fd-zsh) aliases plugin to the list of plugin
I released a new zsh plugin that provide some aliases for the tool [fd](https://github.com/sharkdp/fd) and it might be good addition to this list. 
[fd-zsh](https://github.com/MohamedElashri/fd-zsh)
- [] Any added completions have a readme and a license file in their repository.
- [] Any added frameworks have a readme and a license file in their repository.
> Add fd-zsh aliases plugin

- README.md
- Add `oliver-svrcek/Themeraf` theme
> Add `oliver-svrcek/Themeraf` theme

- README.md
> Add `shougo/ddc` completion

- README.md
- Update `dangerroom` entry
- Add `LFabre/zsh-git-prompt-enhanced` plugin
> cake day updates

- README.md
- https://github.com/HFMorais/oh-my-zsh-purpleblood-theme/issues/1 is closed, add `FMorais/oh-my-zsh-purpleblood-theme`
> Add `FMorais/oh-my-zsh-purpleblood-theme`

- README.md
Call out `zgenom` as the recommended ZSH framework.
> Call out `zgenom` as the recommended ZSH framework.

- README.md
> Update `znvm` plugin entry

- README.md
> Add senv plugin

- README.md
- https://github.com/eddieantonio/gitbash-zsh-theme/issues/1 is closed, add `eddieantonio/gitbash-zsh-theme` theme
- `mfurkanndemir/gazelle` is 404, remove
> Add `eddieantonio/gitbash-zsh-theme` theme

- README.md
- Disambiguate `ssh` completion plugins
- Correct `lets-cli` name
> 2022-10-12 updates

- README.md
- Add `TwoPizza9621536/zsh-plenv` plugin
- Add `TwoPizza9621536/zsh-pyenv` plugin
> 2022-10-15 updates

- README.md
Add a contributor mugshot image
> Add a contributor mugshot image

- README.md
- Add `voidzero/omz-plugin-psgrep` - closes https://github.com/voidzero/omz-plugin-psgrep/issues/1
- Remove `ketlrznt/ketlrznt.zsh-theme` is 404, remove
> Add `voidzero/omz-plugin-psgrep`

- README.md
- Update entry for `xwmx/astral`
- Update entry for `normanius/normanius-zsh-theme`
- Add `Akollade/symfony.plugin.zsh` tab completion.
> 2022-10-23 updates

- README.md
- Add `saravanabalagi/zsh-plugin-singularityenv` plugin
- Remove 404 `Vesdii/zsh-wdnote` - `Vesdii` GitHub account no longer exists.
> Add `saravanabalagi/zsh-plugin-singularityenv`

- README.md
- https://github.com/PhoenixSmaug/zsh-lgbtq-themes/issues/1 is closed, add lgbtq themes
> 2022-11-1 updates

- README.md
https://github.com/SoYoureAWaffleMan/xandermute-oh-my-zsh-theme/issues/1 is closed, add `SoYoureAWaffleMan/xandermute-oh-my-zsh-theme`
> Add `SoYoureAWaffleMan/xandermute-oh-my-zsh-theme`

- README.md
- Add `clavelm/yt-dlp-omz-plugin` tab completion for [yt-dlp](https://github.com/yt-dlp/yt-dlp)
- Add `Ivan-Kuzmichev/air` theme
> 2022-11-05 updates

- README.md
- Add `lexhuismans/happy-coding` theme. Closes https://github.com/lexhuismans/happy-coding/issues/1
- Add `sheoak/zsh-bepoptimist` plugin now that https://github.com/sheoak/zsh-bepoptimist/issues/1 is closed
> 2022 updates

- README.md
- Add bat `fdellwing/zsh-bat` plugin, closes https://github.com/unixorn/awesome-zsh-plugins/issues/1628
- Add `warshanks/funkydrac` now that https://github.com/warshanks/funkydrac/issues/1 is closed
> 2022-11-09 updates

- README.md
The tab completion "symfony (Akollade)" replace "symfony (TheGrowingPlant)".
> symfony (Akollade) replace symfony (TheGrowingPlant)

- README.md
Add `BuonOmo/yarn-extra-completion` tab completion
> Add `BuonOmo/yarn-extra-completion` tab completion

- README.md
- Dedupe `shrug` theme entries and update URL with the author's new GitHub username
- https://github.com/Hdoc1509/shell-fns/issues/1 is closed, add `Hdoc1509/shell-fns` plugin
- Add entry for `zap-zsh/zap` framework
> 2022-11-12 updates

- README.md
- Add `mvinan/malev-zsh-theme`
- Add `easytocloud/oh-my-easytocloud`
- Update `bashplus` entry
- Add `zap-zsh/fnm` tab completions
> 2022-11-18 updates

- README.md
> Added cycle-fav-dirs plugin

- README.md
- Sort fixes and minor text updates
- https://github.com/meganerd/meganerd-zsh/issues/1 is closed, add `meganerd/meganerd-zsh` theme
> 2022-11-19 Updates

- README.md
- https://github.com/OtterArkar/otter-zsh/issues/1 is closed, add `otter` theme
- Add `gh05t-4/pwn-theme`, closes https://github.com/gh05t-4/pwn-theme/issues/1
> 2022-11-25 updates

- README.md
- Update mvinan/malev-zsh-theme, https://github.com/mvinan/malev-zsh-theme/issues/1 is closed
- https://github.com/fesmjke/escape/issues/1 is closed, add `escape` theme
> 2022-12-04 updates

- README.md
https://github.com/alesrosina/oh-my-zsh-alesrosina-theme/issues/1 is closed, add `alesrosina/oh-my-zsh-alesrosina-theme`
> Add `alesrosina/oh-my-zsh-alesrosina-theme`

- README.md
- Update `jdk-switch` plugin entry
- Add `pog7x/pog7x-zsh-theme`
Now supports Linux, too.
> 2022-12-08 updates

- README.md
- Add `xdigu/zsh-vtex` plugin
- https://github.com/parwatcodes/random-emoji-robbyrussell/issues/2 is closed, update `parwatcodes/random-emoji-robbyrussell` theme
- Add and disambiguate `Leizhenpeng/zsh-plugin-pnpm`
> 2022-12-10 updates

- README.md
- Add `magidc/fzf-copyq-clipboard-zsh-plugin` that adds support for [CopyQ](https://hluk.github.io/CopyQ/)
- https://github.com/gynamics/zsh-gitneko/issues/1 is closed, add `gynamics/zsh-gitneko`
> 2022-12-14 Updates

- README.md
- Update `zsh-pyenv`
- Add `aguiar-us/aguiar.zsh-theme`
> 2022-12-16 updates

- README.md
- Add `chiemerieezechukwu/aws-zsh-theme`
- https://github.com/PicoGeyer/zsh-pico-prompt/issues/1 is closed, add `PicoGeyer/zsh-pico-prompt`
> 2022-12-19 updates

- README.md
https://github.com/Lissy93/minimal-terminal-prompt/issues/2 is closed, add `Lissy93/minimal-terminal-prompt`
> Add `Lissy93/minimal-terminal-prompt`

- README.md
- Add `wintermi/zsh-gcloud`, disambiguate `littleq0903/gcloud-zsh-completion`
- Add `wintermi/zsh-golang` plugin
- Add `wintermi/zsh-rust` plugin
> Add wintermi plugins

- README.md
- Add `Kimitzuni/australis-theme`
- Fix bad label in `rust (cowboyd)` entry
> Add australis, update rust entry

- README.md
- Add `Atlas34/fzf-plugin` plugin
- Add `zshPlug` plugin manager
- Add `apalkk/Cmaker` plugin
- Add `mubinben/purr-zsh-theme` theme
> 2023-01-07 Updates

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- Update PR Template
- Add zsh.ai framework
> 2023-01-09 Updates

- README.md
Add `wintermi/zsh-starship` theme
> Add `wintermi/zsh-starship`

- README.md
- Add `Pilaton/OhMyZsh-full-autoupdate` - updates oh-my-zsh extra plugins and/or themes
> Add `Pilaton/OhMyZsh-full-autoupdate`

- README.md
- Add `akgarhwal/ez-cmd` plugin
- Update `wintermi/zsh-gcloud` entry with link to the CLI
- Add `rwwiv/multi-evalcache` plugin
> 2023-01-22 updates

- README.md
- `mroth/evalcache` has a license now, update entry. Closes https://github.com/mroth/evalcache/issues/7
> Update `mroth/evalcache` entry

- README.md
Add plugin for better pnpm aliases, as the existing ones are lacking in some aspects
[pnpm (mat2ja)](https://github.com/mat2ja/pnpm.plugin.zsh)
Idk how to signoff via GitHub, and I can't be bothered right now
> Add yet another pnpm aliases

- README.md
- https://github.com/SetOfAllSets/simply-perfect-zsh-theme/issues/1 is closed, add `SetOfAllSets/simply-perfect-zsh-theme`
- Update `conda-incubator/conda-zsh-completion` to include a link to [conda.pydata.org](http://conda.pydata.org/)
> 2023-02-01 updates

- README.md
- Add `unixorn/dietpi.plugin.zsh` plugin
- Add `baliestri/laravel.plugin.zsh` plugin
- Add `baliestri/adonisjs.plugin.zsh` plugin
- Disambiguate `crazybooot/laravel-zsh-plugin` entry
- `baliestri/git-multiuser.plugin.zsh` was renamed to `baliestri/git-extra-profiles.plugin.zsh`, update link
> 2023-02-06 Updates

- README.md
> Add jonscheiding/zsh-plugin-aws-vault-profiles

- README.md
- Add `hogbal/hogbal.zsh-theme`. Closes https://github.com/hogbal/hogbal.zsh-theme/issues/1.
> Add `hogbal/hogbal.zsh-theme`.

- README.md
Add Prerequisites section with links for finding Powerline-compatible and Nerd Fonts.
> Add Prerequisites section

- README.md
> Formatting cleanups in readme

- README.md
Adds my brand new plugin, [zshrpg](https://gtihub.com/aliervo/zshrpg) to the list.
It's currently in the Z section because I named it `zshrpg`, but I could also just link it under `rpg` if that is preferable.
This is my first time signing off a commit, please let me know if I screwed it up.
> Add `Aliervo/zshrpg`

- README.md
- `gusrylmubarok/gusrylmubarok-zsh-theme` is 404, remove
- Add `juliuscaesar/unicorn` theme
> 2023-02-24 updates

- README.md
- https://github.com/miccou/sensa-theme/issues/1 is closed, add `miccou/sensa-theme`
> Add `miccou/sensa-theme`

- README.md
> Added zypper-short plugin

- README.md
- Update `mmatongo/toledo` theme entry with list of supported shells.
- Add `mys721tx/set_path` plugin
> Add `setpath` and update `toledo`

- README.md
- Remove 404 `my-hl2` theme
- Remove 404 `dirkk/zsh-basex` plugin
- https://github.com/aofxta/aofxta.zsh-theme/issues/1 is closed, add `aofxta/aofxta.zsh-theme`
- Add `logik93/rkj-logik.zsh-theme`. Closes https://github.com/logik93/rkj-logik.zsh-theme/issues/1
- Update `zpico` description
- Add `zimfw/asdf` plugin
- Add `mehalter/zsh-pins` plugin
- Add `flameleo11/avoleo-zsh-theme`
> 2023-03-12 updates

- README.md
Add `cybensis/cybensis-zsh-theme`. Closes https://github.com/cybensis/cybensis-zsh-theme/issues/1
> Add `cybensis/cybensis-zsh-theme`

- README.md
- Add `Michaelwmx/zsh-ask` plugin
- Add `timhilton/userandnode` theme now that https://github.com/timhilton/userandnode/issues/1 is closed
> 2023-03-16 updates

- README.md
- https://github.com/mfulz/zsh-penmux/issues/1 is closed, add `mfulz/zsh-penmux`
- Add `z-shell/zsh-lsd` and disambiguate `wintermi/zsh-lsd`
> 2023-03-18 updates

- README.md
- Add `Ryooooooga/croque` theme now that https://github.com/Ryooooooga/croque/issues/1 is closed.
- Add `dann254/mantis-zsh-theme`
> The Enterprise update :-)

- README.md
Add `BastionAtackDev/Warm-Colours` theme
Closes https://github.com/BastionAtackDev/Warm-Colours.zsh-theme/issues/1
> Add `BastionAtackDev/Warm-Colours.zsh-theme`

- README.md
Lux supports iTerm2 and VS Code out of the box, update entry accordingly.
> Update lux entry

- README.md
https://github.com/evgenygorchakov/oh-my-zsh-gorchak-theme/issues/1 is closed, add `evgenygorchakov/oh-my-zsh-gorchak-theme`
> Add `evgenygorchakov/oh-my-zsh-gorchak-theme`

- README.md
- Update `nodo` entry
- Add `AmyangXYZ/zhiyin` theme
> 2023-04-28 updates

- README.md
Add `goarano/zsh-fzf-packagemanager` now that https://github.com/goarano/zsh-fzf-packagemanager/issues/1 is closed
> Add `goarano/zsh-fzf-packagemanager`

- README.md
- Add `pipe-felipe/zsh-pipe-plugin` now that https://github.com/pipe-felipe/zsh-pipe-plugin/issues/2 is closed.
- Add `Hzbeta/omt-manager` plugin
- Add `goarano/zsh-lazy-load` plugin
- Add `nullxception/roundy` theme
- Update `Elagoht/Elagoht.zsh-theme`
> 2023-05-01

- README.md
- Add `jandamm/zgenom-ext-eval` now that https://github.com/jandamm/zgenom-ext-eval/issues/1 is closed.
- Add `mubinben/purr-zsh-theme`
> 2023-05-05 updates

- README.md
- Add `MefitHp/alias-maker` plugin now that https://github.com/MefitHp/alias-maker/issues/1 is closed.
- Add `Domanowska/zshSailorMoonThemes` collection of themes. Closes https://github.com/Domanowska/zshSailorMoonThemes/issues/1
> Add `alias-maker` and `sailormoon` themes

- README.md
- Add `Freed-Wu/zsh-completions-for-cross-compilers` tab completions.
- Add `commiyou/conda-init-zsh-plugin` now that https://github.com/commiyou/conda-init-zsh-plugin/issues/1 is closed
- Add `Dofoerix/Dfrx-Prompt-Theme` now that https://github.com/Dofoerix/Dfrx-Prompt-Theme/issues/1 is closed
- Add Anant-mishra1729/web-search plugin - closes https://github.com/Anant-mishra1729/web-search/issues/1
> 2023-05-11 updates

- README.md
- Add `wintermi/zsh-fnm` plugin, disambiguate `dominik-schwabe/zsh-fnm`.
- Add `wintermi/zsh-bob` plugin
- Add `ryanccn/vivid-zsh` plugin
- Add `fourdim/zsh-poetry` tab completions for [poetry](https://python-poetry.org/)
- Add `fourdim/zsh-archlinux` plugin, disambiguate `Junker/zsh-archlinux`
- Add `renanborgez/ohmyzsh-theme-renanborgez` theme
- Add `firefoxic/firefoxic-zsh-theme`. Closes https://github.com/firefoxic/firefoxic-zsh-theme/issues/1
- `dimitardimitrov/radium` and `omBratteng/zsh-plugin-pipx` are both 404, remove.
> 2023-05-17

- README.md
- Add `git-girl/git-check` plugin, deprecate `git-girl/pseudo-projectile`. Closes https://github.com/unixorn/awesome-zsh-plugins/issues/1719.
- Add `zshzoo/iwd` plugin
> Add `git-girl/git-check` and `zshzoo/iwd`

- README.md
- Update `ChesterYue/ohmyzsh-theme-passion` entry
- Add `BuddhaDom/zsh-buddha` theme
> 2023-05-20 updates

- README.md
- Add `fourdim/zsh-pack` plugin
- Add `Vu0811/bashlover` theme
> 2023-05-22 updates

- README.md
- Add `TomfromBerlin/zsh-cmd-time` plugin.
> Add `TomfromBerlin/zsh-cmd-time`

- README.md
- Add `gakimball/zsh-coffee-time` plugin
- Add `antonjs/zsh-gpt` plugin
- Add `gakimball/zsh-macos-theme` plugin.
> 2023-05-29 updates

- README.md
- Update `fresh` framework entry
- Add `luisprgr/zsh-show-git-user` plugin
- Add `florentinl/omz-wsl` plugin
> 2023-06-06 updates

- README.md
- `brisa-dev/oh-my-zsh-brisa-theme` moved to `ambrisolla/oh-my-zsh-brisa-theme`, update entry
- Add `skippyr/astral` theme, disambiguate `xwmx/astral`
- Add `sharif3271/git-gen` plugin
> 2023-06-17 updates

- README.md
- Add `skippyr/outer_space` theme
- Add `skippyr/chinatown` theme
- `rozNum/roz-zsh-theme` is 404, remove
> 2023-06-19 updates

- README.md
- Add `joje6/joje.zsh-theme` theme
- `rogeliosamuel621` changed username to `sam-621`, update url for `sam-621/rs-zsh-theme`.
> 2023-06-21 updates

- README.md
- Add `rafa-wine/monsi_oh-my-zsh_theme`, closes https://github.com/rafa-wine/monsi_oh-my-zsh_theme/issues/1
- Add `troykelly/oh-my-zsh-opera-gx` plugin
> 2023-06-24 updates

- README.md
- Add `happycod3r/fzf-tools` plugin
- Add `Warbacon/zunder-prompt` theme
> 2023-07-02 updates

- README.md
- Add `hooay233/Hoozeeth` theme now that https://github.com/hooay233/Hoozeeth/issues/1 and https://github.com/hooay233/Hoozeeth/issues/2 are closed
- Update Nerd Fonts references to links
- Sort fixups
> 2023-07-09 updates

- README.md
- Add `skippyr/checkmate` theme
- Add `zpm-zsh/pr-user` plugin
> 2023-08-04 updates

- README.md
- Add `kusamaxi/chaos-zsh` theme
- Add `ITAxReal/xbira` theme now that https://github.com/ITAxReal/xbira/issues/1 is closed
> 2023-08-05 updates

- README.md
- Add `jkcdarunday/zplug-blame` plugin for [zplug](https://github.com/zplug/zplug)
- Update `skippyr/nostalgia` theme entry
- Update `jtyr/gbt` theme entry
> 2023-08-07 updates

- README.md
- Format tweak in `nicolodiamante/nodo` plugin entry.
- Add hotlink to [zsh-rbenv](https://github.com/Meroje/zsh-rbenv) in `mattberther/zsh-nodenv` entry
- Format tweak in `andyrichardson/zsh-node-path` entry
> 2023-08-23 updates

- README.md
I debated whether add this given that the author previously pulled his work from github, but decided in the end that noting that in the framework description was adequate warning to end users.
Given that:
- Evernote has broken a lot of functionality since they moved away from a truly native app
- https://github.com/vitalyrodnenko/geeknote is not under maintenance (probably because of the Evernote fuckery above)
- geeknote.me is offline
I am removing the whole entry and not merely the link to geeknote.me.
@s7anley, I'm open to reinstating it if it's still working with Evernote - I gave up on Evernote a while back and moved to obsidian, so I can't test for myself any more.
> Add zinit-4 framework

- README.md
I referenced a gitlab repo about my zsh-theme.
As the title implies.
> Added a new Neo zsh theme.

- README.md
- Remove `mzpm` framework
- Add `aifrim/aifrim.zsh-theme` theme
> 2023-09-03 updates

- README.md
Add `ArtixLabs/deer` framework.
> Add `deer` framework

- README.md
- https://github.com/lperezp/lperezp-zsh-theme/issues/1 is closed, add `lperezp/lperezp-zsh-theme` theme
- Add `z-shell/zsh-eza` plugin
- Add `clavelm/eza-omz-plugin` plugin.
- Add `yzsh` framework
> 2023-09-16 update

- README.md
- https://github.com/tharindu899/x-theme/issues/1 is closed, add x theme
- Add `sussynuggetz/sussysh-zsh` theme
> 2023-09-30 updates

- README.md
This improves the consistency of the style of entries in this Awesome list. Notably, it:
- Places `-` bullets are after entries that were previously missing
- "github", "gitlab", and "nodejs" have been changed to be consistent (GitHub, GitLab, Node.js) (these names are also consistent with other awesome-lists as verified by [awesome-lint](https://github.com/sindresorhus/awesome-lint))
- Remove the few smart quotes that existed
- Uses shorter, cleaner (and official) links to awesome repository and badge
- Other small fixes
> readme: Improve style consistency

- README.md
Closes #1781 (more information in the linked issue)
> Remove `angry-fly-zsh`

- README.md
Closes #1783 (more information in linked issue)
> Remove link to `phpenv.plugin.zsh`

- README.md
- Add `DuckzCantFly/zsh-dot-plugin` framework
- Add `Akollade/php-version-switcher.plugin.zsh` plugin
> 2023-10-12 updates

- README.md
Closes #1786 (more information in the linked issue)
- [] Add/remove/update a link to a plugin
- [] Add/remove/update a link to a theme
> Remove entry for `tzpm`

- README.md
> Remove broken link for alias-snippet-toolkit

- README.md
- Add `Freed-Wu/zsh-colorize-functions` plugin
- Add `lmllrjr/backbone-zsh-prompt` theme
- Add `egorlem/ultima.zsh-theme` theme
> 2023-10-22 updates

- README.md
> Add `mollifier/zload`

- README.md
- Removed exa plugins that have been deprecated
- Adds new exa plugins that also support eza
> Refresh 'exa' section

- README.md
- Add `twopizza9621536/zsh-eza` plugin
- `ya0201/qwer-ps1` is 404, remove
- `aaronjamesyoung/aaron-zsh-theme` is 404, remove
- https://github.com/daviludvig/ludvig-theme-zsh/issues/1 is closed, update `daviludvig/ludvig-theme-zsh`
> 2023-11-12 updates

- README.md
- Add `roskatom/dir-alert` plugin
- Add `xPMo/zsh-prompt-dir-perms` plugin
- Add `pseifer/s1ck3r` theme
> 2023-11-19 updates

- README.md
> feat(themes): add promptly zsh theme

- README.md
- Add `Lloyd-Leo/parrot-htb-zsh-theme` theme. Closes https://github.com/Lloyd-Leo/parrot-htb-zsh-theme/issues/1
- `Saeed-MFarahani/Neo-ZSH-Theme` is 404, remove
> 2023 Christmas Eve updates

- README.md
> add dvir-levy/terminal-aliases

- README.md
> 2023-12-26 updates

- README.md
Update `cdubos-fr/gallifrey-war` theme to add the missing link to gallifrey theme
> Update `cdubos-fr/gallifrey-war` theme

- README.md
- Add `danieltodor/blaze` theme
- Update `daotoyi/dyzsh-zsh-theme` theme entry
- https://github.com/RizkiIqbal02/zsh-theme-custom/issues/1 is closed, add `RizkiIqbal02/zsh-theme-custom` theme
> 2024-01-05 updates

- README.md
Add `UlyssesZh/ulyssesys` theme now that https://github.com/UlyssesZh/ulyssesys/issues/1 is closed
> Add `UlyssesZh/ulyssesys` theme

- README.md
* pacmandoh/omz-theme-pacmandoh#1 is closed add `pacmandoh/omz-theme-pacmandoh` theme
Add pacmandoh/omz-theme-pacmandoh theme
> Add pacmandoh/omz-theme-pacmandoh theme

- README.md
- Update last commit badge
- Add `wintermi/zsh-mise` plugin
> 2024-01-11 updates

- README.md
- Update `pacmandoh/omz-theme-pacmandoh` theme description.
- Add `duggum/zeza` plugin for [eza](https://github.com/eza-community/eza)
> 2024-01-15 updates

- README.md
- https://github.com/KSposh/ksposh-zsh-theme/issues/4 is closed, add KSposh/ksposh-zsh-theme
- Add `Razzaghnoori/Sailor` plugin now that https://github.com/Razzaghnoori/Sailor/issues/1 is closed
> 2024-01-19 updates

- README.md
- Add `devadathanmb/zap-robbyrussell` theme
- Add `josephcourtney/hypnosnek` plugin
> 2024-01-25 updates

- README.md
- `phantomk/phantomk.zsh-theme` is 404, remove
- Add `joknarf/selector` plugin
- Add `joknarf/cdhist` plugin
- Add `joknarf/redo` plugin now that https://github.com/joknarf/redo/issues/3 is closed.
- Add `yngc0der/zsh-ssh-config-suggestions` ZSH completion
> 2024-01-27 updates

- README.md
The PR adds a zsh extension that I created for eza aliases. It is a fork (with more aliases) of my previous plugin [exa-zsh](https://github.com/MohamedElashri/exa-zsh) which is in this list already. But since exa is deprecated and eza is taking over, it is useful to move to eza.
> Add eza-zsh plugin by MohamedElashri

- .github/workflows/awesomebot.yml
- README.md
- Run awesomebot daily to find 404 links more quickly
- Add `mountaineerbr/shellChatGPT` plugin
> 2024-02-09 updates

- README.md
https://github.com/Goldeneye128/goldenprompt/issues/1 is closed, add `Goldeneye128/goldenprompt` theme
> Add `Goldeneye128/goldenprompt` theme

- README.md
- Add `simonmader17/sashimi-zsh-theme` theme
- Add `RusMephist/talosctl-zsh-plugin` tab completions
> 2024-02-24 updates

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Add `ichirei/ichirei.zsh-theme` now that https://github.com/ichirei/ichirei.zsh-theme/issues/1 is closed
> Add `ichirei/ichirei.zsh-theme`

- README.md
- `A-delta/zsh-airpods-battery` is now `louis-thevenet/zsh-airpods-battery`, update zsh-airpods-battery plugin entry accordingly
- Add `nimacpp/themes-zsh`, closes https://github.com/nimacpp/themes-zsh/issues/1
- Add `Savecoders/Savior-zsh-theme`. Closes https://github.com/Savecoders/Savior-zsh-theme/issues/1
- Add `sbfkcel/oh-my-zsh-theme` theme. Closes https://github.com/sbfkcel/oh-my-zsh-theme/issues/1
> ∏ day updates

- README.md
- Add `vvvvv/bgnoster.zsh-theme` theme.
- Clean up themes section
> 2024-03-16 update

- README.md
- Add `p1r473/zsh-color-logging` plugin. Closes https://github.com/unixorn/awesome-zsh-plugins/issues/1864
- Add `Skylor-Tang/zshrc-sync` plugin
> May the 4th be with you!

- README.md
Description
- Add `Diogo13Antunes/Get_To_Work` theme
- `primait/docker-enter-completion` is 404, remove
- Add `p1r473/zsh-hist-delete-fzf/`. Closes https://github.com/unixorn/awesome-zsh-plugins/issues/1868.
- Add `gambardellawill/cezshanne` theme now that https://github.com/gambardellawill/cezshanne/issues/1 is closed.
- Add `hwk929/zsh-fzf` now that https://github.com/hwk929/zsh-fzf/issues/1 is closed.
> 2024-05-16 updates

- README.md
- Add `arzezak/pronto` theme now that https://github.com/arzezak/pronto/issues/1 is closed.
- Add `Yttehs-HDX/zsh-zpacman` completion. Closes https://github.com/Yttehs-HDX/zsh-zpacman/issues/1
- Add `joknarf/cdhist` plugin
> 2024-05-30 Updates

- README.md
- Add `MrRedacted/zsh-themer` theme
- Add `nkurata/zsh-theme` now that https://github.com/nkurata/zsh-theme/issues/1 is closed
> 2024-06-02 updates

- README.md
- Add `anotherlusitano/moon-light` theme
- Add link to _Profiling ZSH_ article
> 2024-06-03 updates

- README.md
- Add `marvinroman/oh-my-zsh-git-patch-plugin` plugin
- Add `marvinroman/oh-my-zsh-mkcd-plugin` plugin
- Add `marvinroman/oh-my-zsh-gpg-plugin` plugin
- Add `wintermi/zsh-oh-my-posh` plugin for managing oh-my-posh theme configurations
> 2024-06-09 updates

- README.md
Added x-cmd to the list, x-cmd is a toolset implemented using posix shell and awk.
It is very small in size and offers many interesting features. Here is a milestone demo: https://x-cmd.com/
**Tools Provided by x-cmd:**
- [Wrappers for Common Commands (e.g., cd, ip, ps, tar, apt, brew)](https://x-cmd.com/mod/zuz): These wrapped commands are more intelligent and easier to use compared to the native commands.
- [Lightweight Package Management Tool](https://x-cmd.com/pkg/): We have implemented a lightweight package management tool using shell and awk. Through it, you can quickly obtain most common software tools, such as jq, 7za, bat, nvim, python, node, go, etc.
- [CLI for Useful Websites (e.g., github.com, cht.sh)](https://x-cmd.com/mod/cht): We have wrapped their APIs using shell and awk …
> Add x-cmd to the Frameworks  list.

- README.md
Been busy, so a big batch of updates
- Add `marcelohmdias/zsh-deno` tab completion
- Add `nmcc1212/shades-of-purple-windows-terminal`. Closes https://github.com/nmcc1212/shades-of-purple-windows-terminal/issues/1
- Add `remino/omz-plugin-iterm2-tmux-color-tabs` plugin
- Add `fairy-root/Zsh-Shortcuts-Plugin` plugin
- Add `Katrovsky/zsh-ollama-completion` tab completions
- Add `getantidote/use-omz` plugin
- Add `elvitin/printdocker-zsh-plugin` plugin
- Add `Hera-Moon/My-rabbit-Zsh-Theme` theme
- Add `seamile/mu-zsh-theme` theme
- Add `mubinben/purr-zsh-theme` theme
> 2024-07-13 updates

- README.md
- Add `twfksh/zsh-ssh-agent` plugin
- Add `ricard-ferrero/cafeconbits-zsh-theme` theme
- Add `tmccombs/thayne.zsh-theme` theme now that https://github.com/tmccombs/thayne.zsh-theme/issues/1 is closed
- Add `jbaranski/jeff-zsh-theme` theme
- Add `YourBrightSmile/ggZshTheme` now that https://github.com/YourBrightSmile/ggZshTheme/issues/1 is closed.
> 2024-07-15 updates

- README.md
- https://github.com/knid/tasko/issues/1 is closed, add `knid/tasko` plugin
- Move `mastern2k3/taskbook-zsh-plugin` to completions section
- https://github.com/Hietan/Hietan_ZshTheme/issues/1 is closed, add `hietan/hietan` theme
- Add `tech8i/zsh_sunrise`.  Closes https://github.com/tech8i/zsh_sunrise/issues/1
- Add `joshuadanpeterson/zsh-welcome-banner` now that https://github.com/joshuadanpeterson/zsh-welcome-banner/issues/1 is closed.
> 2024-07-24 updates

- README.md
- Add `TheEdgeOfRage/boban-zsh` theme
- Add `ArturDobrowolski/shiro-zsh-theme` theme
- Add `shirozuki/shiro-zsh-theme` theme
> 2024-07-27 updates

- README.md
- https://github.com/mortinger91/michelebira/issues/1 is closed, add `mortinger91/michelebira` theme
- https://github.com/odunlop/even-more-emojis/issues/1 is closed, add `odunlop/even-more-emojis`
- Update URL of `masaakifuruki/emoji.zsh-theme`
- Fix typo in `Bergiu/emojirussell` entry
- Fix sort of themes section
> 2024-08-10 updates

- README.md
- Add `SaltedBlowfish/zsh-shellcolor` plugin
- Add `mattmc3/ez-compinit` plugin
> 2024-08-15 updates

- README.md
- Add `raisedadead/zsh-snr` plugin
- Add `const-void/rose-pine-man` plugin for colorizing man pages
- Update `sheoak/zsh-bepoptimist` plugin entry
> 2024-08-18 updates

- README.md
> Move some themes from `Plugins` section into `Themes`

- README.md
- `hwk929/zsh-fzf` is 404, remove
- Update link to `igor9silva/igorsilva-zsh-theme`. Closes https://github.com/igor9silva/igorsilva-zsh-theme/issues/1
- Add `jhammerberg/jax-theme` now that https://github.com/jhammerberg/jax-theme/issues/1 is closed
- Add `vzambon/vszambon_ocean-zsh-theme` now that https://github.com/vzambon/vszambon_ocean-zsh-theme/issues/1 is closed
- Add `InfinityUniverse0/light-zsh` theme
> 2024-08-27 updates

- README.md
- https://github.com/thederpykrafter/cryptic.zsh-theme/issues/2 is closed, add `thederpykrafter/cryptic.zsh-theme`
- Add `davidparsson/zsh-nvm-deferred` plugin
> 2024-08-06

- README.md
Add `TomiVidal99/westchange` now that https://github.com/TomiVidal99/westchange/issues/1 is closed
- [ x] I have stripped any leading and/or trailing **zsh-**, **zsh-plugin** and/or **oh-my-zsh-** substrings from the link's displayed name. This makes it easier to find plugins/themes/completions by name by preventing big clusters in the **O** and **Z** sections of the list.
> Add `TomiVidal99/westchange`

- README.md
- Add `aungphyo-dev/ap2.zsh` theme now that https://github.com/aungphyo-dev/ap2.zsh/issues/1 is closed
- Add `brunomacedo/zsh-auto-pnpm-use` plugin now that https://github.com/brunomacedo/zsh-auto-pnpm-use/issues/1 is closed,
- Add `drkhsh/zsh-banner` now that https://github.com/drkhsh/zsh-banner/issues/1 is closed
- Add `SidonieBouthors/zido-zsh-theme` theme now that https://github.com/SidonieBouthors/zido-zsh-theme/issues/1 is closed
- Sort fix themes section
> 2024-09-27 updates

- README.md
Add link to https://github.com/joknarf/thefly. Been a while since there was a new framework.
> Add TheFly framework

- README.md
Add `iliutaadrian/zapmarks` plugin
> Add `iliutaadrian/zapmarks` plugin

- README.md
`lmllrjr/backbone-zsh-prompt` has moved to `42LM/backbone-zsh-prompt`
> Update backbone entry

- README.md
> 2024-11-10 updates

- README.md
Add `ryzshck/ryzshckt` framework
> Add `ryzshck/ryzshckt`

- README.md
- Add `MoeBensu/zsh-some-peco` now that https://github.com/MoeBensu/zsh-some-peco/issues/1 is closed
- Add missing badges to `ryzshc` framework entry
> 2024-11-18 updates

- README.md
- Add `MohamedElashri/adguard-helper` plugin
- Update `persiliao/persi-zsh-theme` entry
- `harvey103565/git-multi-sshacc-asst` is 404, remove
> 2024-11-21 updates

- README.md
- Add `kobylinski/caper-bush` plugin
- Add `PsychArch/nlsh` plugin
> 2024-11-28 updates

- README.md
Fixed the Markdown syntax for Github last commit tag on line 280.
Fixed the Markdown syntax for eza-ls link on line 944.
Modified description for terminal-aliases plugin on line 1457 to indicate that terraform and git are commands here and not other plugins. 
Removed an extraneous "]" on line 1671.
Fixed the Markdown syntax for robbyrussell theme link on line 2201.
- [x - I apologize, this is my first PR and I'm not quite sure what to do here but I viewed the resulting Markdown after my changes and they all look good] All new and existing tests passed.
> Made some typographical corrections and fixed some Markdown syntax errors.d

- README.md
- wangyandong-ningxia GH account is 404, delete `ningxia` theme
- https://github.com/sergkondr/skondrashov-zsh-theme/issues/1 is closed, add `sergkondr/skondrashov-zsh-theme`
- https://github.com/nautilor/lgbt.zsh-theme/issues/1 is closed, add `nautilor/lgbt.zsh-theme/`
- Add `Seraphin-/zsh-tailscale-ssh` tab completion
- Add `TheCrazyGM/zen` theme. Disambiguate `cybardev/zen.zsh`
- Add `dbushell/zigbar` prompt
- Add `BlackFlame444/dpd-plugin` plugin
- Add `eliyastein/llm-zsh-plugin`. Closes https://github.com/unixorn/awesome-zsh-plugins/issues/1969
> 2025-03-06 updates

- README.md
Add [zenquotes](https://github.com/aminelch/zenquotes) plugin
> Add zenquotes plugin

- README.md
- Add `jeffzhangc/sshpky_zsh_plugin` now that https://github.com/jeffzhangc/sshpky_zsh_plugin/issues/1 is closed.
- Add `ppcamp/zsh-lsi` plugin
> 2025-03-30 updates

- README.md
Hi! This PR adds a link to my Zsh theme [kerneldiego-zsh-theme](https://github.com/KernelDiego/kerneldiego-zsh-theme).
As suggested in [this issue](https://github.com/KernelDiego/kerneldiego-zsh-theme/issues/1), I have added:
- A license file (MIT).
- Screenshots of the theme.
- A proper README with installation instructions and preview.
Thank you for maintaining this awesome list!
> Add  theme

- README.md
- Add `caesar0301/zsh-shell-proxy` plugin
- Add `hjdarnel/org-hopper` now that https://github.com/hjdarnel/org-hopper/issues/1 is closed
- Add `gynamics/zsh-usepkg` ZSH framework
- Add `alalik/pycalc` plugin
- Add `kshnkvn/kindahv-zsh-theme` theme
> 2025-05-25 updates

- README.md
SOPS Crypt ZSH Plugin is for Mozilla SOPS that provides one-click encryption and decryption of files in the current directory and subdirectories.
Mainly use to development and GitOps.
> doc: add sops-crypt to plugin list

- README.md
- Add `Kikolator/proj-jumper` plugin
- Add `JeffreyYAJ/ykali-zsh` theme
- Add `rhorno/oh-my-zsh-git-plugin-cheatsheet` plugin now that https://github.com/rhorno/oh-my-zsh-git-plugin-cheatsheet/issues/1 is closed.
- Add `dizzpy/flutter-zsh-shortcuts` plugin
- Update `dalailahner/dalailahner.zsh-theme` entry
- Add awesome-lazy-zsh framework
- Add `JBarberU/zsh-tio` tab completion
- Add `JBarberU/zsh-justfile` tab completion
> 2025-07-02 updates

- README.md
- Update `molovo/filthy` theme entry
- Add `pressdarling/codex-zsh-plugin` tab completion
- Add `SckyzO/zsh-sshinfo` plugin
> 2025-07-12 updates

- README.md
> Add project aliases plugin
